// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.init.item.consumables;

public enum CapsuleType {
	STR("STR", 5), SKP("SKP", 5), RES("RES", 5), VIT("VIT", 5), PWR("PWR", 5), ENE("ENE", 5);
	private final String statName;
	private final Integer statPoints;

	@java.lang.SuppressWarnings("all")
	public String getStatName() {
		return this.statName;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getStatPoints() {
		return this.statPoints;
	}

	@java.lang.SuppressWarnings("all")
	private CapsuleType(final String statName, final Integer statPoints) {
		this.statName = statName;
		this.statPoints = statPoints;
	}
}
