// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.quest;

public abstract class QuestObjective {
	private final ObjectiveType type;
	private final int required;
	private int progress;
	private boolean completed;

	public QuestObjective(ObjectiveType type, int required) {
		this.type = type;
		this.required = required;
		this.progress = 0;
		this.completed = false;
	}

	public void setProgress(int progress) {
		this.progress = Math.min(progress, required);
		checkCompletion();
	}

	public void addProgress(int amount) {
		this.progress = Math.min(this.progress + amount, required);
		checkCompletion();
	}

	private void checkCompletion() {
		if (progress >= required) {
			completed = true;
		}
	}

	public abstract boolean checkProgress(Object... params);


	public enum ObjectiveType {
		ITEM, KILL, INTERACT, STRUCTURE, BIOME, DIMENSION, COORDS, TALK_TO, DRAGON_SUMMON, SKILL;
	}

	@java.lang.SuppressWarnings("all")
	public ObjectiveType getType() {
		return this.type;
	}

	@java.lang.SuppressWarnings("all")
	public int getRequired() {
		return this.required;
	}

	@java.lang.SuppressWarnings("all")
	public int getProgress() {
		return this.progress;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isCompleted() {
		return this.completed;
	}

	@java.lang.SuppressWarnings("all")
	public void setCompleted(final boolean completed) {
		this.completed = completed;
	}
}
