// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.quest;

import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;
import java.util.EnumSet;
import java.util.Set;

public abstract class QuestReward {
	private final RewardType type;
	private Set<Difficulty> difficulties = EnumSet.allOf(Difficulty.class);

	public QuestReward(RewardType type) {
		this.type = type;
	}

	public void setDifficulties(Set<Difficulty> difficulties) {
		this.difficulties = (difficulties == null || difficulties.isEmpty()) ? EnumSet.allOf(Difficulty.class) : EnumSet.copyOf(difficulties);
	}

	public abstract void giveReward(ServerPlayer player);

	public void giveReward(ServerPlayer player, double rewardMultiplier) {
		giveReward(player);
	}

	public abstract Component getDescription();

	public Component getDescription(double rewardMultiplier) {
		return getDescription();
	}

	public boolean isUnlockedFor(Difficulty difficulty) {
		return difficulties.contains(difficulty != null ? difficulty : Difficulty.NORMAL);
	}


	public enum RewardType {
		ITEM, GENERIC_ITEM, COMMAND, TPS, SKILL, ALIGNMENT, TRANSFORMATION, KI_TECHNIQUE;
	}

	@java.lang.SuppressWarnings("all")
	public RewardType getType() {
		return this.type;
	}

	@java.lang.SuppressWarnings("all")
	public Set<Difficulty> getDifficulties() {
		return this.difficulties;
	}
}
