// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.quest;
import java.util.ArrayList;
import java.util.List;

public class Saga {
    private final String id;
    private final String name;
    private final List<Quest> quests;
    private final SagaRequirements requirements;
    private boolean unlocked;
    private int currentQuestIndex;

    public Saga(String id, String name, List<Quest> quests, SagaRequirements requirements) {
        this.id = id;
        this.name = name;
        this.quests = quests != null ? quests : new ArrayList<>();
        this.requirements = requirements;
        this.unlocked = false;
        this.currentQuestIndex = 0;
    }

    public Quest getCurrentQuest() {
        if (currentQuestIndex >= 0 && currentQuestIndex < quests.size()) {
            return quests.get(currentQuestIndex);
        }
        return null;
    }

    public boolean advanceQuest() {
        if (currentQuestIndex < quests.size() - 1) {
            currentQuestIndex++;
            return true;
        }
        return false;
    }

    public boolean isCompleted() {
        return currentQuestIndex >= quests.size() - 1 && (getCurrentQuest() == null || getCurrentQuest().isCompleted());
    }

    public Quest getQuestById(int questId) {
        return quests.stream().filter(q -> q.getId() == questId).findFirst().orElse(null);
    }


    public record SagaRequirements(String previousSagaId) {
    }

    @java.lang.SuppressWarnings("all")
    public void setUnlocked(final boolean unlocked) {
        this.unlocked = unlocked;
    }

    @java.lang.SuppressWarnings("all")
    public void setCurrentQuestIndex(final int currentQuestIndex) {
        this.currentQuestIndex = currentQuestIndex;
    }

    @java.lang.SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public List<Quest> getQuests() {
        return this.quests;
    }

    @java.lang.SuppressWarnings("all")
    public SagaRequirements getRequirements() {
        return this.requirements;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isUnlocked() {
        return this.unlocked;
    }

    @java.lang.SuppressWarnings("all")
    public int getCurrentQuestIndex() {
        return this.currentQuestIndex;
    }
}
