project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .

preserve_hierarchy: true

files:
  - source: /src/main/resources/assets/dragonminez/lang/en_us.json
    translation: /src/main/resources/assets/dragonminez/lang/%locale_with_underscore%.json
    languages_mapping:
      locale_with_underscore:
        af: af_za
        ar: ar_sa
        ca: ca_es
        zh-CN: zh_cn
        zh-TW: zh_tw
        cs: cs_cz
        da: da_dk
        nl: nl_nl
        fi: fi_fi
        fr: fr_fr
        de: de_de
        el: el_gr
        he: he_il
        hu: hu_hu
        it: it_it
        ja: ja_jp
        ko: ko_kr
        nb: no_no
        pl: pl_pl
        pt-PT: pt_pt
        pt-BR: pt_br
        ro: ro_ro
        ru: ru_ru
        sr: sr_rs
        es-ES: es_es
        es-AR: es_ar
        es-CL: es_cl
        es-EC: es_ec
        es-MX: es_mx
        es-UY: es_uy
        es-VE: es_ve
        sv-SE: sv_se
        tr: tr_tr
        uk: uk_ua
        vi: vi_vn
