// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.config;

import com.dragonminez.common.combat.logic.player.TargetHelper;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CombatConfig {
	public static final String CURRENT_VERSION = ConfigManager.CONFIG_VERSION;
	private String configVersion;
	private Double staminaConsumptionRatio = 0.083;
	private Double blockStaminaCost = 0.25;
	private Integer knockdownDurationSeconds = 30;
	private Integer baselineFormDrain = 80;
	private Boolean killPlayersOnCombatLogout = true;
	private Double kiProtectionMitigationPerLevel = 0.025;
	private Double kiProtectionCostRatio = 0.15;
	private Double kiInfusionDamagePerLevel = 0.025;
	private Double kiInfusionBaseCostPct = 2.5;
	private Double kiInfusionMaxCostPct = 7.5;
	private Double baseDamageReductionCap = 0.75;
	private Double enchantmentDamageReductionCap = 0.85;
	private Double defenseDecayOnGuardBreak = 0.66;
	private Double flatMitigationFactor = 0.1;
	private Double flatMitigationMaxAbsorbFraction = 0.82;
	private Double defenseReductionScale = 0.11;
	private Boolean enableAdaptativeDefenseMitigation = true;
	private Double adaptativeMitigationParityRatio = 1.0;
	private Double adaptativeMitigationParityValue = 0.25;
	private Double adaptativeMitigationZeroRatio = 5.0;
	private Double adaptativeDefenseMitigationCap = 0.65;
	private Boolean cancelDamageEventIfMitigationTooHigh = true;
	private Double cancelDamageMitigationThreshold = 2.5;
	private Boolean accurateMobBattlePower = true;
	private Boolean enableBlocking = true;
	private Boolean enableParrying = true;
	private Integer parryWindowMs = 150;
	private Double parryStaminaCostPenalty = 2.0;
	private Integer blockBreakStunDurationTicks = 60;
	private Double poiseDamageMultiplier = 0.25;
	private Double blockDamageReductionCap = 0.65;
	private Double blockDamageReductionMin = 0.05;
	private Integer poiseRegenCooldown = 100;
	private Boolean enablePerfectEvasion = true;
	private Integer perfectEvasionWindowMs = 200;
	private Integer dashCooldownSeconds = 4;
	private Integer doubleDashCooldownSeconds = 12;
	private Integer teleportCooldownSeconds = 30;
	private Boolean combatFlyAutoSwitchOnDamage = true;
	private Integer combatFlyLockSeconds = 8;
	private Double combatFlyBaseSpeed = 0.3;
	private Double combatFlySprintSpeed = 0.5;
	private Double combatFlyHoldSpeedMultiplier = 1.6;
	private Double combatFlyDrainMultiplier = 0.5;
	private Double combatFlyImpulseKiCostPct = 0.05;
	private Integer combatFlyImpulseCooldownTicks = 25;
	private Map<String, KiWeaponConfig> kiWeaponsConfig = new HashMap<>() {
		{
			put("blade", new KiWeaponConfig(0.0, 0.25, 0.0, 0.075, -2.4, "#FFFFFF", "dragonminez:sword"));
			put("scythe", new KiWeaponConfig(0.0, 0.45, 0.0, 0.105, -2.8, "#FFFFFF", "dragonminez:scythe"));
			put("clawlance", new KiWeaponConfig(0.0, 0.65, 0.0, 0.175, -2.6, "#FFFFFF", "dragonminez:trident"));
		}
	};
	private Float upswingMultiplier = 0.5F;
	private Boolean allowAttackingMount = false;
	private Integer attackIntervalCap = 2;
	private Boolean weaponRegistryLogging = false;
	private Boolean weaponRegistryCompression = true;
	private Map<String, TargetHelper.Relation> playerRelations = new HashMap<>() {
		{
			put("minecraft:player", TargetHelper.Relation.HOSTILE);
			put("minecraft:villager", TargetHelper.Relation.NEUTRAL);
			put("minecraft:iron_golem", TargetHelper.Relation.NEUTRAL);
			put("guardvillagers:guard", TargetHelper.Relation.NEUTRAL);
		}
	};
	private List<String> masteryBlacklistEntities = new ArrayList<>(Arrays.asList("minecraft:silverfish", "dummmmmmy:target_dummy"));
	private TargetHelper.Relation playerRelationToPassives = TargetHelper.Relation.HOSTILE;
	private TargetHelper.Relation playerRelationToHostiles = TargetHelper.Relation.HOSTILE;
	private TargetHelper.Relation playerRelationToOther = TargetHelper.Relation.HOSTILE;
	private Boolean fallbackCompatibilityEnabled = true;
	private String blacklistItemIdRegex = "pickaxe";
	private List<CompatibilitySpecifier> fallbackCompatibility = new ArrayList<>(Arrays.asList(new CompatibilitySpecifier("claymore|great_sword|greatsword", "dragonminez:claymore"), new CompatibilitySpecifier("great_hammer|greathammer|war_hammer|warhammer|maul", "dragonminez:hammer"), new CompatibilitySpecifier("double_axe|doubleaxe|war_axe|waraxe|great_axe|greataxe", "dragonminez:double_axe"), new CompatibilitySpecifier("scythe", "dragonminez:scythe"), new CompatibilitySpecifier("halberd|glaive|pike|lance|naginata", "dragonminez:halberd"), new CompatibilitySpecifier("spear|trident|pitchfork|javelin", "dragonminez:spear"), new CompatibilitySpecifier("battlestaff|staff|quarterstaff|pole", "dragonminez:battlestaff"), new CompatibilitySpecifier("katana|uchigatana|nodachi|tachi", "dragonminez:katana"), new CompatibilitySpecifier("rapier|foil", "dragonminez:rapier"), new CompatibilitySpecifier("dagger|knife|shiv|dirk|kunai|karambit|wakizashi|tanto", "dragonminez:dagger"), new CompatibilitySpecifier("sickle|kama", "dragonminez:sickle"), new CompatibilitySpecifier("soul_knife", "dragonminez:soul_knife"), new CompatibilitySpecifier("claw|katar", "dragonminez:claw"), new CompatibilitySpecifier("wand", "dragonminez:wand"), new CompatibilitySpecifier("mace|hammer|flail", "dragonminez:mace"), new CompatibilitySpecifier("axe", "dragonminez:axe"), new CompatibilitySpecifier("coral_blade", "dragonminez:coral_blade"), new CompatibilitySpecifier("twin_blade|twinblade", "dragonminez:twin_blade"), new CompatibilitySpecifier("cutlass|scimitar|machete", "dragonminez:cutlass"), new CompatibilitySpecifier("sword|blade", "dragonminez:sword")));

	public float getUpswingMultiplier() {
		return Math.max(0.2F, Math.min(1.0F, upswingMultiplier));
	}

	public double getFlatMitigationFactor() {
		return flatMitigationFactor != null ? Math.max(0.0, flatMitigationFactor) : 0.1;
	}

	public double getFlatMitigationMaxAbsorbFraction() {
		return flatMitigationMaxAbsorbFraction != null ? Math.max(0.0, Math.min(1.0, flatMitigationMaxAbsorbFraction)) : 0.82;
	}

	public double getDefenseReductionScale() {
		return defenseReductionScale != null ? Math.max(0.01, defenseReductionScale) : 0.11;
	}

	public boolean getEnableAdaptativeDefenseMitigation() {
		return enableAdaptativeDefenseMitigation == null || enableAdaptativeDefenseMitigation;
	}

	public double getAdaptativeMitigationParityRatio() {
		return adaptativeMitigationParityRatio != null ? Math.max(1.0E-4, adaptativeMitigationParityRatio) : 1.0;
	}

	public double getAdaptativeMitigationParityValue() {
		return adaptativeMitigationParityValue != null ? Math.max(0.0, Math.min(1.0, adaptativeMitigationParityValue)) : 0.25;
	}

	public double getAdaptativeMitigationZeroRatio() {
		return adaptativeMitigationZeroRatio != null ? Math.max(getAdaptativeMitigationParityRatio() + 1.0E-4, adaptativeMitigationZeroRatio) : 5.0;
	}

	public double getAdaptativeDefenseMitigationCap() {
		return adaptativeDefenseMitigationCap != null ? Math.max(0.0, Math.min(1.0, adaptativeDefenseMitigationCap)) : 0.7;
	}

	public boolean getCancelDamageEventIfMitigationTooHigh() {
		return cancelDamageEventIfMitigationTooHigh == null || cancelDamageEventIfMitigationTooHigh;
	}

	public double getCancelDamageMitigationThreshold() {
		return cancelDamageMitigationThreshold != null ? Math.max(1.0, cancelDamageMitigationThreshold) : 3.0;
	}

	public boolean getAccurateMobBattlePower() {
		return accurateMobBattlePower == null || accurateMobBattlePower;
	}

	public KiWeaponConfig getKiWeaponConfig(String type) {
		if (type == null || kiWeaponsConfig == null) return null;
		return kiWeaponsConfig.get(type.toLowerCase());
	}

	public List<String> getKiWeaponTypes() {
		if (kiWeaponsConfig == null) return new ArrayList<>();
		List<String> keys = new ArrayList<>(kiWeaponsConfig.keySet());
		java.util.Collections.sort(keys);
		return keys;
	}


	public static class CompatibilitySpecifier {
		private String item_id_regex;
		private String weapon_attributes;

		@java.lang.SuppressWarnings("all")
		public CompatibilitySpecifier(final String item_id_regex, final String weapon_attributes) {
			this.item_id_regex = item_id_regex;
			this.weapon_attributes = weapon_attributes;
		}

		@java.lang.SuppressWarnings("all")
		public CompatibilitySpecifier() {
		}

		@java.lang.SuppressWarnings("all")
		public String getItem_id_regex() {
			return this.item_id_regex;
		}

		@java.lang.SuppressWarnings("all")
		public String getWeapon_attributes() {
			return this.weapon_attributes;
		}
	}


	public static class KiWeaponConfig {
		private Double baseDamage = 0.0;
		private Double kiScalingDamage = 1.0;
		private Double baseKiCost = 0.0;
		private Double kiScalingCost = 0.05;
		private Double attackSpeed = -2.4;
		private String forcedColor = "#FFFFFF";
		private String weaponCombo = "";

		public double getBaseDamage() {
			return baseDamage != null ? Math.max(0.0, baseDamage) : 0.0;
		}

		public double getKiScalingDamage() {
			return kiScalingDamage != null ? Math.max(0.0, kiScalingDamage) : 0.0;
		}

		public double getBaseKiCost() {
			return baseKiCost != null ? Math.max(0.0, baseKiCost) : 0.0;
		}

		public double getKiScalingCost() {
			return kiScalingCost != null ? Math.max(0.0, kiScalingCost) : 0.0;
		}

		public double getAttackSpeed() {
			return attackSpeed != null ? attackSpeed : 0.0;
		}

		@java.lang.SuppressWarnings("all")
		public KiWeaponConfig(final Double baseDamage, final Double kiScalingDamage, final Double baseKiCost, final Double kiScalingCost, final Double attackSpeed, final String forcedColor, final String weaponCombo) {
			this.baseDamage = baseDamage;
			this.kiScalingDamage = kiScalingDamage;
			this.baseKiCost = baseKiCost;
			this.kiScalingCost = kiScalingCost;
			this.attackSpeed = attackSpeed;
			this.forcedColor = forcedColor;
			this.weaponCombo = weaponCombo;
		}

		@java.lang.SuppressWarnings("all")
		public KiWeaponConfig() {
		}

		@java.lang.SuppressWarnings("all")
		public String getForcedColor() {
			return this.forcedColor;
		}

		@java.lang.SuppressWarnings("all")
		public String getWeaponCombo() {
			return this.weaponCombo;
		}
	}

	@java.lang.SuppressWarnings("all")
	public String getConfigVersion() {
		return this.configVersion;
	}

	@java.lang.SuppressWarnings("all")
	public Double getStaminaConsumptionRatio() {
		return this.staminaConsumptionRatio;
	}

	@java.lang.SuppressWarnings("all")
	public Double getBlockStaminaCost() {
		return this.blockStaminaCost;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getKnockdownDurationSeconds() {
		return this.knockdownDurationSeconds;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getBaselineFormDrain() {
		return this.baselineFormDrain;
	}

	@java.lang.SuppressWarnings("all")
	public Boolean getKillPlayersOnCombatLogout() {
		return this.killPlayersOnCombatLogout;
	}

	@java.lang.SuppressWarnings("all")
	public Double getKiProtectionMitigationPerLevel() {
		return this.kiProtectionMitigationPerLevel;
	}

	@java.lang.SuppressWarnings("all")
	public Double getKiProtectionCostRatio() {
		return this.kiProtectionCostRatio;
	}

	@java.lang.SuppressWarnings("all")
	public Double getKiInfusionDamagePerLevel() {
		return this.kiInfusionDamagePerLevel;
	}

	@java.lang.SuppressWarnings("all")
	public Double getKiInfusionBaseCostPct() {
		return this.kiInfusionBaseCostPct;
	}

	@java.lang.SuppressWarnings("all")
	public Double getKiInfusionMaxCostPct() {
		return this.kiInfusionMaxCostPct;
	}

	@java.lang.SuppressWarnings("all")
	public Double getBaseDamageReductionCap() {
		return this.baseDamageReductionCap;
	}

	@java.lang.SuppressWarnings("all")
	public Double getEnchantmentDamageReductionCap() {
		return this.enchantmentDamageReductionCap;
	}

	@java.lang.SuppressWarnings("all")
	public Double getDefenseDecayOnGuardBreak() {
		return this.defenseDecayOnGuardBreak;
	}

	@java.lang.SuppressWarnings("all")
	public Boolean getEnableBlocking() {
		return this.enableBlocking;
	}

	@java.lang.SuppressWarnings("all")
	public Boolean getEnableParrying() {
		return this.enableParrying;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getParryWindowMs() {
		return this.parryWindowMs;
	}

	@java.lang.SuppressWarnings("all")
	public Double getParryStaminaCostPenalty() {
		return this.parryStaminaCostPenalty;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getBlockBreakStunDurationTicks() {
		return this.blockBreakStunDurationTicks;
	}

	@java.lang.SuppressWarnings("all")
	public Double getPoiseDamageMultiplier() {
		return this.poiseDamageMultiplier;
	}

	@java.lang.SuppressWarnings("all")
	public Double getBlockDamageReductionCap() {
		return this.blockDamageReductionCap;
	}

	@java.lang.SuppressWarnings("all")
	public Double getBlockDamageReductionMin() {
		return this.blockDamageReductionMin;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getPoiseRegenCooldown() {
		return this.poiseRegenCooldown;
	}

	@java.lang.SuppressWarnings("all")
	public Boolean getEnablePerfectEvasion() {
		return this.enablePerfectEvasion;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getPerfectEvasionWindowMs() {
		return this.perfectEvasionWindowMs;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getDashCooldownSeconds() {
		return this.dashCooldownSeconds;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getDoubleDashCooldownSeconds() {
		return this.doubleDashCooldownSeconds;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getTeleportCooldownSeconds() {
		return this.teleportCooldownSeconds;
	}

	@java.lang.SuppressWarnings("all")
	public Boolean getCombatFlyAutoSwitchOnDamage() {
		return this.combatFlyAutoSwitchOnDamage;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getCombatFlyLockSeconds() {
		return this.combatFlyLockSeconds;
	}

	@java.lang.SuppressWarnings("all")
	public Double getCombatFlyBaseSpeed() {
		return this.combatFlyBaseSpeed;
	}

	@java.lang.SuppressWarnings("all")
	public Double getCombatFlySprintSpeed() {
		return this.combatFlySprintSpeed;
	}

	@java.lang.SuppressWarnings("all")
	public Double getCombatFlyHoldSpeedMultiplier() {
		return this.combatFlyHoldSpeedMultiplier;
	}

	@java.lang.SuppressWarnings("all")
	public Double getCombatFlyDrainMultiplier() {
		return this.combatFlyDrainMultiplier;
	}

	@java.lang.SuppressWarnings("all")
	public Double getCombatFlyImpulseKiCostPct() {
		return this.combatFlyImpulseKiCostPct;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getCombatFlyImpulseCooldownTicks() {
		return this.combatFlyImpulseCooldownTicks;
	}

	@java.lang.SuppressWarnings("all")
	public Map<String, KiWeaponConfig> getKiWeaponsConfig() {
		return this.kiWeaponsConfig;
	}

	@java.lang.SuppressWarnings("all")
	public Boolean getAllowAttackingMount() {
		return this.allowAttackingMount;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getAttackIntervalCap() {
		return this.attackIntervalCap;
	}

	@java.lang.SuppressWarnings("all")
	public Boolean getWeaponRegistryLogging() {
		return this.weaponRegistryLogging;
	}

	@java.lang.SuppressWarnings("all")
	public Boolean getWeaponRegistryCompression() {
		return this.weaponRegistryCompression;
	}

	@java.lang.SuppressWarnings("all")
	public Map<String, TargetHelper.Relation> getPlayerRelations() {
		return this.playerRelations;
	}

	@java.lang.SuppressWarnings("all")
	public List<String> getMasteryBlacklistEntities() {
		return this.masteryBlacklistEntities;
	}

	@java.lang.SuppressWarnings("all")
	public TargetHelper.Relation getPlayerRelationToPassives() {
		return this.playerRelationToPassives;
	}

	@java.lang.SuppressWarnings("all")
	public TargetHelper.Relation getPlayerRelationToHostiles() {
		return this.playerRelationToHostiles;
	}

	@java.lang.SuppressWarnings("all")
	public TargetHelper.Relation getPlayerRelationToOther() {
		return this.playerRelationToOther;
	}

	@java.lang.SuppressWarnings("all")
	public Boolean getFallbackCompatibilityEnabled() {
		return this.fallbackCompatibilityEnabled;
	}

	@java.lang.SuppressWarnings("all")
	public String getBlacklistItemIdRegex() {
		return this.blacklistItemIdRegex;
	}

	@java.lang.SuppressWarnings("all")
	public List<CompatibilitySpecifier> getFallbackCompatibility() {
		return this.fallbackCompatibility;
	}

	@java.lang.SuppressWarnings("all")
	public CombatConfig() {
	}

	@java.lang.SuppressWarnings("all")
	public void setConfigVersion(final String configVersion) {
		this.configVersion = configVersion;
	}
}
