package com.dragonminez.common.config;

import com.dragonminez.Env;
import com.dragonminez.LogUtil;
import com.dragonminez.common.util.lists.*;
import com.google.gson.Gson;

import java.io.IOException;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;

public class DefaultFormsFactory {

    private final ConfigLoader loader;

    public DefaultFormsFactory(Gson gson, ConfigLoader loader) {
        this.loader = loader;
    }

    private void setDefaultMasteryValues(FormConfig.FormData form) {
        form.setMaxMastery(100.0);
        form.setMasteryPerHit(0.05);
        form.setMasteryPerDamageReceived(0.05);
        form.setStatMultPerMasteryPoint(0.02);
        form.setCostDecreasePerMasteryPoint(0.02);
    }

    public void createDefaultFormsForRace(String raceName, Path formsPath, Map<String, FormConfig> forms) throws IOException {
        switch (raceName.toLowerCase()) {
			case "human" -> createDefaultHumanForms(formsPath, forms);
            case "saiyan" -> createSaiyanForms(formsPath, forms);
            case "namekian" -> createNamekianForms(formsPath, forms);
            case "frostdemon" -> createFrostDemonForms(formsPath, forms);
            case "majin" -> createMajinForms(formsPath, forms);
            case "bioandroid" -> createBioAndroidForms(formsPath, forms);
        }
    }

	private void createDefaultHumanForms(Path formsPath, Map<String, FormConfig> forms) throws IOException {
        FormConfig humanForms = new FormConfig();
        humanForms.setGroupName(HumanForms.GROUP_SUPERFORMS);
        humanForms.setFormType("super");

        FormConfig.FormData buffed = new FormConfig.FormData();
        buffed.setName(HumanForms.BUFFED);
        buffed.setUnlockOnSkillLevel(1);
        buffed.setCustomModel("");
        buffed.setModelScaling(1.1f);
        buffed.setStrMultiplier(1.75);
        buffed.setSkpMultiplier(1.75);
        buffed.setStmMultiplier(1.0);
        buffed.setDefMultiplier(1.25);
        buffed.setVitMultiplier(1.0);
        buffed.setPwrMultiplier(1.75);
        buffed.setEneMultiplier(1.0);
        buffed.setSpeedMultiplier(1.0);
        buffed.setEnergyDrain(0.08);
        buffed.setStaminaDrain(1.0);
        buffed.setAttackSpeed(1.0);
        buffed.setHairColor("");
        buffed.setEye1Color("");
        buffed.setEye2Color("");
        buffed.setAuraColor("");
        buffed.setBodyColor1("");
        buffed.setBodyColor2("");
        buffed.setBodyColor3("");
        buffed.setHairType(-1);
        setDefaultMasteryValues(buffed);
        buffed.setKaiokenStackable(true);
        buffed.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData fullPower = new FormConfig.FormData();
        fullPower.setName(HumanForms.FULLPOWER);
        fullPower.setUnlockOnSkillLevel(2);
        fullPower.setCustomModel("");
        fullPower.setModelScaling(1.0f);
        fullPower.setStrMultiplier(2.5);
        fullPower.setSkpMultiplier(2.5);
        fullPower.setStmMultiplier(1.0);
        fullPower.setDefMultiplier(1.65);
        fullPower.setVitMultiplier(1.0);
        fullPower.setPwrMultiplier(2.5);
        fullPower.setEneMultiplier(1.0);
        fullPower.setSpeedMultiplier(1.0);
        fullPower.setEnergyDrain(0.16);
        fullPower.setStaminaDrain(1.0);
        fullPower.setAttackSpeed(1.0);
        fullPower.setHairColor("");
        fullPower.setEye1Color("");
        fullPower.setEye2Color("");
        fullPower.setAuraColor("");
        fullPower.setBodyColor1("");
        fullPower.setBodyColor2("");
        fullPower.setBodyColor3("");
        fullPower.setHairType(-1);
        setDefaultMasteryValues(fullPower);
        fullPower.setKaiokenStackable(true);
        fullPower.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData overdrive = new FormConfig.FormData();
        overdrive.setName(HumanForms.OVERDRIVE);
        overdrive.setUnlockOnSkillLevel(3);
        overdrive.setCustomModel("");
        overdrive.setModelScaling(1.0f);
        overdrive.setStrMultiplier(3.5);
        overdrive.setSkpMultiplier(3.5);
        overdrive.setStmMultiplier(1.0);
        overdrive.setDefMultiplier(2.15);
        overdrive.setVitMultiplier(1.0);
        overdrive.setPwrMultiplier(3.5);
        overdrive.setEneMultiplier(1.0);
        overdrive.setSpeedMultiplier(1.0);
        overdrive.setEnergyDrain(0.34);
        overdrive.setStaminaDrain(1.0);
        overdrive.setAttackSpeed(1.0);
        overdrive.setHairColor("");
        overdrive.setEye1Color("");
        overdrive.setEye2Color("");
        overdrive.setAuraColor("");
        overdrive.setBodyColor1("");
        overdrive.setBodyColor2("");
        overdrive.setBodyColor3("");
        overdrive.setHairType(-1);
        setDefaultMasteryValues(overdrive);
        overdrive.setKaiokenStackable(true);
        overdrive.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData solaris = new FormConfig.FormData();
        solaris.setName(HumanForms.SOLARIS);
        solaris.setUnlockOnSkillLevel(4);
        solaris.setCustomModel("");
        solaris.setModelScaling(1.0f);
        solaris.setStrMultiplier(4.5);
        solaris.setSkpMultiplier(4.5);
        solaris.setStmMultiplier(1.0);
        solaris.setDefMultiplier(2.5);
        solaris.setVitMultiplier(1.0);
        solaris.setPwrMultiplier(4.5);
        solaris.setEneMultiplier(1.0);
        solaris.setSpeedMultiplier(1.0);
        solaris.setEnergyDrain(0.22);
        solaris.setStaminaDrain(1.0);
        solaris.setAttackSpeed(1.0);
        solaris.setHairColor("");
        solaris.setEye1Color("");
        solaris.setEye2Color("");
        solaris.setAuraColor("");
        solaris.setBodyColor1("");
        solaris.setBodyColor2("");
        solaris.setBodyColor3("");
        solaris.setHairType(-1);
        setDefaultMasteryValues(solaris);
        solaris.setKaiokenStackable(true);
        solaris.setKaiokenDrainMultiplier(2.0);

        Map<String, FormConfig.FormData> humanFormData = new LinkedHashMap<>();
        humanFormData.put(HumanForms.BUFFED, buffed);
        humanFormData.put(HumanForms.FULLPOWER, fullPower);
        humanFormData.put(HumanForms.OVERDRIVE, overdrive);
        humanFormData.put(HumanForms.SOLARIS, solaris);
        humanForms.setForms(humanFormData);

        forms.put(HumanForms.GROUP_SUPERFORMS, humanForms);

        Path humanPath = formsPath.resolve(HumanForms.GROUP_SUPERFORMS + ".json");
        loader.saveConfig(humanPath, humanForms);
        LogUtil.info(Env.COMMON, "Default Human forms created");
	}

    private void createSaiyanForms(Path formsPath, Map<String, FormConfig> forms) throws IOException {
        FormConfig oozaruForms = new FormConfig();
        oozaruForms.setGroupName(SaiyanForms.GROUP_OOZARU);
        oozaruForms.setFormType("super");

        FormConfig.FormData oozaru = new FormConfig.FormData();
        oozaru.setName(SaiyanForms.OOZARU);
        oozaru.setUnlockOnSkillLevel(0);
        oozaru.setCustomModel("oozaru");
        oozaru.setModelScaling(3.8f);
        oozaru.setStrMultiplier(1.2);
        oozaru.setSkpMultiplier(1.2);
        oozaru.setStmMultiplier(1.0);
        oozaru.setDefMultiplier(1.1);
        oozaru.setVitMultiplier(1.0);
        oozaru.setPwrMultiplier(1.2);
        oozaru.setEneMultiplier(1.0);
        oozaru.setSpeedMultiplier(0.8);
        oozaru.setEnergyDrain(0.05);
        oozaru.setStaminaDrain(1.2);
        oozaru.setAttackSpeed(0.9);
        oozaru.setHairColor("");
        oozaru.setEye1Color("");
        oozaru.setEye2Color("");
        oozaru.setAuraColor("");
        oozaru.setBodyColor1("");
        oozaru.setBodyColor2("");
        oozaru.setBodyColor3("");
        oozaru.setHairType(-1);
        setDefaultMasteryValues(oozaru);
		oozaru.setKaiokenStackable(true);
		oozaru.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData goldenOozaru = new FormConfig.FormData();
        goldenOozaru.setName(SaiyanForms.GOLDEN_OOZARU);
        goldenOozaru.setUnlockOnSkillLevel(7);
        goldenOozaru.setCustomModel("oozaru");
        goldenOozaru.setHairColor("#FFD700");
        goldenOozaru.setAuraColor("#FFD700");
        goldenOozaru.setModelScaling(3.8f);
        goldenOozaru.setStrMultiplier(3.0);
        goldenOozaru.setSkpMultiplier(3.0);
        goldenOozaru.setStmMultiplier(1.0);
        goldenOozaru.setDefMultiplier(1.9);
        goldenOozaru.setVitMultiplier(1.0);
        goldenOozaru.setPwrMultiplier(3.0);
        goldenOozaru.setEneMultiplier(1.0);
        goldenOozaru.setSpeedMultiplier(0.85);
        goldenOozaru.setEnergyDrain(0.24);
        goldenOozaru.setStaminaDrain(1.3);
        goldenOozaru.setAttackSpeed(1.0);
        goldenOozaru.setEye1Color("");
        goldenOozaru.setEye2Color("");
        goldenOozaru.setBodyColor1("");
        goldenOozaru.setBodyColor2("");
        goldenOozaru.setBodyColor3("");
        goldenOozaru.setHairType(-1);
        setDefaultMasteryValues(goldenOozaru);
		goldenOozaru.setKaiokenStackable(false);
		goldenOozaru.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData ssj4 = new FormConfig.FormData();
        ssj4.setName(SaiyanForms.SUPER_SAIYAN_4);
        ssj4.setUnlockOnSkillLevel(7);
        ssj4.setCustomModel("");
        ssj4.setHairColor("#000000");
        ssj4.setEye1Color("#FFD700");
        ssj4.setEye2Color("#FFD700");
        ssj4.setAuraColor("#FF0000");
        ssj4.setBodyColor1("");
        ssj4.setBodyColor2("");
        ssj4.setBodyColor3("");
        ssj4.setModelScaling(0.9375f);
        ssj4.setStrMultiplier(4.5);
        ssj4.setSkpMultiplier(4.5);
        ssj4.setStmMultiplier(1.0);
        ssj4.setDefMultiplier(2.5);
        ssj4.setVitMultiplier(1.0);
        ssj4.setPwrMultiplier(4.5);
        ssj4.setEneMultiplier(1.0);
        ssj4.setSpeedMultiplier(1.0);
        ssj4.setEnergyDrain(0.22);
        ssj4.setStaminaDrain(1.0);
        ssj4.setAttackSpeed(1.0);
        ssj4.setHairType(-1);
        setDefaultMasteryValues(ssj4);
		ssj4.setKaiokenStackable(false);
		ssj4.setKaiokenDrainMultiplier(2.0);

        Map<String, FormConfig.FormData> oozaruFormData = new LinkedHashMap<>();
        oozaruFormData.put(SaiyanForms.OOZARU, oozaru);
        oozaruFormData.put(SaiyanForms.GOLDEN_OOZARU, goldenOozaru);
        oozaruFormData.put(SaiyanForms.SUPER_SAIYAN_4, ssj4);
        oozaruForms.setForms(oozaruFormData);

        FormConfig ssGrades = new FormConfig();
        ssGrades.setGroupName(SaiyanForms.GROUP_SSGRADES);
        ssGrades.setFormType("super");

        FormConfig.FormData ssj1 = new FormConfig.FormData();
        ssj1.setName(SaiyanForms.SUPER_SAIYAN);
        ssj1.setUnlockOnSkillLevel(1);
        ssj1.setCustomModel("");
        ssj1.setHairColor("#FFEDB3");
        ssj1.setEye1Color("#00FFFF");
        ssj1.setEye2Color("#00FFFF");
        ssj1.setAuraColor("#FFD700");
        ssj1.setBodyColor1("");
        ssj1.setBodyColor2("");
        ssj1.setBodyColor3("");
        ssj1.setModelScaling(0.9375f);
        ssj1.setStrMultiplier(1.75);
        ssj1.setSkpMultiplier(1.75);
        ssj1.setStmMultiplier(1.0);
        ssj1.setDefMultiplier(1.25);
        ssj1.setVitMultiplier(1.0);
        ssj1.setPwrMultiplier(1.75);
        ssj1.setEneMultiplier(1.0);
        ssj1.setSpeedMultiplier(1.0);
        ssj1.setEnergyDrain(0.08);
        ssj1.setStaminaDrain(1.0);
        ssj1.setAttackSpeed(1.0);
        ssj1.setHairType(-1);
        setDefaultMasteryValues(ssj1);
        ssj1.setKaiokenStackable(true);
        ssj1.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData ssg2 = new FormConfig.FormData();
        ssg2.setName(SaiyanForms.SUPER_SAIYAN_GRADE_2);
        ssg2.setUnlockOnSkillLevel(2);
        ssg2.setCustomModel("");
        ssg2.setHairColor("#FFEDB3");
        ssg2.setEye1Color("#00FFFF");
        ssg2.setEye2Color("#00FFFF");
        ssg2.setAuraColor("#FFD700");
        ssg2.setBodyColor1("");
        ssg2.setBodyColor2("");
        ssg2.setBodyColor3("");
        ssg2.setModelScaling(1.1f);
        ssg2.setStrMultiplier(2.0);
        ssg2.setSkpMultiplier(2.0);
        ssg2.setStmMultiplier(1.0);
        ssg2.setDefMultiplier(1.4);
        ssg2.setVitMultiplier(1.0);
        ssg2.setPwrMultiplier(2.0);
        ssg2.setEneMultiplier(1.0);
        ssg2.setSpeedMultiplier(0.9);
        ssg2.setEnergyDrain(0.12);
        ssg2.setStaminaDrain(1.3);
        ssg2.setAttackSpeed(1.0);
        ssg2.setHairType(-1);
        setDefaultMasteryValues(ssg2);
        ssg2.setKaiokenStackable(true);
        ssg2.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData ssg3 = new FormConfig.FormData();
        ssg3.setName(SaiyanForms.SUPER_SAIYAN_GRADE_3);
        ssg3.setUnlockOnSkillLevel(3);
        ssg3.setCustomModel("");
        ssg3.setHairColor("#FFEDB3");
        ssg3.setEye1Color("#00FFFF");
        ssg3.setEye2Color("#00FFFF");
        ssg3.setAuraColor("#FFD700");
        ssg3.setBodyColor1("");
        ssg3.setBodyColor2("");
        ssg3.setBodyColor3("");
        ssg3.setModelScaling(1.2f);
        ssg3.setStrMultiplier(2.8);
        ssg3.setSkpMultiplier(2.8);
        ssg3.setStmMultiplier(1.0);
        ssg3.setDefMultiplier(1.8);
        ssg3.setVitMultiplier(1.0);
        ssg3.setPwrMultiplier(2.8);
        ssg3.setEneMultiplier(1.0);
        ssg3.setSpeedMultiplier(0.7);
        ssg3.setEnergyDrain(0.28);
        ssg3.setStaminaDrain(2.5);
        ssg3.setAttackSpeed(1.0);
        ssg3.setHairType(-1);
        setDefaultMasteryValues(ssg3);
        ssg3.setKaiokenStackable(true);
        ssg3.setKaiokenDrainMultiplier(2.0);

        Map<String, FormConfig.FormData> ssGradeForms = new LinkedHashMap<>();
        ssGradeForms.put(SaiyanForms.SUPER_SAIYAN, ssj1);
        ssGradeForms.put(SaiyanForms.SUPER_SAIYAN_GRADE_2, ssg2);
        ssGradeForms.put(SaiyanForms.SUPER_SAIYAN_GRADE_3, ssg3);
        ssGrades.setForms(ssGradeForms);

        FormConfig superSaiyan = new FormConfig();
        superSaiyan.setGroupName(SaiyanForms.GROUP_SUPERSAIYAN);
        superSaiyan.setFormType("super");

        FormConfig.FormData ssj1Mastered = new FormConfig.FormData();
        ssj1Mastered.setName(SaiyanForms.SUPER_SAIYAN_MASTERED);
        ssj1Mastered.setUnlockOnSkillLevel(4);
        ssj1Mastered.setCustomModel("");
        ssj1Mastered.setHairColor("#FFE89E");
        ssj1Mastered.setEye1Color("#00FFFF");
        ssj1Mastered.setEye2Color("#00FFFF");
        ssj1Mastered.setAuraColor("#FFD700");
        ssj1Mastered.setBodyColor1("");
        ssj1Mastered.setBodyColor2("");
        ssj1Mastered.setBodyColor3("");
        ssj1Mastered.setModelScaling(0.9375f);
        ssj1Mastered.setStrMultiplier(1.9);
        ssj1Mastered.setSkpMultiplier(1.9);
        ssj1Mastered.setStmMultiplier(1.0);
        ssj1Mastered.setDefMultiplier(1.35);
        ssj1Mastered.setVitMultiplier(1.0);
        ssj1Mastered.setPwrMultiplier(1.9);
        ssj1Mastered.setEneMultiplier(1.0);
        ssj1Mastered.setSpeedMultiplier(1.0);
        ssj1Mastered.setEnergyDrain(0.03);
        ssj1Mastered.setStaminaDrain(1.0);
        ssj1Mastered.setAttackSpeed(1.0);
        ssj1Mastered.setHairType(-1);
        setDefaultMasteryValues(ssj1Mastered);
        ssj1Mastered.setKaiokenStackable(true);
        ssj1Mastered.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData ssj2 = new FormConfig.FormData();
        ssj2.setName(SaiyanForms.SUPER_SAIYAN_2);
        ssj2.setUnlockOnSkillLevel(5);
        ssj2.setCustomModel("");
        ssj2.setHairColor("#FFE89E");
        ssj2.setEye1Color("#00FFFF");
        ssj2.setEye2Color("#00FFFF");
        ssj2.setAuraColor("#FFD700");
        ssj2.setBodyColor1("");
        ssj2.setBodyColor2("");
        ssj2.setBodyColor3("");
        ssj2.setModelScaling(0.9375f);
        ssj2.setStrMultiplier(2.5);
        ssj2.setSkpMultiplier(2.5);
        ssj2.setStmMultiplier(1.0);
        ssj2.setDefMultiplier(1.65);
        ssj2.setVitMultiplier(1.0);
        ssj2.setPwrMultiplier(2.5);
        ssj2.setEneMultiplier(1.0);
        ssj2.setSpeedMultiplier(1.0);
        ssj2.setEnergyDrain(0.16);
        ssj2.setStaminaDrain(1.0);
        ssj2.setAttackSpeed(1.0);
        ssj2.setHairType(-1);
        setDefaultMasteryValues(ssj2);
        ssj2.setKaiokenStackable(true);
        ssj2.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData ssj3 = new FormConfig.FormData();
        ssj3.setName(SaiyanForms.SUPER_SAIYAN_3);
        ssj3.setUnlockOnSkillLevel(6);
        ssj3.setCustomModel("");
        ssj3.setHairType(1);
        ssj3.setHairColor("#FFE89E");
        ssj3.setEye1Color("#00FFFF");
        ssj3.setEye2Color("#00FFFF");
        ssj3.setAuraColor("#FFD700");
        ssj3.setBodyColor1("");
        ssj3.setBodyColor2("");
        ssj3.setBodyColor3("");
        ssj3.setModelScaling(0.9375f);
        ssj3.setStrMultiplier(3.5);
        ssj3.setSkpMultiplier(3.5);
        ssj3.setStmMultiplier(1.0);
        ssj3.setDefMultiplier(2.15);
        ssj3.setVitMultiplier(1.0);
        ssj3.setPwrMultiplier(3.5);
        ssj3.setEneMultiplier(1.0);
        ssj3.setSpeedMultiplier(1.0);
        ssj3.setEnergyDrain(0.34);
        ssj3.setStaminaDrain(1.0);
        ssj3.setAttackSpeed(1.0);
        setDefaultMasteryValues(ssj3);
        ssj3.setKaiokenStackable(true);
        ssj3.setKaiokenDrainMultiplier(2.0);

        Map<String, FormConfig.FormData> superSaiyanForms = new LinkedHashMap<>();
        superSaiyanForms.put(SaiyanForms.SUPER_SAIYAN_MASTERED, ssj1Mastered);
        superSaiyanForms.put(SaiyanForms.SUPER_SAIYAN_2, ssj2);
        superSaiyanForms.put(SaiyanForms.SUPER_SAIYAN_3, ssj3);
        superSaiyan.setForms(superSaiyanForms);

        forms.put(SaiyanForms.OOZARU, oozaruForms);
        forms.put(SaiyanForms.GROUP_SSGRADES, ssGrades);
        forms.put(SaiyanForms.SUPER_SAIYAN, superSaiyan);

        Path oozaruPath = formsPath.resolve(SaiyanForms.OOZARU + ".json");
        loader.saveConfig(oozaruPath, oozaruForms);
        Path ssGradesPath = formsPath.resolve(SaiyanForms.GROUP_SSGRADES + ".json");
        loader.saveConfig(ssGradesPath, ssGrades);
        Path superSaiyanPath = formsPath.resolve(SaiyanForms.SUPER_SAIYAN + ".json");
        loader.saveConfig(superSaiyanPath, superSaiyan);
        LogUtil.info(Env.COMMON, "Default Super Saiyan forms created");
    }

    private void createNamekianForms(Path formsPath, Map<String, FormConfig> forms) throws IOException {
        FormConfig namekianForms = new FormConfig();
        namekianForms.setGroupName(NamekianForms.GROUP_SUPERFORMS);
        namekianForms.setFormType("super");

        FormConfig.FormData giantForm = new FormConfig.FormData();
        giantForm.setName(NamekianForms.GIANT);
        giantForm.setUnlockOnSkillLevel(1);
        giantForm.setCustomModel("");
        giantForm.setModelScaling(3.6f);
        giantForm.setStrMultiplier(1.95);
        giantForm.setSkpMultiplier(1.95);
        giantForm.setStmMultiplier(1.0);
        giantForm.setDefMultiplier(1.4);
        giantForm.setVitMultiplier(1.0);
        giantForm.setPwrMultiplier(1.95);
        giantForm.setEneMultiplier(1.0);
        giantForm.setSpeedMultiplier(1.0);
        giantForm.setEnergyDrain(0.09);
        giantForm.setStaminaDrain(1.0);
        giantForm.setAttackSpeed(1.0);
        giantForm.setHairColor("");
        giantForm.setEye1Color("");
        giantForm.setEye2Color("");
        giantForm.setAuraColor("");
        giantForm.setBodyColor1("");
        giantForm.setBodyColor2("");
        giantForm.setBodyColor3("");
        giantForm.setHairType(-1);
        setDefaultMasteryValues(giantForm);
        giantForm.setKaiokenStackable(true);
        giantForm.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData fullPower = new FormConfig.FormData();
        fullPower.setName(NamekianForms.FULLPOWER);
        fullPower.setUnlockOnSkillLevel(2);
        fullPower.setCustomModel("");
        fullPower.setModelScaling(1.0f);
        fullPower.setStrMultiplier(2.85);
        fullPower.setSkpMultiplier(2.85);
        fullPower.setStmMultiplier(1.0);
        fullPower.setDefMultiplier(1.85);
        fullPower.setVitMultiplier(1.0);
        fullPower.setPwrMultiplier(2.85);
        fullPower.setEneMultiplier(1.0);
        fullPower.setSpeedMultiplier(1.0);
        fullPower.setEnergyDrain(0.18);
        fullPower.setStaminaDrain(1.0);
        fullPower.setAttackSpeed(1.0);
        fullPower.setHairColor("");
        fullPower.setEye1Color("");
        fullPower.setEye2Color("");
        fullPower.setAuraColor("");
        fullPower.setBodyColor1("");
        fullPower.setBodyColor2("");
        fullPower.setBodyColor3("");
        fullPower.setHairType(-1);
        setDefaultMasteryValues(fullPower);
        fullPower.setKaiokenStackable(true);
        fullPower.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData superNamekian = new FormConfig.FormData();
        superNamekian.setName(NamekianForms.SUPER_NAMEKIAN);
        superNamekian.setUnlockOnSkillLevel(3);
        superNamekian.setCustomModel("");
        superNamekian.setAuraColor("#7FFF00");
        superNamekian.setModelScaling(1.05f);
        superNamekian.setStrMultiplier(4.0);
        superNamekian.setSkpMultiplier(4.0);
        superNamekian.setStmMultiplier(1.0);
        superNamekian.setDefMultiplier(2.35);
        superNamekian.setVitMultiplier(1.0);
        superNamekian.setPwrMultiplier(4.0);
        superNamekian.setEneMultiplier(1.0);
        superNamekian.setSpeedMultiplier(1.0);
        superNamekian.setEnergyDrain(0.27);
        superNamekian.setStaminaDrain(1.0);
        superNamekian.setAttackSpeed(1.0);
        superNamekian.setHairColor("");
        superNamekian.setEye1Color("");
        superNamekian.setEye2Color("");
        superNamekian.setBodyColor1("");
        superNamekian.setBodyColor2("");
        superNamekian.setBodyColor3("");
        superNamekian.setHairType(-1);
        setDefaultMasteryValues(superNamekian);
        superNamekian.setKaiokenStackable(true);
        superNamekian.setKaiokenDrainMultiplier(2.0);

        Map<String, FormConfig.FormData> namekianFormData = new LinkedHashMap<>();
        namekianFormData.put(NamekianForms.GIANT, giantForm);
        namekianFormData.put(NamekianForms.FULLPOWER, fullPower);
        namekianFormData.put(NamekianForms.SUPER_NAMEKIAN, superNamekian);
        namekianForms.setForms(namekianFormData);

        forms.put(NamekianForms.GROUP_SUPERFORMS, namekianForms);

        Path namekianPath = formsPath.resolve(NamekianForms.GROUP_SUPERFORMS + ".json");
        loader.saveConfig(namekianPath, namekianForms);
        LogUtil.info(Env.COMMON, "Default Namekian forms created");
    }

    private void createFrostDemonForms(Path formsPath, Map<String, FormConfig> forms) throws IOException {
        FormConfig frostForms = new FormConfig();
        frostForms.setGroupName(FrostDemonForms.GROUP_EVOLUTIONFORMS);
        frostForms.setFormType("super");

        FormConfig.FormData second = new FormConfig.FormData();
        second.setName(FrostDemonForms.SECOND_FORM);
        second.setUnlockOnSkillLevel(1);
        second.setCustomModel("");
        second.setModelScaling(1.3f);
        second.setStrMultiplier(1.75);
        second.setSkpMultiplier(1.75);
        second.setStmMultiplier(1.0);
        second.setDefMultiplier(1.25);
        second.setVitMultiplier(1.0);
        second.setPwrMultiplier(1.75);
        second.setEneMultiplier(1.0);
        second.setSpeedMultiplier(1.0);
        second.setEnergyDrain(0.0);
        second.setStaminaDrain(1.0);
        second.setAttackSpeed(1.0);
        second.setHairColor("");
        second.setEye1Color("");
        second.setEye2Color("");
        second.setAuraColor("");
        second.setBodyColor1("");
        second.setBodyColor2("");
        second.setBodyColor3("");
        second.setHairType(-1);
        setDefaultMasteryValues(second);
        second.setKaiokenStackable(true);
        second.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData third = new FormConfig.FormData();
        third.setName(FrostDemonForms.THIRD_FORM);
        third.setUnlockOnSkillLevel(2);
        third.setCustomModel("frostdemon_third");
        third.setModelScaling(1.4f);
        third.setStrMultiplier(2.5);
        third.setSkpMultiplier(2.5);
        third.setStmMultiplier(1.0);
        third.setDefMultiplier(1.65);
        third.setVitMultiplier(1.0);
        third.setPwrMultiplier(2.5);
        third.setEneMultiplier(1.0);
        third.setSpeedMultiplier(1.0);
        third.setEnergyDrain(0.0);
        third.setStaminaDrain(1.0);
        third.setAttackSpeed(1.0);
        third.setHairColor("");
        third.setEye1Color("");
        third.setEye2Color("");
        third.setAuraColor("");
        third.setBodyColor1("");
        third.setBodyColor2("");
        third.setBodyColor3("");
        third.setHairType(-1);
        setDefaultMasteryValues(third);
        third.setKaiokenStackable(true);
        third.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData finalForm = new FormConfig.FormData();
        finalForm.setName(FrostDemonForms.FINAL_FORM);
        finalForm.setUnlockOnSkillLevel(3);
        finalForm.setCustomModel("");
        finalForm.setModelScaling(1.0f);
        finalForm.setStrMultiplier(3.5);
        finalForm.setSkpMultiplier(3.5);
        finalForm.setStmMultiplier(1.0);
        finalForm.setDefMultiplier(2.15);
        finalForm.setVitMultiplier(1.0);
        finalForm.setPwrMultiplier(3.5);
        finalForm.setEneMultiplier(1.0);
        finalForm.setSpeedMultiplier(1.0);
        finalForm.setEnergyDrain(0.0);
        finalForm.setStaminaDrain(1.0);
        finalForm.setAttackSpeed(1.0);
        finalForm.setHairColor("");
        finalForm.setEye1Color("");
        finalForm.setEye2Color("");
        finalForm.setAuraColor("");
        finalForm.setBodyColor1("");
        finalForm.setBodyColor2("");
        finalForm.setBodyColor3("");
        finalForm.setHairType(-1);
        setDefaultMasteryValues(finalForm);
        finalForm.setKaiokenStackable(true);
        finalForm.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData fullPower = new FormConfig.FormData();
        fullPower.setName(FrostDemonForms.FULLPOWER);
        fullPower.setUnlockOnSkillLevel(4);
        fullPower.setCustomModel("");
        fullPower.setModelScaling(1.2f);
        fullPower.setStrMultiplier(4.5);
        fullPower.setSkpMultiplier(4.5);
        fullPower.setStmMultiplier(1.0);
        fullPower.setDefMultiplier(2.5);
        fullPower.setVitMultiplier(1.0);
        fullPower.setPwrMultiplier(4.5);
        fullPower.setEneMultiplier(1.0);
        fullPower.setSpeedMultiplier(1.0);
        fullPower.setEnergyDrain(0.22);
        fullPower.setStaminaDrain(1.0);
        fullPower.setAttackSpeed(1.0);
        fullPower.setHairColor("");
        fullPower.setEye1Color("");
        fullPower.setEye2Color("");
        fullPower.setAuraColor("");
        fullPower.setBodyColor1("");
        fullPower.setBodyColor2("");
        fullPower.setBodyColor3("");
        fullPower.setHairType(-1);
        setDefaultMasteryValues(fullPower);
        fullPower.setKaiokenStackable(true);
        fullPower.setKaiokenDrainMultiplier(2.0);

        Map<String, FormConfig.FormData> frostFormData = new LinkedHashMap<>();
        frostFormData.put(FrostDemonForms.SECOND_FORM, second);
        frostFormData.put(FrostDemonForms.THIRD_FORM, third);
        frostFormData.put(FrostDemonForms.FINAL_FORM, finalForm);
        frostFormData.put(FrostDemonForms.FULLPOWER, fullPower);
        frostForms.setForms(frostFormData);

        forms.put(FrostDemonForms.GROUP_EVOLUTIONFORMS, frostForms);

        Path frostPath = formsPath.resolve(FrostDemonForms.GROUP_EVOLUTIONFORMS + ".json");
        loader.saveConfig(frostPath, frostForms);
        LogUtil.info(Env.COMMON, "Default Frost Demon forms created");
    }

    private void createMajinForms(Path formsPath, Map<String, FormConfig> forms) throws IOException {
        FormConfig majinForms = new FormConfig();
        majinForms.setGroupName(MajinForms.GROUP_PUREFORMS);
        majinForms.setFormType("super");

        FormConfig.FormData kid = new FormConfig.FormData();
        kid.setName(MajinForms.KID);
        kid.setUnlockOnSkillLevel(1);
        kid.setCustomModel("human_slim");
        kid.setModelScaling(0.7f);
        kid.setStrMultiplier(1.75);
        kid.setSkpMultiplier(1.75);
        kid.setStmMultiplier(1.0);
        kid.setDefMultiplier(1.25);
        kid.setVitMultiplier(1.0);
        kid.setPwrMultiplier(1.75);
        kid.setEneMultiplier(1.0);
        kid.setSpeedMultiplier(1.0);
        kid.setEnergyDrain(0.0);
        kid.setStaminaDrain(1.0);
        kid.setAttackSpeed(1.0);
        kid.setHairColor("");
        kid.setEye1Color("");
        kid.setEye2Color("");
        kid.setAuraColor("");
        kid.setBodyColor1("");
        kid.setBodyColor2("");
        kid.setBodyColor3("");
        kid.setHairType(-1);
        setDefaultMasteryValues(kid);
        kid.setKaiokenStackable(true);
        kid.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData evil = new FormConfig.FormData();
        evil.setName(MajinForms.EVIL);
        evil.setUnlockOnSkillLevel(2);
        evil.setCustomModel("");
        evil.setModelScaling(1.0f);
        evil.setStrMultiplier(2.5);
        evil.setSkpMultiplier(2.5);
        evil.setStmMultiplier(1.0);
        evil.setDefMultiplier(1.65);
        evil.setVitMultiplier(1.0);
        evil.setPwrMultiplier(2.5);
        evil.setEneMultiplier(1.0);
        evil.setSpeedMultiplier(1.0);
        evil.setEnergyDrain(0.0);
        evil.setStaminaDrain(1.0);
        evil.setAttackSpeed(1.0);
        evil.setHairColor("");
        evil.setEye1Color("#FFFFFF");
        evil.setEye2Color("#FFFFFF");
        evil.setAuraColor("");
        evil.setBodyColor1("#917979");
        evil.setBodyColor2("#917979");
        evil.setBodyColor3("#917979");
        evil.setHairType(-1);
        setDefaultMasteryValues(evil);
        evil.setKaiokenStackable(true);
        evil.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData superForm = new FormConfig.FormData();
        superForm.setName(MajinForms.SUPER);
        superForm.setUnlockOnSkillLevel(3);
        superForm.setCustomModel("");
        superForm.setModelScaling(1.0f);
        superForm.setStrMultiplier(3.5);
        superForm.setSkpMultiplier(3.5);
        superForm.setStmMultiplier(1.0);
        superForm.setDefMultiplier(2.15);
        superForm.setVitMultiplier(1.0);
        superForm.setPwrMultiplier(3.5);
        superForm.setEneMultiplier(1.0);
        superForm.setSpeedMultiplier(1.0);
        superForm.setEnergyDrain(0.0);
        superForm.setStaminaDrain(1.0);
        superForm.setAttackSpeed(1.0);
        superForm.setHairColor("");
        superForm.setEye1Color("");
        superForm.setEye2Color("");
        superForm.setAuraColor("");
        superForm.setBodyColor1("");
        superForm.setBodyColor2("");
        superForm.setBodyColor3("");
        superForm.setHairType(-1);
        setDefaultMasteryValues(superForm);
        superForm.setKaiokenStackable(true);
        superForm.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData ultra = new FormConfig.FormData();
        ultra.setName(MajinForms.ULTRA);
        ultra.setUnlockOnSkillLevel(4);
        ultra.setCustomModel("");
        ultra.setModelScaling(1.2f);
        ultra.setStrMultiplier(4.5);
        ultra.setSkpMultiplier(4.5);
        ultra.setStmMultiplier(1.0);
        ultra.setDefMultiplier(2.5);
        ultra.setVitMultiplier(1.0);
        ultra.setPwrMultiplier(4.5);
        ultra.setEneMultiplier(1.0);
        ultra.setSpeedMultiplier(1.0);
        ultra.setEnergyDrain(0.22);
        ultra.setStaminaDrain(1.0);
        ultra.setAttackSpeed(1.0);
        ultra.setHairColor("");
        ultra.setEye1Color("");
        ultra.setEye2Color("");
        ultra.setAuraColor("");
        ultra.setBodyColor1("");
        ultra.setBodyColor2("");
        ultra.setBodyColor3("");
        ultra.setHairType(-1);
        setDefaultMasteryValues(ultra);
        ultra.setKaiokenStackable(true);
        ultra.setKaiokenDrainMultiplier(2.0);

        Map<String, FormConfig.FormData> majinFormData = new LinkedHashMap<>();
        majinFormData.put(MajinForms.KID, kid);
        majinFormData.put(MajinForms.EVIL, evil);
        majinFormData.put(MajinForms.SUPER, superForm);
        majinFormData.put(MajinForms.ULTRA, ultra);
        majinForms.setForms(majinFormData);

        forms.put(MajinForms.GROUP_PUREFORMS, majinForms);

        Path majinPath = formsPath.resolve(MajinForms.GROUP_PUREFORMS + ".json");
        loader.saveConfig(majinPath, majinForms);
        LogUtil.info(Env.COMMON, "Default Majin forms created");
    }

    private void createBioAndroidForms(Path formsPath, Map<String, FormConfig> forms) throws IOException {
        FormConfig bioForms = new FormConfig();
        bioForms.setGroupName(BioAndroidForms.GROUP_BIOEVOLUTION);
        bioForms.setFormType("super");

        FormConfig.FormData semiPerfect = new FormConfig.FormData();
        semiPerfect.setName(BioAndroidForms.SEMI_PERFECT);
        semiPerfect.setUnlockOnSkillLevel(1);
        semiPerfect.setCustomModel("bioandroid_semi");
        semiPerfect.setModelScaling(1.3f);
        semiPerfect.setStrMultiplier(1.95);
        semiPerfect.setSkpMultiplier(1.95);
        semiPerfect.setStmMultiplier(1.0);
        semiPerfect.setDefMultiplier(1.4);
        semiPerfect.setVitMultiplier(1.0);
        semiPerfect.setPwrMultiplier(1.95);
        semiPerfect.setEneMultiplier(1.0);
        semiPerfect.setSpeedMultiplier(1.0);
        semiPerfect.setEnergyDrain(0.0);
        semiPerfect.setStaminaDrain(1.0);
        semiPerfect.setAttackSpeed(1.0);
        semiPerfect.setHairColor("");
        semiPerfect.setEye1Color("");
        semiPerfect.setEye2Color("");
        semiPerfect.setAuraColor("");
        semiPerfect.setBodyColor1("");
        semiPerfect.setBodyColor2("");
        semiPerfect.setBodyColor3("");
        semiPerfect.setHairType(-1);
        setDefaultMasteryValues(semiPerfect);
        semiPerfect.setKaiokenStackable(true);
        semiPerfect.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData perfect = new FormConfig.FormData();
        perfect.setName(BioAndroidForms.PERFECT);
        perfect.setUnlockOnSkillLevel(2);
        perfect.setCustomModel("bioandroid_perfect");
        perfect.setModelScaling(1.1f);
        perfect.setStrMultiplier(2.85);
        perfect.setSkpMultiplier(2.85);
        perfect.setStmMultiplier(1.0);
        perfect.setDefMultiplier(1.85);
        perfect.setVitMultiplier(1.0);
        perfect.setPwrMultiplier(2.85);
        perfect.setEneMultiplier(1.0);
        perfect.setSpeedMultiplier(1.0);
        perfect.setEnergyDrain(0.0);
        perfect.setStaminaDrain(1.0);
        perfect.setAttackSpeed(1.0);
        perfect.setHairColor("");
        perfect.setEye1Color("");
        perfect.setEye2Color("");
        perfect.setAuraColor("");
        perfect.setBodyColor1("");
        perfect.setBodyColor2("");
        perfect.setBodyColor3("");
        perfect.setHairType(-1);
        setDefaultMasteryValues(perfect);
        perfect.setKaiokenStackable(true);
        perfect.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData superPerfect = new FormConfig.FormData();
        superPerfect.setName(BioAndroidForms.SUPER_PERFECT);
        superPerfect.setUnlockOnSkillLevel(3);
        superPerfect.setCustomModel("bioandroid_perfect");
        superPerfect.setModelScaling(1.2f);
        superPerfect.setStrMultiplier(4.0);
        superPerfect.setSkpMultiplier(4.0);
        superPerfect.setStmMultiplier(1.0);
        superPerfect.setDefMultiplier(2.35);
        superPerfect.setVitMultiplier(1.0);
        superPerfect.setPwrMultiplier(4.0);
        superPerfect.setEneMultiplier(1.0);
        superPerfect.setSpeedMultiplier(1.0);
        superPerfect.setEnergyDrain(0.16);
        superPerfect.setStaminaDrain(1.0);
        superPerfect.setAttackSpeed(1.0);
        superPerfect.setHairColor("");
        superPerfect.setEye1Color("");
        superPerfect.setEye2Color("");
        superPerfect.setAuraColor("");
        superPerfect.setBodyColor1("");
        superPerfect.setBodyColor2("");
        superPerfect.setBodyColor3("");
        superPerfect.setHairType(-1);
        setDefaultMasteryValues(superPerfect);
        superPerfect.setKaiokenStackable(true);
        superPerfect.setKaiokenDrainMultiplier(2.0);

        Map<String, FormConfig.FormData> bioFormData = new LinkedHashMap<>();
        bioFormData.put(BioAndroidForms.SEMI_PERFECT, semiPerfect);
        bioFormData.put(BioAndroidForms.PERFECT, perfect);
        bioFormData.put(BioAndroidForms.SUPER_PERFECT, superPerfect);
        bioForms.setForms(bioFormData);

        forms.put(BioAndroidForms.GROUP_BIOEVOLUTION, bioForms);

        Path bioAndroidPath = formsPath.resolve(BioAndroidForms.GROUP_BIOEVOLUTION + ".json");
        loader.saveConfig(bioAndroidPath, bioForms);
        LogUtil.info(Env.COMMON, "Default Bio Android forms created");
    }
}
