// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.config;

import net.minecraft.util.Mth;
import java.util.HashMap;
import java.util.Map;

public class EntitiesConfig {
	public static final String CURRENT_VERSION = ConfigManager.CONFIG_VERSION;
	private String configVersion;
	private Map<String, EntityStats> defaultEntityStats = new HashMap<>();
	/**
	 * Global defaults applied when a saga enemy transforms into its next form.
	 * Per-quest KILL objectives may override these individually; when neither a
	 * quest override nor a config value is present, the {@code ...Or(...)} helpers
	 * fall back to the historical hard-coded behaviour (1.5x stats, transform at 50% HP).
	 */
	private TransformSettings transformDefaults = new TransformSettings();


	public static class EntityStats {
		private Double health;
		private Double meleeDamage;
		private Double kiDamage;

		public Double getHealth() {
			return health != null ? Math.max(1, health) : null;
		}

		public Double getMeleeDamage() {
			return meleeDamage != null ? Math.max(1, meleeDamage) : null;
		}

		public Double getKiDamage() {
			return kiDamage != null ? Math.max(1, kiDamage) : null;
		}

		@java.lang.SuppressWarnings("all")
		public void setHealth(final Double health) {
			this.health = health;
		}

		@java.lang.SuppressWarnings("all")
		public void setMeleeDamage(final Double meleeDamage) {
			this.meleeDamage = meleeDamage;
		}

		@java.lang.SuppressWarnings("all")
		public void setKiDamage(final Double kiDamage) {
			this.kiDamage = kiDamage;
		}

		@java.lang.SuppressWarnings("all")
		public EntityStats() {
		}
	}


	public static class TransformSettings {
		/**
		 * Multiplier applied to the previous form's max health when transforming.
		 */
		private Double healthMultiplier;
		/**
		 * Multiplier applied to the previous form's melee (attack) damage when transforming.
		 */
		private Double meleeMultiplier;
		/**
		 * Multiplier applied to the previous form's ki blast damage when transforming.
		 */
		private Double kiMultiplier;
		/**
		 * Fraction of max health (0..1) at which the enemy triggers its transformation.
		 */
		private Double triggerHealthPercent;

		public double healthMultiplierOr(double fallback) {
			return healthMultiplier != null ? Math.max(0.1, healthMultiplier) : fallback;
		}

		public double meleeMultiplierOr(double fallback) {
			return meleeMultiplier != null ? Math.max(0.1, meleeMultiplier) : fallback;
		}

		public double kiMultiplierOr(double fallback) {
			return kiMultiplier != null ? Math.max(0.1, kiMultiplier) : fallback;
		}

		public double triggerHealthFractionOr(double fallback) {
			return triggerHealthPercent != null ? Mth.clamp(triggerHealthPercent, 0.0, 1.0) : fallback;
		}

		/**
		 * Multiplier applied to the previous form's max health when transforming.
		 */
		@java.lang.SuppressWarnings("all")
		public void setHealthMultiplier(final Double healthMultiplier) {
			this.healthMultiplier = healthMultiplier;
		}

		/**
		 * Multiplier applied to the previous form's melee (attack) damage when transforming.
		 */
		@java.lang.SuppressWarnings("all")
		public void setMeleeMultiplier(final Double meleeMultiplier) {
			this.meleeMultiplier = meleeMultiplier;
		}

		/**
		 * Multiplier applied to the previous form's ki blast damage when transforming.
		 */
		@java.lang.SuppressWarnings("all")
		public void setKiMultiplier(final Double kiMultiplier) {
			this.kiMultiplier = kiMultiplier;
		}

		/**
		 * Fraction of max health (0..1) at which the enemy triggers its transformation.
		 */
		@java.lang.SuppressWarnings("all")
		public void setTriggerHealthPercent(final Double triggerHealthPercent) {
			this.triggerHealthPercent = triggerHealthPercent;
		}

		@java.lang.SuppressWarnings("all")
		public TransformSettings() {
		}
	}

	@java.lang.SuppressWarnings("all")
	public String getConfigVersion() {
		return this.configVersion;
	}

	@java.lang.SuppressWarnings("all")
	public Map<String, EntityStats> getDefaultEntityStats() {
		return this.defaultEntityStats;
	}

	/**
	 * Global defaults applied when a saga enemy transforms into its next form.
	 * Per-quest KILL objectives may override these individually; when neither a
	 * quest override nor a config value is present, the {@code ...Or(...)} helpers
	 * fall back to the historical hard-coded behaviour (1.5x stats, transform at 50% HP).
	 */
	@java.lang.SuppressWarnings("all")
	public TransformSettings getTransformDefaults() {
		return this.transformDefaults;
	}

	@java.lang.SuppressWarnings("all")
	public EntitiesConfig() {
	}

	@java.lang.SuppressWarnings("all")
	public void setConfigVersion(final String configVersion) {
		this.configVersion = configVersion;
	}
}
