// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.config;

import java.util.*;

public class FormConfig {
	public static final String CURRENT_VERSION = ConfigManager.CONFIG_VERSION;
	private String configVersion;
	private String groupName;
	private String formType = "superforms";
	private Map<String, FormData> forms = new LinkedHashMap<>();

	public String getGroupName() {
		return groupName != null ? groupName : "";
	}

	public String getFormType() {
		return formType != null ? formType : "superforms";
	}

	public Map<String, FormData> getForms() {
		return forms != null ? forms : Collections.emptyMap();
	}

	public FormData getForm(String formName) {
		if (formName == null) return null;
		for (FormData formData : getForms().values()) {
			if (formData != null && formData.getName() != null && formData.getName().equalsIgnoreCase(formName)) return formData;
		}
		return null;
	}

	public FormData getFormByKey(String key) {
		return forms.get(key);
	}


	public static class FormData {
		private String name = "";
		private Integer unlockOnSkillLevel = 0;
		private String formCombo = "";
		private String customModel = "";
		private boolean keepBaseFormHeadBones = false;
		private String transformationAnimation = "transf.generic";
		private String bodyColor1 = "";
		private String bodyColor2 = "";
		private String bodyColor3 = "";
		private String extraFormLayer = "";
		private String extraFormColor = "";
		private String hairType = "";
		private String forcedHairCode = "";
		private String hairColor = "";
		private String eye1Color = "";
		private String eye2Color = "";
		private String auraType = "kakarot";
		private Integer auraLayer = 0;
		private String auraColor = "";
		private Integer extraAuraLayer = -1;
		private String extraAuraColor = "#FFFFFF";
		private String extraAuraType = "kakarot";
		private Boolean hasLightnings = false;
		private String lightningColor = "";
		private String tintColor = "#FF0000";
		private Double tintIntensity = 0.0;
		private Float[] modelScaling = {0.9375F, 0.9375F, 0.9375F};
		private Double strMultiplier = 1.0;
		private Double skpMultiplier = 1.0;
		private Double stmMultiplier = 1.0;
		private Double defMultiplier = 1.0;
		private Double vitMultiplier = 1.0;
		private Double pwrMultiplier = 1.0;
		private Double eneMultiplier = 1.0;
		private Double speedMultiplier = 1.0;
		private Double staminaDrainMultiplier = 1.0;
		private Double energyDrain = 0.0;
		private Double staminaDrain = 0.0;
		private Double healthDrain = 0.0;
		private Double attackSpeed = 1.0;
		private Double maxMastery = 100.0;
		private Double masteryPerHitDealt = 0.01;
		private Double masteryPerHitReceived = 0.01;
		private Double passiveMasteryEveryFiveSeconds = 0.001;
		private Double maxCostMultiplier = 0.5;
		private Double maxStatsMultiplier = 1.25;
		private String formRequisite = "";
		private String formRequisiteType = "all";
		private Double unlockOnMastery = 0.0;
		private Double stackOnMastery = 0.0;
		private Double instantTransformOnMastery = 40.0;
		private Double allowFreeTransformOnMastery = 50.0;
		private Boolean formStackable = true;
		private Double stackDrainMultiplier = 2.0;
		private List<String> incompatibleWith = new ArrayList<>(List.of("ultimate.ultimate"));
		private List<String> shareMasteryWith = new ArrayList<>();
		private Double shareMasteryMultiplier = 1.0;
		private OutlineShaderConfig outlineShader = new OutlineShaderConfig();
		private List<TriggerItemCost> triggerItemCosts = new ArrayList<>();
		private List<DurationItemCost> durationItemCosts = new ArrayList<>();
		private List<MobEffectConfig> mobEffects = new ArrayList<>();
		private transient float[] rgbBodyColor1;
		private transient float[] rgbBodyColor2;
		private transient float[] rgbBodyColor3;
		private transient float[] rgbHairColor;
		private transient float[] rgbEye1Color;
		private transient float[] rgbEye2Color;
		private transient float[] rgbAuraColor;
		private transient float[] rgbExtraFormColor;
		private transient float[] rgbExtraAuraColor;
		private transient float[] rgbTintColor;

		public Double getStrMultiplier() {
			return Math.max(0.01, strMultiplier);
		}

		public Double getSkpMultiplier() {
			return Math.max(0.01, skpMultiplier);
		}

		public Double getStmMultiplier() {
			return Math.max(0.01, stmMultiplier);
		}

		public Double getDefMultiplier() {
			return Math.max(0.01, defMultiplier);
		}

		public Double getVitMultiplier() {
			return Math.max(0.01, vitMultiplier);
		}

		public Double getPwrMultiplier() {
			return Math.max(0.01, pwrMultiplier);
		}

		public Double getEneMultiplier() {
			return Math.max(0.01, eneMultiplier);
		}

		public Double getSpeedMultiplier() {
			return Math.max(0.01, speedMultiplier);
		}

		public Double getStaminaDrainMultiplier() {
			return Math.max(0, staminaDrainMultiplier);
		}

		public Double getEnergyDrain() {
			return Math.max(0, energyDrain);
		}

		public Double getStaminaDrain() {
			return Math.max(0, staminaDrain);
		}

		public Double getHealthDrain() {
			return Math.max(0, healthDrain);
		}

		public Double getAttackSpeed() {
			return Math.max(0.1, attackSpeed);
		}

		public Double getMasteryPerHitDealt() {
			return Math.max(0, masteryPerHitDealt);
		}

		public Double getMasteryPerHitReceived() {
			return Math.max(0, masteryPerHitReceived);
		}

		public Double getPassiveMasteryEveryFiveSeconds() {
			return Math.max(0, passiveMasteryEveryFiveSeconds);
		}

		public Double getMaxCostMultiplier() {
			return Math.max(0, maxCostMultiplier);
		}

		public Double getMaxStatsMultiplier() {
			return Math.max(0, maxStatsMultiplier);
		}

		public String getFormRequisite() {
			return formRequisite != null ? formRequisite.trim() : "";
		}

		public String getFormRequisiteType() {
			return "any".equalsIgnoreCase(formRequisiteType != null ? formRequisiteType.trim() : "") ? "any" : "all";
		}

		public Double getUnlockOnMastery() {
			return Math.max(0, unlockOnMastery);
		}

		public Double getStackOnMastery() {
			return Math.max(0, stackOnMastery);
		}

		public Double getInstantTransformOnMastery() {
			return Math.max(0, instantTransformOnMastery);
		}

		public Double getAllowFreeTransformOnMastery() {
			return Math.max(0, allowFreeTransformOnMastery != null ? allowFreeTransformOnMastery : 50.0);
		}

		public List<String> getIncompatibleWith() {
			return incompatibleWith != null ? incompatibleWith : Collections.emptyList();
		}

		public List<String> getShareMasteryWith() {
			return shareMasteryWith != null ? shareMasteryWith : Collections.emptyList();
		}

		public Double getShareMasteryMultiplier() {
			return Math.max(0, shareMasteryMultiplier);
		}

		public boolean isIncompatibleWith(String groupId, String formId) {
			if (groupId == null || formId == null) return false;
			String key = (groupId + "." + formId).toLowerCase();
			for (String entry : getIncompatibleWith()) {
				if (entry != null && entry.trim().toLowerCase().equals(key)) return true;
			}
			return false;
		}

		public Double getStackDrainMultiplier() {
			return Math.max(0.01, stackDrainMultiplier);
		}

		public Boolean hasCustomModel() {
			return customModel != null && !customModel.isEmpty();
		}

		public boolean hasTransformationAnimation() {
			return transformationAnimation != null && !transformationAnimation.trim().isEmpty();
		}

		public String getTransformationAnimation() {
			return transformationAnimation != null ? transformationAnimation.trim() : "";
		}

		public Boolean hasBodyColorOverride() {
			return !bodyColor1.isEmpty() || !bodyColor2.isEmpty() || !bodyColor3.isEmpty();
		}

		public String getExtraFormLayer() {
			return extraFormLayer != null ? extraFormLayer.trim() : "";
		}

		public boolean hasExtraFormLayer() {
			return !getExtraFormLayer().isEmpty();
		}

		public Boolean hasDefinedHairType() {
			return hairType != null && !hairType.isEmpty();
		}

		public Boolean hasHairCodeOverride() {
			return !forcedHairCode.isEmpty();
		}

		public Boolean hasHairColorOverride() {
			return hairColor != null && !hairColor.isEmpty();
		}

		public Boolean hasEyeColorOverride() {
			return !eye1Color.isEmpty() || !eye2Color.isEmpty();
		}

		public Boolean hasAuraColorOverride() {
			return auraColor != null && !auraColor.isEmpty();
		}

		public int getExtraAuraLayer() {
			return extraAuraLayer != null ? extraAuraLayer : -1;
		}

		public boolean hasExtraAura() {
			int layer = getExtraAuraLayer();
			return layer >= 1 && layer <= 6;
		}

		public String getExtraAuraColor() {
			return extraAuraColor != null && !extraAuraColor.isEmpty() ? extraAuraColor : "#FFFFFF";
		}

		public String getExtraAuraType() {
			return extraAuraType != null && !extraAuraType.isEmpty() ? extraAuraType : "kakarot";
		}

		public OutlineShaderConfig getOutlineShader() {
			return outlineShader != null ? outlineShader : new OutlineShaderConfig();
		}

		public List<MobEffectConfig> getMobEffects() {
			return mobEffects != null ? mobEffects : Collections.emptyList();
		}

		public List<TriggerItemCost> getTriggerItemCosts() {
			return triggerItemCosts != null ? triggerItemCosts : Collections.emptyList();
		}

		public List<DurationItemCost> getDurationItemCosts() {
			return durationItemCosts != null ? durationItemCosts : Collections.emptyList();
		}

		public boolean hasTriggerItemCosts() {
			return triggerItemCosts != null && !triggerItemCosts.isEmpty();
		}

		public boolean hasDurationItemCosts() {
			return durationItemCosts != null && !durationItemCosts.isEmpty();
		}

		public float[] getRgbBodyColor1() {
			if (rgbBodyColor1 == null && bodyColor1 != null && !bodyColor1.isEmpty()) rgbBodyColor1 = com.dragonminez.client.util.ColorUtils.hexToRgb(bodyColor1);
			return rgbBodyColor1;
		}

		public float[] getRgbBodyColor2() {
			if (rgbBodyColor2 == null && bodyColor2 != null && !bodyColor2.isEmpty()) rgbBodyColor2 = com.dragonminez.client.util.ColorUtils.hexToRgb(bodyColor2);
			return rgbBodyColor2;
		}

		public float[] getRgbBodyColor3() {
			if (rgbBodyColor3 == null && bodyColor3 != null && !bodyColor3.isEmpty()) rgbBodyColor3 = com.dragonminez.client.util.ColorUtils.hexToRgb(bodyColor3);
			return rgbBodyColor3;
		}

		public float[] getRgbHairColor() {
			if (rgbHairColor == null && hairColor != null && !hairColor.isEmpty()) rgbHairColor = com.dragonminez.client.util.ColorUtils.hexToRgb(hairColor);
			return rgbHairColor;
		}

		public float[] getRgbEye1Color() {
			if (rgbEye1Color == null && eye1Color != null && !eye1Color.isEmpty()) rgbEye1Color = com.dragonminez.client.util.ColorUtils.hexToRgb(eye1Color);
			return rgbEye1Color;
		}

		public float[] getRgbEye2Color() {
			if (rgbEye2Color == null && eye2Color != null && !eye2Color.isEmpty()) rgbEye2Color = com.dragonminez.client.util.ColorUtils.hexToRgb(eye2Color);
			return rgbEye2Color;
		}

		public float[] getRgbAuraColor() {
			if (rgbAuraColor == null && auraColor != null && !auraColor.isEmpty()) rgbAuraColor = com.dragonminez.client.util.ColorUtils.hexToRgb(auraColor);
			return rgbAuraColor;
		}

		public float[] getRgbExtraFormColor() {
			if (rgbExtraFormColor == null && extraFormColor != null && !extraFormColor.isEmpty()) rgbExtraFormColor = com.dragonminez.client.util.ColorUtils.hexToRgb(extraFormColor);
			return rgbExtraFormColor;
		}

		public float[] getRgbExtraAuraColor() {
			if (rgbExtraAuraColor == null) rgbExtraAuraColor = com.dragonminez.client.util.ColorUtils.hexToRgb(getExtraAuraColor());
			return rgbExtraAuraColor;
		}

		public String getTintColor() {
			return tintColor != null ? tintColor : "";
		}

		public double getTintIntensity() {
			return tintIntensity != null ? Math.max(0.0, tintIntensity) : 0.0;
		}

		public float[] getRgbTintColor() {
			if (rgbTintColor == null && tintColor != null && !tintColor.isEmpty()) rgbTintColor = com.dragonminez.client.util.ColorUtils.hexToRgb(tintColor);
			return rgbTintColor;
		}

		public boolean hasTint() {
			return getTintIntensity() > 0.0 && getRgbTintColor() != null;
		}


		public static class MobEffectConfig {
			private String effectId = "";
			private Integer amplifier = 0;
			private Integer durationTicks = -1;
			private Boolean ambient = false;
			private Boolean visible = true;
			private Boolean showIcon = true;

			public String getEffectId() {
				return effectId != null ? effectId.trim() : "";
			}

			public int getAmplifier() {
				return Math.max(0, amplifier != null ? amplifier : 0);
			}

			public int getDurationTicks() {
				return durationTicks != null ? durationTicks : -1;
			}

			public boolean isPersistent() {
				return getDurationTicks() < 0;
			}

			public boolean isAmbient() {
				return Boolean.TRUE.equals(ambient);
			}

			public boolean isVisible() {
				return visible == null || visible;
			}

			public boolean isShowIcon() {
				return showIcon == null || showIcon;
			}

			@java.lang.SuppressWarnings("all")
			public void setEffectId(final String effectId) {
				this.effectId = effectId;
			}

			@java.lang.SuppressWarnings("all")
			public void setAmplifier(final Integer amplifier) {
				this.amplifier = amplifier;
			}

			@java.lang.SuppressWarnings("all")
			public void setDurationTicks(final Integer durationTicks) {
				this.durationTicks = durationTicks;
			}

			@java.lang.SuppressWarnings("all")
			public void setAmbient(final Boolean ambient) {
				this.ambient = ambient;
			}

			@java.lang.SuppressWarnings("all")
			public void setVisible(final Boolean visible) {
				this.visible = visible;
			}

			@java.lang.SuppressWarnings("all")
			public void setShowIcon(final Boolean showIcon) {
				this.showIcon = showIcon;
			}

			@java.lang.SuppressWarnings("all")
			public Boolean getAmbient() {
				return this.ambient;
			}

			@java.lang.SuppressWarnings("all")
			public Boolean getVisible() {
				return this.visible;
			}

			@java.lang.SuppressWarnings("all")
			public Boolean getShowIcon() {
				return this.showIcon;
			}

			@java.lang.SuppressWarnings("all")
			public MobEffectConfig() {
			}
		}


		public static class TriggerItemCost {
			private String itemId = "";
			private String itemTag = "";
			private String nbt = "";
			private Integer count = 1;
			private Boolean consume = true;

			public String getItemId() {
				return itemId != null ? itemId.trim() : "";
			}

			public String getItemTag() {
				return itemTag != null ? itemTag.trim() : "";
			}

			public String getNbt() {
				return nbt != null ? nbt.trim() : "";
			}

			public int getCount() {
				return Math.max(1, count != null ? count : 1);
			}

			public boolean isConsume() {
				return consume == null || consume;
			}

			public boolean hasItemId() {
				return !getItemId().isEmpty();
			}

			public boolean hasItemTag() {
				return !getItemTag().isEmpty();
			}

			public boolean hasNbt() {
				return !getNbt().isEmpty();
			}

			@java.lang.SuppressWarnings("all")
			public void setItemId(final String itemId) {
				this.itemId = itemId;
			}

			@java.lang.SuppressWarnings("all")
			public void setItemTag(final String itemTag) {
				this.itemTag = itemTag;
			}

			@java.lang.SuppressWarnings("all")
			public void setNbt(final String nbt) {
				this.nbt = nbt;
			}

			@java.lang.SuppressWarnings("all")
			public void setCount(final Integer count) {
				this.count = count;
			}

			@java.lang.SuppressWarnings("all")
			public void setConsume(final Boolean consume) {
				this.consume = consume;
			}

			@java.lang.SuppressWarnings("all")
			public Boolean getConsume() {
				return this.consume;
			}

			@java.lang.SuppressWarnings("all")
			public TriggerItemCost() {
			}
		}


		public static class DurationItemCost {
			private String itemId = "";
			private String itemTag = "";
			private String nbt = "";
			private Integer durationSeconds = 1;

			public String getItemId() {
				return itemId != null ? itemId.trim() : "";
			}

			public String getItemTag() {
				return itemTag != null ? itemTag.trim() : "";
			}

			public String getNbt() {
				return nbt != null ? nbt.trim() : "";
			}

			public int getDurationSeconds() {
				return Math.max(1, durationSeconds != null ? durationSeconds : 1);
			}

			public boolean hasItemId() {
				return !getItemId().isEmpty();
			}

			public boolean hasItemTag() {
				return !getItemTag().isEmpty();
			}

			public boolean hasNbt() {
				return !getNbt().isEmpty();
			}

			@java.lang.SuppressWarnings("all")
			public void setItemId(final String itemId) {
				this.itemId = itemId;
			}

			@java.lang.SuppressWarnings("all")
			public void setItemTag(final String itemTag) {
				this.itemTag = itemTag;
			}

			@java.lang.SuppressWarnings("all")
			public void setNbt(final String nbt) {
				this.nbt = nbt;
			}

			@java.lang.SuppressWarnings("all")
			public void setDurationSeconds(final Integer durationSeconds) {
				this.durationSeconds = durationSeconds;
			}

			@java.lang.SuppressWarnings("all")
			public DurationItemCost() {
			}
		}


		public static class OutlineShaderConfig {
			private Boolean enabled = false;
			private String primaryColor = "#7FFFFF";
			private String secondaryColor = "#7FFFFF";
			private Double outlineThickness = 1.5;

			public boolean isEnabled() {
				return Boolean.TRUE.equals(enabled);
			}

			public String getPrimaryColor() {
				return primaryColor != null && !primaryColor.isEmpty() ? primaryColor : "#7FFFFF";
			}

			public String getSecondaryColor() {
				return secondaryColor != null && !secondaryColor.isEmpty() ? secondaryColor : "#FFD970";
			}

			public double getOutlineThickness() {
				return Math.max(0.0, outlineThickness != null ? outlineThickness : 1.5);
			}

			@java.lang.SuppressWarnings("all")
			public void setEnabled(final Boolean enabled) {
				this.enabled = enabled;
			}

			@java.lang.SuppressWarnings("all")
			public void setPrimaryColor(final String primaryColor) {
				this.primaryColor = primaryColor;
			}

			@java.lang.SuppressWarnings("all")
			public void setSecondaryColor(final String secondaryColor) {
				this.secondaryColor = secondaryColor;
			}

			@java.lang.SuppressWarnings("all")
			public void setOutlineThickness(final Double outlineThickness) {
				this.outlineThickness = outlineThickness;
			}

			@java.lang.SuppressWarnings("all")
			public Boolean getEnabled() {
				return this.enabled;
			}

			@java.lang.SuppressWarnings("all")
			public OutlineShaderConfig() {
			}
		}

		@java.lang.SuppressWarnings("all")
		public void setName(final String name) {
			this.name = name;
		}

		@java.lang.SuppressWarnings("all")
		public void setUnlockOnSkillLevel(final Integer unlockOnSkillLevel) {
			this.unlockOnSkillLevel = unlockOnSkillLevel;
		}

		@java.lang.SuppressWarnings("all")
		public void setFormCombo(final String formCombo) {
			this.formCombo = formCombo;
		}

		@java.lang.SuppressWarnings("all")
		public void setCustomModel(final String customModel) {
			this.customModel = customModel;
		}

		@java.lang.SuppressWarnings("all")
		public void setKeepBaseFormHeadBones(final boolean keepBaseFormHeadBones) {
			this.keepBaseFormHeadBones = keepBaseFormHeadBones;
		}

		@java.lang.SuppressWarnings("all")
		public void setTransformationAnimation(final String transformationAnimation) {
			this.transformationAnimation = transformationAnimation;
		}

		@java.lang.SuppressWarnings("all")
		public void setBodyColor1(final String bodyColor1) {
			this.bodyColor1 = bodyColor1;
		}

		@java.lang.SuppressWarnings("all")
		public void setBodyColor2(final String bodyColor2) {
			this.bodyColor2 = bodyColor2;
		}

		@java.lang.SuppressWarnings("all")
		public void setBodyColor3(final String bodyColor3) {
			this.bodyColor3 = bodyColor3;
		}

		@java.lang.SuppressWarnings("all")
		public void setExtraFormLayer(final String extraFormLayer) {
			this.extraFormLayer = extraFormLayer;
		}

		@java.lang.SuppressWarnings("all")
		public void setExtraFormColor(final String extraFormColor) {
			this.extraFormColor = extraFormColor;
		}

		@java.lang.SuppressWarnings("all")
		public void setHairType(final String hairType) {
			this.hairType = hairType;
		}

		@java.lang.SuppressWarnings("all")
		public void setForcedHairCode(final String forcedHairCode) {
			this.forcedHairCode = forcedHairCode;
		}

		@java.lang.SuppressWarnings("all")
		public void setHairColor(final String hairColor) {
			this.hairColor = hairColor;
		}

		@java.lang.SuppressWarnings("all")
		public void setEye1Color(final String eye1Color) {
			this.eye1Color = eye1Color;
		}

		@java.lang.SuppressWarnings("all")
		public void setEye2Color(final String eye2Color) {
			this.eye2Color = eye2Color;
		}

		@java.lang.SuppressWarnings("all")
		public void setAuraType(final String auraType) {
			this.auraType = auraType;
		}

		@java.lang.SuppressWarnings("all")
		public void setAuraLayer(final Integer auraLayer) {
			this.auraLayer = auraLayer;
		}

		@java.lang.SuppressWarnings("all")
		public void setAuraColor(final String auraColor) {
			this.auraColor = auraColor;
		}

		@java.lang.SuppressWarnings("all")
		public void setExtraAuraLayer(final Integer extraAuraLayer) {
			this.extraAuraLayer = extraAuraLayer;
		}

		@java.lang.SuppressWarnings("all")
		public void setExtraAuraColor(final String extraAuraColor) {
			this.extraAuraColor = extraAuraColor;
		}

		@java.lang.SuppressWarnings("all")
		public void setExtraAuraType(final String extraAuraType) {
			this.extraAuraType = extraAuraType;
		}

		@java.lang.SuppressWarnings("all")
		public void setHasLightnings(final Boolean hasLightnings) {
			this.hasLightnings = hasLightnings;
		}

		@java.lang.SuppressWarnings("all")
		public void setLightningColor(final String lightningColor) {
			this.lightningColor = lightningColor;
		}

		@java.lang.SuppressWarnings("all")
		public void setTintColor(final String tintColor) {
			this.tintColor = tintColor;
		}

		@java.lang.SuppressWarnings("all")
		public void setTintIntensity(final Double tintIntensity) {
			this.tintIntensity = tintIntensity;
		}

		@java.lang.SuppressWarnings("all")
		public void setModelScaling(final Float[] modelScaling) {
			this.modelScaling = modelScaling;
		}

		@java.lang.SuppressWarnings("all")
		public void setStrMultiplier(final Double strMultiplier) {
			this.strMultiplier = strMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setSkpMultiplier(final Double skpMultiplier) {
			this.skpMultiplier = skpMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setStmMultiplier(final Double stmMultiplier) {
			this.stmMultiplier = stmMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setDefMultiplier(final Double defMultiplier) {
			this.defMultiplier = defMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setVitMultiplier(final Double vitMultiplier) {
			this.vitMultiplier = vitMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setPwrMultiplier(final Double pwrMultiplier) {
			this.pwrMultiplier = pwrMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setEneMultiplier(final Double eneMultiplier) {
			this.eneMultiplier = eneMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setSpeedMultiplier(final Double speedMultiplier) {
			this.speedMultiplier = speedMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setStaminaDrainMultiplier(final Double staminaDrainMultiplier) {
			this.staminaDrainMultiplier = staminaDrainMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setEnergyDrain(final Double energyDrain) {
			this.energyDrain = energyDrain;
		}

		@java.lang.SuppressWarnings("all")
		public void setStaminaDrain(final Double staminaDrain) {
			this.staminaDrain = staminaDrain;
		}

		@java.lang.SuppressWarnings("all")
		public void setHealthDrain(final Double healthDrain) {
			this.healthDrain = healthDrain;
		}

		@java.lang.SuppressWarnings("all")
		public void setAttackSpeed(final Double attackSpeed) {
			this.attackSpeed = attackSpeed;
		}

		@java.lang.SuppressWarnings("all")
		public void setMaxMastery(final Double maxMastery) {
			this.maxMastery = maxMastery;
		}

		@java.lang.SuppressWarnings("all")
		public void setMasteryPerHitDealt(final Double masteryPerHitDealt) {
			this.masteryPerHitDealt = masteryPerHitDealt;
		}

		@java.lang.SuppressWarnings("all")
		public void setMasteryPerHitReceived(final Double masteryPerHitReceived) {
			this.masteryPerHitReceived = masteryPerHitReceived;
		}

		@java.lang.SuppressWarnings("all")
		public void setPassiveMasteryEveryFiveSeconds(final Double passiveMasteryEveryFiveSeconds) {
			this.passiveMasteryEveryFiveSeconds = passiveMasteryEveryFiveSeconds;
		}

		@java.lang.SuppressWarnings("all")
		public void setMaxCostMultiplier(final Double maxCostMultiplier) {
			this.maxCostMultiplier = maxCostMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setMaxStatsMultiplier(final Double maxStatsMultiplier) {
			this.maxStatsMultiplier = maxStatsMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setFormRequisite(final String formRequisite) {
			this.formRequisite = formRequisite;
		}

		@java.lang.SuppressWarnings("all")
		public void setFormRequisiteType(final String formRequisiteType) {
			this.formRequisiteType = formRequisiteType;
		}

		@java.lang.SuppressWarnings("all")
		public void setUnlockOnMastery(final Double unlockOnMastery) {
			this.unlockOnMastery = unlockOnMastery;
		}

		@java.lang.SuppressWarnings("all")
		public void setStackOnMastery(final Double stackOnMastery) {
			this.stackOnMastery = stackOnMastery;
		}

		@java.lang.SuppressWarnings("all")
		public void setInstantTransformOnMastery(final Double instantTransformOnMastery) {
			this.instantTransformOnMastery = instantTransformOnMastery;
		}

		@java.lang.SuppressWarnings("all")
		public void setAllowFreeTransformOnMastery(final Double allowFreeTransformOnMastery) {
			this.allowFreeTransformOnMastery = allowFreeTransformOnMastery;
		}

		@java.lang.SuppressWarnings("all")
		public void setFormStackable(final Boolean formStackable) {
			this.formStackable = formStackable;
		}

		@java.lang.SuppressWarnings("all")
		public void setStackDrainMultiplier(final Double stackDrainMultiplier) {
			this.stackDrainMultiplier = stackDrainMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setIncompatibleWith(final List<String> incompatibleWith) {
			this.incompatibleWith = incompatibleWith;
		}

		@java.lang.SuppressWarnings("all")
		public void setShareMasteryWith(final List<String> shareMasteryWith) {
			this.shareMasteryWith = shareMasteryWith;
		}

		@java.lang.SuppressWarnings("all")
		public void setShareMasteryMultiplier(final Double shareMasteryMultiplier) {
			this.shareMasteryMultiplier = shareMasteryMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setOutlineShader(final OutlineShaderConfig outlineShader) {
			this.outlineShader = outlineShader;
		}

		@java.lang.SuppressWarnings("all")
		public void setTriggerItemCosts(final List<TriggerItemCost> triggerItemCosts) {
			this.triggerItemCosts = triggerItemCosts;
		}

		@java.lang.SuppressWarnings("all")
		public void setDurationItemCosts(final List<DurationItemCost> durationItemCosts) {
			this.durationItemCosts = durationItemCosts;
		}

		@java.lang.SuppressWarnings("all")
		public void setMobEffects(final List<MobEffectConfig> mobEffects) {
			this.mobEffects = mobEffects;
		}

		@java.lang.SuppressWarnings("all")
		public void setRgbBodyColor1(final float[] rgbBodyColor1) {
			this.rgbBodyColor1 = rgbBodyColor1;
		}

		@java.lang.SuppressWarnings("all")
		public void setRgbBodyColor2(final float[] rgbBodyColor2) {
			this.rgbBodyColor2 = rgbBodyColor2;
		}

		@java.lang.SuppressWarnings("all")
		public void setRgbBodyColor3(final float[] rgbBodyColor3) {
			this.rgbBodyColor3 = rgbBodyColor3;
		}

		@java.lang.SuppressWarnings("all")
		public void setRgbHairColor(final float[] rgbHairColor) {
			this.rgbHairColor = rgbHairColor;
		}

		@java.lang.SuppressWarnings("all")
		public void setRgbEye1Color(final float[] rgbEye1Color) {
			this.rgbEye1Color = rgbEye1Color;
		}

		@java.lang.SuppressWarnings("all")
		public void setRgbEye2Color(final float[] rgbEye2Color) {
			this.rgbEye2Color = rgbEye2Color;
		}

		@java.lang.SuppressWarnings("all")
		public void setRgbAuraColor(final float[] rgbAuraColor) {
			this.rgbAuraColor = rgbAuraColor;
		}

		@java.lang.SuppressWarnings("all")
		public void setRgbExtraFormColor(final float[] rgbExtraFormColor) {
			this.rgbExtraFormColor = rgbExtraFormColor;
		}

		@java.lang.SuppressWarnings("all")
		public void setRgbExtraAuraColor(final float[] rgbExtraAuraColor) {
			this.rgbExtraAuraColor = rgbExtraAuraColor;
		}

		@java.lang.SuppressWarnings("all")
		public void setRgbTintColor(final float[] rgbTintColor) {
			this.rgbTintColor = rgbTintColor;
		}

		@java.lang.SuppressWarnings("all")
		public String getName() {
			return this.name;
		}

		@java.lang.SuppressWarnings("all")
		public Integer getUnlockOnSkillLevel() {
			return this.unlockOnSkillLevel;
		}

		@java.lang.SuppressWarnings("all")
		public String getFormCombo() {
			return this.formCombo;
		}

		@java.lang.SuppressWarnings("all")
		public String getCustomModel() {
			return this.customModel;
		}

		@java.lang.SuppressWarnings("all")
		public boolean isKeepBaseFormHeadBones() {
			return this.keepBaseFormHeadBones;
		}

		@java.lang.SuppressWarnings("all")
		public String getBodyColor1() {
			return this.bodyColor1;
		}

		@java.lang.SuppressWarnings("all")
		public String getBodyColor2() {
			return this.bodyColor2;
		}

		@java.lang.SuppressWarnings("all")
		public String getBodyColor3() {
			return this.bodyColor3;
		}

		@java.lang.SuppressWarnings("all")
		public String getExtraFormColor() {
			return this.extraFormColor;
		}

		@java.lang.SuppressWarnings("all")
		public String getHairType() {
			return this.hairType;
		}

		@java.lang.SuppressWarnings("all")
		public String getForcedHairCode() {
			return this.forcedHairCode;
		}

		@java.lang.SuppressWarnings("all")
		public String getHairColor() {
			return this.hairColor;
		}

		@java.lang.SuppressWarnings("all")
		public String getEye1Color() {
			return this.eye1Color;
		}

		@java.lang.SuppressWarnings("all")
		public String getEye2Color() {
			return this.eye2Color;
		}

		@java.lang.SuppressWarnings("all")
		public String getAuraType() {
			return this.auraType;
		}

		@java.lang.SuppressWarnings("all")
		public Integer getAuraLayer() {
			return this.auraLayer;
		}

		@java.lang.SuppressWarnings("all")
		public String getAuraColor() {
			return this.auraColor;
		}

		@java.lang.SuppressWarnings("all")
		public Boolean getHasLightnings() {
			return this.hasLightnings;
		}

		@java.lang.SuppressWarnings("all")
		public String getLightningColor() {
			return this.lightningColor;
		}

		@java.lang.SuppressWarnings("all")
		public Float[] getModelScaling() {
			return this.modelScaling;
		}

		@java.lang.SuppressWarnings("all")
		public Double getMaxMastery() {
			return this.maxMastery;
		}

		@java.lang.SuppressWarnings("all")
		public Boolean getFormStackable() {
			return this.formStackable;
		}

		@java.lang.SuppressWarnings("all")
		public FormData() {
		}
	}

	@java.lang.SuppressWarnings("all")
	public void setConfigVersion(final String configVersion) {
		this.configVersion = configVersion;
	}

	@java.lang.SuppressWarnings("all")
	public void setGroupName(final String groupName) {
		this.groupName = groupName;
	}

	@java.lang.SuppressWarnings("all")
	public void setFormType(final String formType) {
		this.formType = formType;
	}

	@java.lang.SuppressWarnings("all")
	public void setForms(final Map<String, FormData> forms) {
		this.forms = forms;
	}

	@java.lang.SuppressWarnings("all")
	public String getConfigVersion() {
		return this.configVersion;
	}

	@java.lang.SuppressWarnings("all")
	public FormConfig() {
	}
}
