// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.config;
public class GeneralUserConfig {
	public static final String CURRENT_VERSION = ConfigManager.CONFIG_VERSION;
	private String configVersion;
	private Boolean firstPersonAnimated = true;
	private boolean impactFramesEnabled = false;
	private Boolean techniqueHotbarRightSide = false;
	private Boolean alwaysVisibleHudValues = false;
	private Boolean hideHudNumbers = false;
	private Integer xenoverseHudPosX = 5;
	private Integer xenoverseHudPosY = 5;
	private Float xenoverseHudScale = 1.0F;
	private Boolean advancedDescription = true;
	private Boolean advancedDescriptionPercentage = true;
	private Boolean alternativeHud = false;
	private Boolean hexagonStatsDisplay = false;
	private Float menuScaleMultiplier = 1.0F;
	private Float utilityMenuScaleMultiplier = 1.0F;
	private Integer healthBarPosX = 10;
	private Integer healthBarPosY = 20;
	private Integer energyBarPosX = 10;
	private Integer energyBarPosY = 10;
	private Integer staminaBarPosX = 10;
	private Integer staminaBarPosY = 10;
	private Boolean cameraMovementDuringFlight = true;
	private Boolean liveCrowdinTranslations = true;
	private Boolean showAccumulativeDamage = true;
	private Boolean taiyokenInvertPalette = false;
	private Boolean transformationOutlines = true;
	private Integer overShoulderMode = 2;
	private Boolean overShoulderLeft = false;
	private Float overShoulderBack = 3.0F;
	private Float overShoulderUp = 0.35F;
	private Float overShoulderSide = 1.45F;
	private Float overShoulderSmoothing = 0.4F;

	public Integer getOverShoulderMode() {
		if (overShoulderMode == null || overShoulderMode < 0 || overShoulderMode > 2) overShoulderMode = 2;
		return overShoulderMode;
	}

	public Boolean getOverShoulderLeft() {
		if (overShoulderLeft == null) overShoulderLeft = false;
		return overShoulderLeft;
	}

	public Float getOverShoulderBack() {
		if (overShoulderBack == null || !Float.isFinite(overShoulderBack)) overShoulderBack = 3.0F;
		return overShoulderBack;
	}

	public Float getOverShoulderUp() {
		if (overShoulderUp == null || !Float.isFinite(overShoulderUp)) overShoulderUp = 0.35F;
		return overShoulderUp;
	}

	public Float getOverShoulderSide() {
		if (overShoulderSide == null || !Float.isFinite(overShoulderSide)) overShoulderSide = 1.45F;
		return overShoulderSide;
	}

	public Float getOverShoulderSmoothing() {
		if (overShoulderSmoothing == null || !Float.isFinite(overShoulderSmoothing) || overShoulderSmoothing <= 0.0F) overShoulderSmoothing = 0.4F;
		return Math.min(overShoulderSmoothing, 1.0F);
	}

	public Boolean getTaiyokenInvertPalette() {
		if (taiyokenInvertPalette == null) taiyokenInvertPalette = false;
		return taiyokenInvertPalette;
	}

	public Boolean getTransformationOutlines() {
		if (transformationOutlines == null) transformationOutlines = true;
		return transformationOutlines;
	}

	public Boolean getShowAccumulativeDamage() {
		if (showAccumulativeDamage == null) showAccumulativeDamage = true;
		return showAccumulativeDamage;
	}

	public Float getMenuScaleMultiplier() {
		if (!Float.isFinite(menuScaleMultiplier) || menuScaleMultiplier <= 0.0F) menuScaleMultiplier = 1.0F;
		return menuScaleMultiplier;
	}

	public Float getUtilityMenuScaleMultiplier() {
		if (utilityMenuScaleMultiplier == null || !Float.isFinite(utilityMenuScaleMultiplier) || utilityMenuScaleMultiplier <= 0.0F) utilityMenuScaleMultiplier = 1.0F;
		return utilityMenuScaleMultiplier;
	}

	public void setUtilityMenuScaleMultiplier(Float utilityMenuScaleMultiplier) {
		if (utilityMenuScaleMultiplier == null || !Float.isFinite(utilityMenuScaleMultiplier) || utilityMenuScaleMultiplier <= 0.0F) {
			this.utilityMenuScaleMultiplier = 1.0F;
			return;
		}
		this.utilityMenuScaleMultiplier = utilityMenuScaleMultiplier;
	}

	public Float getXenoverseHudScale() {
		if (xenoverseHudScale == null || !Float.isFinite(xenoverseHudScale) || xenoverseHudScale <= 0.0F) xenoverseHudScale = 1.0F;
		return xenoverseHudScale;
	}

	public void setXenoverseHudScale(Float xenoverseHudScale) {
		if (xenoverseHudScale == null || !Float.isFinite(xenoverseHudScale) || xenoverseHudScale <= 0.0F) {
			this.xenoverseHudScale = 1.0F;
			return;
		}
		this.xenoverseHudScale = xenoverseHudScale;
	}

	public Boolean getTechniqueHotbarRightSide() {
		if (techniqueHotbarRightSide == null) techniqueHotbarRightSide = false;
		return techniqueHotbarRightSide;
	}

	public Boolean getHideHudNumbers() {
		if (hideHudNumbers == null) hideHudNumbers = false;
		return hideHudNumbers;
	}

	public void setMenuScaleMultiplier(Float menuScaleMultiplier) {
		if (!Float.isFinite(menuScaleMultiplier) || menuScaleMultiplier <= 0.0F) {
			this.menuScaleMultiplier = 1.0F;
			return;
		}
		this.menuScaleMultiplier = menuScaleMultiplier;
	}

	@java.lang.SuppressWarnings("all")
	public String getConfigVersion() {
		return this.configVersion;
	}

	@java.lang.SuppressWarnings("all")
	public Boolean getFirstPersonAnimated() {
		return this.firstPersonAnimated;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isImpactFramesEnabled() {
		return this.impactFramesEnabled;
	}

	@java.lang.SuppressWarnings("all")
	public Boolean getAlwaysVisibleHudValues() {
		return this.alwaysVisibleHudValues;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getXenoverseHudPosX() {
		return this.xenoverseHudPosX;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getXenoverseHudPosY() {
		return this.xenoverseHudPosY;
	}

	@java.lang.SuppressWarnings("all")
	public Boolean getAdvancedDescription() {
		return this.advancedDescription;
	}

	@java.lang.SuppressWarnings("all")
	public Boolean getAdvancedDescriptionPercentage() {
		return this.advancedDescriptionPercentage;
	}

	@java.lang.SuppressWarnings("all")
	public Boolean getAlternativeHud() {
		return this.alternativeHud;
	}

	@java.lang.SuppressWarnings("all")
	public Boolean getHexagonStatsDisplay() {
		return this.hexagonStatsDisplay;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getHealthBarPosX() {
		return this.healthBarPosX;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getHealthBarPosY() {
		return this.healthBarPosY;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getEnergyBarPosX() {
		return this.energyBarPosX;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getEnergyBarPosY() {
		return this.energyBarPosY;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getStaminaBarPosX() {
		return this.staminaBarPosX;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getStaminaBarPosY() {
		return this.staminaBarPosY;
	}

	@java.lang.SuppressWarnings("all")
	public Boolean getCameraMovementDuringFlight() {
		return this.cameraMovementDuringFlight;
	}

	@java.lang.SuppressWarnings("all")
	public Boolean getLiveCrowdinTranslations() {
		return this.liveCrowdinTranslations;
	}

	@java.lang.SuppressWarnings("all")
	public void setFirstPersonAnimated(final Boolean firstPersonAnimated) {
		this.firstPersonAnimated = firstPersonAnimated;
	}

	@java.lang.SuppressWarnings("all")
	public void setImpactFramesEnabled(final boolean impactFramesEnabled) {
		this.impactFramesEnabled = impactFramesEnabled;
	}

	@java.lang.SuppressWarnings("all")
	public void setTechniqueHotbarRightSide(final Boolean techniqueHotbarRightSide) {
		this.techniqueHotbarRightSide = techniqueHotbarRightSide;
	}

	@java.lang.SuppressWarnings("all")
	public void setAlwaysVisibleHudValues(final Boolean alwaysVisibleHudValues) {
		this.alwaysVisibleHudValues = alwaysVisibleHudValues;
	}

	@java.lang.SuppressWarnings("all")
	public void setHideHudNumbers(final Boolean hideHudNumbers) {
		this.hideHudNumbers = hideHudNumbers;
	}

	@java.lang.SuppressWarnings("all")
	public void setXenoverseHudPosX(final Integer xenoverseHudPosX) {
		this.xenoverseHudPosX = xenoverseHudPosX;
	}

	@java.lang.SuppressWarnings("all")
	public void setXenoverseHudPosY(final Integer xenoverseHudPosY) {
		this.xenoverseHudPosY = xenoverseHudPosY;
	}

	@java.lang.SuppressWarnings("all")
	public void setAdvancedDescription(final Boolean advancedDescription) {
		this.advancedDescription = advancedDescription;
	}

	@java.lang.SuppressWarnings("all")
	public void setAdvancedDescriptionPercentage(final Boolean advancedDescriptionPercentage) {
		this.advancedDescriptionPercentage = advancedDescriptionPercentage;
	}

	@java.lang.SuppressWarnings("all")
	public void setAlternativeHud(final Boolean alternativeHud) {
		this.alternativeHud = alternativeHud;
	}

	@java.lang.SuppressWarnings("all")
	public void setHexagonStatsDisplay(final Boolean hexagonStatsDisplay) {
		this.hexagonStatsDisplay = hexagonStatsDisplay;
	}

	@java.lang.SuppressWarnings("all")
	public void setHealthBarPosX(final Integer healthBarPosX) {
		this.healthBarPosX = healthBarPosX;
	}

	@java.lang.SuppressWarnings("all")
	public void setHealthBarPosY(final Integer healthBarPosY) {
		this.healthBarPosY = healthBarPosY;
	}

	@java.lang.SuppressWarnings("all")
	public void setEnergyBarPosX(final Integer energyBarPosX) {
		this.energyBarPosX = energyBarPosX;
	}

	@java.lang.SuppressWarnings("all")
	public void setEnergyBarPosY(final Integer energyBarPosY) {
		this.energyBarPosY = energyBarPosY;
	}

	@java.lang.SuppressWarnings("all")
	public void setStaminaBarPosX(final Integer staminaBarPosX) {
		this.staminaBarPosX = staminaBarPosX;
	}

	@java.lang.SuppressWarnings("all")
	public void setStaminaBarPosY(final Integer staminaBarPosY) {
		this.staminaBarPosY = staminaBarPosY;
	}

	@java.lang.SuppressWarnings("all")
	public void setCameraMovementDuringFlight(final Boolean cameraMovementDuringFlight) {
		this.cameraMovementDuringFlight = cameraMovementDuringFlight;
	}

	@java.lang.SuppressWarnings("all")
	public void setLiveCrowdinTranslations(final Boolean liveCrowdinTranslations) {
		this.liveCrowdinTranslations = liveCrowdinTranslations;
	}

	@java.lang.SuppressWarnings("all")
	public void setShowAccumulativeDamage(final Boolean showAccumulativeDamage) {
		this.showAccumulativeDamage = showAccumulativeDamage;
	}

	@java.lang.SuppressWarnings("all")
	public void setTaiyokenInvertPalette(final Boolean taiyokenInvertPalette) {
		this.taiyokenInvertPalette = taiyokenInvertPalette;
	}

	@java.lang.SuppressWarnings("all")
	public void setTransformationOutlines(final Boolean transformationOutlines) {
		this.transformationOutlines = transformationOutlines;
	}

	@java.lang.SuppressWarnings("all")
	public void setOverShoulderMode(final Integer overShoulderMode) {
		this.overShoulderMode = overShoulderMode;
	}

	@java.lang.SuppressWarnings("all")
	public void setOverShoulderLeft(final Boolean overShoulderLeft) {
		this.overShoulderLeft = overShoulderLeft;
	}

	@java.lang.SuppressWarnings("all")
	public void setOverShoulderBack(final Float overShoulderBack) {
		this.overShoulderBack = overShoulderBack;
	}

	@java.lang.SuppressWarnings("all")
	public void setOverShoulderUp(final Float overShoulderUp) {
		this.overShoulderUp = overShoulderUp;
	}

	@java.lang.SuppressWarnings("all")
	public void setOverShoulderSide(final Float overShoulderSide) {
		this.overShoulderSide = overShoulderSide;
	}

	@java.lang.SuppressWarnings("all")
	public void setOverShoulderSmoothing(final Float overShoulderSmoothing) {
		this.overShoulderSmoothing = overShoulderSmoothing;
	}

	@java.lang.SuppressWarnings("all")
	public void setConfigVersion(final String configVersion) {
		this.configVersion = configVersion;
	}
}
