// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.config;

import com.google.gson.annotations.SerializedName;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

public class RaceStatsConfig {
	public static final String CURRENT_VERSION = ConfigManager.CONFIG_VERSION;
	private String configVersion;
	private final Map<String, ClassStats> classes = new HashMap<>();
	private static final int MAX_TRACKED_CLASSES = 64;

	public ClassStats getClassStats(String characterClass) {
		ClassStats existing = this.classes.get(characterClass);
		if (existing != null) return existing;
		if (characterClass != null && this.classes.size() < MAX_TRACKED_CLASSES) {
			ClassStats created = new ClassStats();
			this.classes.put(characterClass, created);
			return created;
		}
		return new ClassStats();
	}

	public Collection<String> getAllClasses() {
		return this.classes.keySet();
	}


	public static class ClassStats {
		private BaseStats baseStats = new BaseStats();
		private StatScaling statScaling = new StatScaling();
		private Double baseHp5 = 1.25;
		private Double hp5VitScaling = 0.0375;
		private Double baseEp5 = 10.0;
		private Double ep5EneScaling = 0.2;
		private Double baseSp5 = 10.0;
		private Double sp5StmScaling = 0.1;
		private Double tpCostMultiplier = 1.0;
		private Double tpGainMultiplier = 1.0;
		private Passive passive = new Passive();

		@java.lang.SuppressWarnings("all")
		public void setBaseStats(final BaseStats baseStats) {
			this.baseStats = baseStats;
		}

		@java.lang.SuppressWarnings("all")
		public void setStatScaling(final StatScaling statScaling) {
			this.statScaling = statScaling;
		}

		@java.lang.SuppressWarnings("all")
		public void setBaseHp5(final Double baseHp5) {
			this.baseHp5 = baseHp5;
		}

		@java.lang.SuppressWarnings("all")
		public void setHp5VitScaling(final Double hp5VitScaling) {
			this.hp5VitScaling = hp5VitScaling;
		}

		@java.lang.SuppressWarnings("all")
		public void setBaseEp5(final Double baseEp5) {
			this.baseEp5 = baseEp5;
		}

		@java.lang.SuppressWarnings("all")
		public void setEp5EneScaling(final Double ep5EneScaling) {
			this.ep5EneScaling = ep5EneScaling;
		}

		@java.lang.SuppressWarnings("all")
		public void setBaseSp5(final Double baseSp5) {
			this.baseSp5 = baseSp5;
		}

		@java.lang.SuppressWarnings("all")
		public void setSp5StmScaling(final Double sp5StmScaling) {
			this.sp5StmScaling = sp5StmScaling;
		}

		@java.lang.SuppressWarnings("all")
		public void setTpCostMultiplier(final Double tpCostMultiplier) {
			this.tpCostMultiplier = tpCostMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setTpGainMultiplier(final Double tpGainMultiplier) {
			this.tpGainMultiplier = tpGainMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setPassive(final Passive passive) {
			this.passive = passive;
		}

		@java.lang.SuppressWarnings("all")
		public BaseStats getBaseStats() {
			return this.baseStats;
		}

		@java.lang.SuppressWarnings("all")
		public StatScaling getStatScaling() {
			return this.statScaling;
		}

		@java.lang.SuppressWarnings("all")
		public Double getBaseHp5() {
			return this.baseHp5;
		}

		@java.lang.SuppressWarnings("all")
		public Double getHp5VitScaling() {
			return this.hp5VitScaling;
		}

		@java.lang.SuppressWarnings("all")
		public Double getBaseEp5() {
			return this.baseEp5;
		}

		@java.lang.SuppressWarnings("all")
		public Double getEp5EneScaling() {
			return this.ep5EneScaling;
		}

		@java.lang.SuppressWarnings("all")
		public Double getBaseSp5() {
			return this.baseSp5;
		}

		@java.lang.SuppressWarnings("all")
		public Double getSp5StmScaling() {
			return this.sp5StmScaling;
		}

		@java.lang.SuppressWarnings("all")
		public Double getTpCostMultiplier() {
			return this.tpCostMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public Double getTpGainMultiplier() {
			return this.tpGainMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public Passive getPassive() {
			return this.passive;
		}

		@java.lang.SuppressWarnings("all")
		public ClassStats() {
		}
	}


	public static class Passive {
		private boolean enabled = true;
		private Map<String, Double> values = new HashMap<>();

		@java.lang.SuppressWarnings("all")
		public void setEnabled(final boolean enabled) {
			this.enabled = enabled;
		}

		@java.lang.SuppressWarnings("all")
		public void setValues(final Map<String, Double> values) {
			this.values = values;
		}

		@java.lang.SuppressWarnings("all")
		public boolean isEnabled() {
			return this.enabled;
		}

		@java.lang.SuppressWarnings("all")
		public Map<String, Double> getValues() {
			return this.values;
		}

		@java.lang.SuppressWarnings("all")
		public Passive() {
		}
	}


	public static class BaseStats {
		@SerializedName("STR")
		private Integer strength = 5;
		@SerializedName("SKP")
		private Integer strikePower = 5;
		@SerializedName("RES")
		private Integer resistance = 5;
		@SerializedName("VIT")
		private Integer vitality = 5;
		@SerializedName("PWR")
		private Integer kiPower = 5;
		@SerializedName("ENE")
		private Integer energy = 5;

		@java.lang.SuppressWarnings("all")
		public void setStrength(final Integer strength) {
			this.strength = strength;
		}

		@java.lang.SuppressWarnings("all")
		public void setStrikePower(final Integer strikePower) {
			this.strikePower = strikePower;
		}

		@java.lang.SuppressWarnings("all")
		public void setResistance(final Integer resistance) {
			this.resistance = resistance;
		}

		@java.lang.SuppressWarnings("all")
		public void setVitality(final Integer vitality) {
			this.vitality = vitality;
		}

		@java.lang.SuppressWarnings("all")
		public void setKiPower(final Integer kiPower) {
			this.kiPower = kiPower;
		}

		@java.lang.SuppressWarnings("all")
		public void setEnergy(final Integer energy) {
			this.energy = energy;
		}

		@java.lang.SuppressWarnings("all")
		public Integer getStrength() {
			return this.strength;
		}

		@java.lang.SuppressWarnings("all")
		public Integer getStrikePower() {
			return this.strikePower;
		}

		@java.lang.SuppressWarnings("all")
		public Integer getResistance() {
			return this.resistance;
		}

		@java.lang.SuppressWarnings("all")
		public Integer getVitality() {
			return this.vitality;
		}

		@java.lang.SuppressWarnings("all")
		public Integer getKiPower() {
			return this.kiPower;
		}

		@java.lang.SuppressWarnings("all")
		public Integer getEnergy() {
			return this.energy;
		}

		@java.lang.SuppressWarnings("all")
		public BaseStats() {
		}
	}


	public static class StatScaling {
		@SerializedName("STR_scaling")
		private Double strengthScaling = 1.0;
		@SerializedName("SKP_scaling")
		private Double strikePowerScaling = 1.0;
		@SerializedName("STM_scaling")
		private Double staminaScaling = 1.0;
		@SerializedName("DEF_scaling")
		private Double defenseScaling = 1.0;
		@SerializedName("VIT_scaling")
		private Double vitalityScaling = 1.0;
		@SerializedName("PWR_scaling")
		private Double kiPowerScaling = 1.0;
		@SerializedName("ENE_scaling")
		private Double energyScaling = 1.0;

		@java.lang.SuppressWarnings("all")
		public void setStrengthScaling(final Double strengthScaling) {
			this.strengthScaling = strengthScaling;
		}

		@java.lang.SuppressWarnings("all")
		public void setStrikePowerScaling(final Double strikePowerScaling) {
			this.strikePowerScaling = strikePowerScaling;
		}

		@java.lang.SuppressWarnings("all")
		public void setStaminaScaling(final Double staminaScaling) {
			this.staminaScaling = staminaScaling;
		}

		@java.lang.SuppressWarnings("all")
		public void setDefenseScaling(final Double defenseScaling) {
			this.defenseScaling = defenseScaling;
		}

		@java.lang.SuppressWarnings("all")
		public void setVitalityScaling(final Double vitalityScaling) {
			this.vitalityScaling = vitalityScaling;
		}

		@java.lang.SuppressWarnings("all")
		public void setKiPowerScaling(final Double kiPowerScaling) {
			this.kiPowerScaling = kiPowerScaling;
		}

		@java.lang.SuppressWarnings("all")
		public void setEnergyScaling(final Double energyScaling) {
			this.energyScaling = energyScaling;
		}

		@java.lang.SuppressWarnings("all")
		public Double getStrengthScaling() {
			return this.strengthScaling;
		}

		@java.lang.SuppressWarnings("all")
		public Double getStrikePowerScaling() {
			return this.strikePowerScaling;
		}

		@java.lang.SuppressWarnings("all")
		public Double getStaminaScaling() {
			return this.staminaScaling;
		}

		@java.lang.SuppressWarnings("all")
		public Double getDefenseScaling() {
			return this.defenseScaling;
		}

		@java.lang.SuppressWarnings("all")
		public Double getVitalityScaling() {
			return this.vitalityScaling;
		}

		@java.lang.SuppressWarnings("all")
		public Double getKiPowerScaling() {
			return this.kiPowerScaling;
		}

		@java.lang.SuppressWarnings("all")
		public Double getEnergyScaling() {
			return this.energyScaling;
		}

		@java.lang.SuppressWarnings("all")
		public StatScaling() {
		}
	}

	@java.lang.SuppressWarnings("all")
	public String getConfigVersion() {
		return this.configVersion;
	}

	@java.lang.SuppressWarnings("all")
	public Map<String, ClassStats> getClasses() {
		return this.classes;
	}

	@java.lang.SuppressWarnings("all")
	public RaceStatsConfig() {
	}

	@java.lang.SuppressWarnings("all")
	public void setConfigVersion(final String configVersion) {
		this.configVersion = configVersion;
	}
}
