// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.config;

import com.dragonminez.common.stats.techniques.KiAttackData;
import com.dragonminez.common.stats.techniques.PredefinedTechniques;
import com.google.gson.annotations.SerializedName;
import java.util.HashMap;
import java.util.Map;

public class TechniqueConfig {
	public static final String CURRENT_VERSION = ConfigManager.CONFIG_VERSION;
	private String configVersion;
	@SerializedName("KiAttacks")
	private final Map<String, TechniqueTypeConfig> kiAttacks = new HashMap<>();
	@SerializedName("StrikeAttacks")
	private final Map<String, StrikeAttackConfig> strikeAttacks = new HashMap<>();

	public TechniqueConfig() {
		createDefaults();
	}

	private void createDefaults() {
		for (KiAttackData.KiType type : KiAttackData.KiType.values()) {
			TechniqueTypeConfig cfg = TechniqueTypeConfig.defaults();
			cfg.setCastTimeTicks(defaultCastTimeTicks(type));
			kiAttacks.put(type.name().toLowerCase(), cfg);
		}
		for (String strikeId : PredefinedTechniques.STRIKE_IDS) {
			StrikeAttackConfig cfg = StrikeAttackConfig.defaults();
			cfg.setCooldownTicks(defaultStrikeCooldownTicks(strikeId));
			strikeAttacks.put(strikeId, cfg);
		}
	}

	private static int defaultStrikeCooldownTicks(String strikeId) {
		return switch (strikeId) {
			case "dragon_fist" -> 320;
			case "oozaru_fist" -> 280;
			case "super_god_fist", "kaioken_attack" -> 240;
			case "deadly_dance_vegetto" -> 200;
			case "wolf_fang" -> 140;
			default -> 160;
		};
	}

	private static int defaultCastTimeTicks(KiAttackData.KiType type) {
		return switch (type) {
			case SMALL_BALL, LASER -> 0;
			case MEDIUM_BALL, DISK -> 30;
			case BARRAGE, SHIELD, AREA -> 40;
			case WAVE, BEAM -> 50;
			case GIANT_BALL, EXPLOSION -> 60;
		};
	}

	public TechniqueTypeConfig getKiTypeConfig(KiAttackData.KiType type) {
		if (type == null) return TechniqueTypeConfig.defaults();
		TechniqueTypeConfig config = kiAttacks.get(type.name().toLowerCase());
		return config != null ? config : TechniqueTypeConfig.defaults();
	}

	public StrikeAttackConfig getStrikeConfig(String strikeId) {
		if (strikeId == null || strikeId.isEmpty()) return StrikeAttackConfig.defaults();
		StrikeAttackConfig config = strikeAttacks.get(strikeId.toLowerCase());
		return config != null ? config : StrikeAttackConfig.defaults();
	}


	public static class TechniqueTypeConfig {
		private int minXPCost = 100;
		private int maxXPCost = -1;
		private double xpCostMultiplier = 1.0;
		private double xpGainMultiplier = 1.0;
		private int xpGainPerHit = 1;
		private int xpGainPerKill = 3;
		private double kiCostMultiplier = 1.0;
		private double damageMultiplier = 1.0;
		private double destructionMultiplier = 1.0;
		private int castTimeTicks = 30;

		public static TechniqueTypeConfig defaults() {
			return new TechniqueTypeConfig();
		}

		@java.lang.SuppressWarnings("all")
		public int getMinXPCost() {
			return this.minXPCost;
		}

		@java.lang.SuppressWarnings("all")
		public int getMaxXPCost() {
			return this.maxXPCost;
		}

		@java.lang.SuppressWarnings("all")
		public double getXpCostMultiplier() {
			return this.xpCostMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public double getXpGainMultiplier() {
			return this.xpGainMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public int getXpGainPerHit() {
			return this.xpGainPerHit;
		}

		@java.lang.SuppressWarnings("all")
		public int getXpGainPerKill() {
			return this.xpGainPerKill;
		}

		@java.lang.SuppressWarnings("all")
		public double getKiCostMultiplier() {
			return this.kiCostMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public double getDamageMultiplier() {
			return this.damageMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public double getDestructionMultiplier() {
			return this.destructionMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public int getCastTimeTicks() {
			return this.castTimeTicks;
		}

		@java.lang.SuppressWarnings("all")
		public void setMinXPCost(final int minXPCost) {
			this.minXPCost = minXPCost;
		}

		@java.lang.SuppressWarnings("all")
		public void setMaxXPCost(final int maxXPCost) {
			this.maxXPCost = maxXPCost;
		}

		@java.lang.SuppressWarnings("all")
		public void setXpCostMultiplier(final double xpCostMultiplier) {
			this.xpCostMultiplier = xpCostMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setXpGainMultiplier(final double xpGainMultiplier) {
			this.xpGainMultiplier = xpGainMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setXpGainPerHit(final int xpGainPerHit) {
			this.xpGainPerHit = xpGainPerHit;
		}

		@java.lang.SuppressWarnings("all")
		public void setXpGainPerKill(final int xpGainPerKill) {
			this.xpGainPerKill = xpGainPerKill;
		}

		@java.lang.SuppressWarnings("all")
		public void setKiCostMultiplier(final double kiCostMultiplier) {
			this.kiCostMultiplier = kiCostMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setDamageMultiplier(final double damageMultiplier) {
			this.damageMultiplier = damageMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setDestructionMultiplier(final double destructionMultiplier) {
			this.destructionMultiplier = destructionMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setCastTimeTicks(final int castTimeTicks) {
			this.castTimeTicks = castTimeTicks;
		}
	}


	public static class StrikeAttackConfig {
		private int minXPCost = 100;
		private int maxXPCost = -1;
		private double xpCostMultiplier = 1.0;
		private double xpGainMultiplier = 1.0;
		private int xpGainPerHit = 1;
		private int xpGainPerKill = 3;
		private double kiCostMultiplier = 1.0;
		private double damageMultiplier = 1.0;
		private int castTimeTicks = 0;
		private int cooldownTicks = 80;

		public static StrikeAttackConfig defaults() {
			return new StrikeAttackConfig();
		}

		@java.lang.SuppressWarnings("all")
		public int getMinXPCost() {
			return this.minXPCost;
		}

		@java.lang.SuppressWarnings("all")
		public int getMaxXPCost() {
			return this.maxXPCost;
		}

		@java.lang.SuppressWarnings("all")
		public double getXpCostMultiplier() {
			return this.xpCostMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public double getXpGainMultiplier() {
			return this.xpGainMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public int getXpGainPerHit() {
			return this.xpGainPerHit;
		}

		@java.lang.SuppressWarnings("all")
		public int getXpGainPerKill() {
			return this.xpGainPerKill;
		}

		@java.lang.SuppressWarnings("all")
		public double getKiCostMultiplier() {
			return this.kiCostMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public double getDamageMultiplier() {
			return this.damageMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public int getCastTimeTicks() {
			return this.castTimeTicks;
		}

		@java.lang.SuppressWarnings("all")
		public int getCooldownTicks() {
			return this.cooldownTicks;
		}

		@java.lang.SuppressWarnings("all")
		public void setMinXPCost(final int minXPCost) {
			this.minXPCost = minXPCost;
		}

		@java.lang.SuppressWarnings("all")
		public void setMaxXPCost(final int maxXPCost) {
			this.maxXPCost = maxXPCost;
		}

		@java.lang.SuppressWarnings("all")
		public void setXpCostMultiplier(final double xpCostMultiplier) {
			this.xpCostMultiplier = xpCostMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setXpGainMultiplier(final double xpGainMultiplier) {
			this.xpGainMultiplier = xpGainMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setXpGainPerHit(final int xpGainPerHit) {
			this.xpGainPerHit = xpGainPerHit;
		}

		@java.lang.SuppressWarnings("all")
		public void setXpGainPerKill(final int xpGainPerKill) {
			this.xpGainPerKill = xpGainPerKill;
		}

		@java.lang.SuppressWarnings("all")
		public void setKiCostMultiplier(final double kiCostMultiplier) {
			this.kiCostMultiplier = kiCostMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setDamageMultiplier(final double damageMultiplier) {
			this.damageMultiplier = damageMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public void setCastTimeTicks(final int castTimeTicks) {
			this.castTimeTicks = castTimeTicks;
		}

		@java.lang.SuppressWarnings("all")
		public void setCooldownTicks(final int cooldownTicks) {
			this.cooldownTicks = cooldownTicks;
		}
	}

	@java.lang.SuppressWarnings("all")
	public String getConfigVersion() {
		return this.configVersion;
	}

	@java.lang.SuppressWarnings("all")
	public Map<String, TechniqueTypeConfig> getKiAttacks() {
		return this.kiAttacks;
	}

	@java.lang.SuppressWarnings("all")
	public Map<String, StrikeAttackConfig> getStrikeAttacks() {
		return this.strikeAttacks;
	}

	@java.lang.SuppressWarnings("all")
	public void setConfigVersion(final String configVersion) {
		this.configVersion = configVersion;
	}
}
