// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.config;

public class TrainingConfig {
	public static final String CURRENT_VERSION = ConfigManager.CONFIG_VERSION;
	private String configVersion;
	private double rewardBaseCoefficient = 3.4;
	private double rewardCostExponent = 0.6;
	private RhythmConfig rhythm = new RhythmConfig();
	private ControlConfig control = new ControlConfig();
	private MemoryConfig memory = new MemoryConfig();
	private PrecisionConfig precision = new PrecisionConfig();
	private GravityConfig gravity = new GravityConfig();

	public float computeTpsPerLevel(int singleStatCost, MinigameSettings settings) {
		double tpc = Math.max(1.0, singleStatCost);
		double perLevel = rewardBaseCoefficient * Math.pow(tpc, rewardCostExponent);
		double multiplier = settings != null ? settings.getRewardMultiplier() : 1.0;
		return (float) Math.max(1.0, perLevel * multiplier);
	}

	public MinigameSettings getSettings(String minigameId) {
		if (minigameId == null) return rhythm;
		return switch (minigameId.toLowerCase()) {
			case "control" -> control;
			case "memory" -> memory;
			case "precision" -> precision;
			case "gravity" -> gravity;
			default -> rhythm;
		};
	}


	public static class MinigameSettings {
		protected double rewardMultiplier = 1.0;
		protected float tpsLimitPerGame = 50000.0F;
		protected boolean unlockedByDefault = false;
		protected String masterName = "a master";

		@java.lang.SuppressWarnings("all")
		public double getRewardMultiplier() {
			return this.rewardMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public float getTpsLimitPerGame() {
			return this.tpsLimitPerGame;
		}

		@java.lang.SuppressWarnings("all")
		public boolean isUnlockedByDefault() {
			return this.unlockedByDefault;
		}

		@java.lang.SuppressWarnings("all")
		public String getMasterName() {
			return this.masterName;
		}

		@java.lang.SuppressWarnings("all")
		public MinigameSettings() {
		}
	}


	public static class RhythmConfig extends MinigameSettings {
		{
			masterName = "popo";
		}

		private double baseNoteSpeed = 4.0;
		private double noteSpeedPerLevel = 0.5;
		private int noteTravelDistance = 150;
		private float arrowScale = 2.0F;
		private int baseSpawnIntervalTicks = 20;
		private int minSpawnIntervalTicks = 8;
		private int spawnIntervalDecreasePerLevel = 2;
		private int perfectWindow = 14;
		private int goodWindow = 30;
		private double progressMax = 100.0;
		private double progressOnLevelUp = 30.0;
		private double progressGainPerfect = 18.0;
		private double progressGainGood = 12.0;
		private double progressGainHold = 22.0;
		private double progressDecayPerTick = 0.28;
		private double progressLossOnMiss = 10.0;
		private int loseMissThreshold = 5;
		private int loseMissWindow = 10;
		private double holdNoteChance = 0.18;
		private int holdDurationTicks = 24;
		private double doubleNoteChance = 0.12;
		private int doubleNoteGap = 26;

		@java.lang.SuppressWarnings("all")
		public double getBaseNoteSpeed() {
			return this.baseNoteSpeed;
		}

		@java.lang.SuppressWarnings("all")
		public double getNoteSpeedPerLevel() {
			return this.noteSpeedPerLevel;
		}

		@java.lang.SuppressWarnings("all")
		public int getNoteTravelDistance() {
			return this.noteTravelDistance;
		}

		@java.lang.SuppressWarnings("all")
		public float getArrowScale() {
			return this.arrowScale;
		}

		@java.lang.SuppressWarnings("all")
		public int getBaseSpawnIntervalTicks() {
			return this.baseSpawnIntervalTicks;
		}

		@java.lang.SuppressWarnings("all")
		public int getMinSpawnIntervalTicks() {
			return this.minSpawnIntervalTicks;
		}

		@java.lang.SuppressWarnings("all")
		public int getSpawnIntervalDecreasePerLevel() {
			return this.spawnIntervalDecreasePerLevel;
		}

		@java.lang.SuppressWarnings("all")
		public int getPerfectWindow() {
			return this.perfectWindow;
		}

		@java.lang.SuppressWarnings("all")
		public int getGoodWindow() {
			return this.goodWindow;
		}

		@java.lang.SuppressWarnings("all")
		public double getProgressMax() {
			return this.progressMax;
		}

		@java.lang.SuppressWarnings("all")
		public double getProgressOnLevelUp() {
			return this.progressOnLevelUp;
		}

		@java.lang.SuppressWarnings("all")
		public double getProgressGainPerfect() {
			return this.progressGainPerfect;
		}

		@java.lang.SuppressWarnings("all")
		public double getProgressGainGood() {
			return this.progressGainGood;
		}

		@java.lang.SuppressWarnings("all")
		public double getProgressGainHold() {
			return this.progressGainHold;
		}

		@java.lang.SuppressWarnings("all")
		public double getProgressDecayPerTick() {
			return this.progressDecayPerTick;
		}

		@java.lang.SuppressWarnings("all")
		public double getProgressLossOnMiss() {
			return this.progressLossOnMiss;
		}

		@java.lang.SuppressWarnings("all")
		public int getLoseMissThreshold() {
			return this.loseMissThreshold;
		}

		@java.lang.SuppressWarnings("all")
		public int getLoseMissWindow() {
			return this.loseMissWindow;
		}

		@java.lang.SuppressWarnings("all")
		public double getHoldNoteChance() {
			return this.holdNoteChance;
		}

		@java.lang.SuppressWarnings("all")
		public int getHoldDurationTicks() {
			return this.holdDurationTicks;
		}

		@java.lang.SuppressWarnings("all")
		public double getDoubleNoteChance() {
			return this.doubleNoteChance;
		}

		@java.lang.SuppressWarnings("all")
		public int getDoubleNoteGap() {
			return this.doubleNoteGap;
		}

		@java.lang.SuppressWarnings("all")
		public RhythmConfig() {
		}
	}


	public static class ControlConfig extends MinigameSettings {
		{
			masterName = "krillin";
		}

		private int holdDurationTicks = 100;
		private int levelTimeLimitTicks = 300;
		private int barWidth = 200;
		private int baseZoneWidth = 60;
		private int zoneWidthDecreasePerLevel = 6;
		private int minZoneWidth = 24;
		private double baseZoneSpeed = 1.2;
		private double zoneSpeedPerLevel = 0.15;
		private double markerSpeed = 2.75;
		private double baseProgressLossPerTick = 0.12;
		private double progressLossPerLevel = 0.12;

		@java.lang.SuppressWarnings("all")
		public int getHoldDurationTicks() {
			return this.holdDurationTicks;
		}

		@java.lang.SuppressWarnings("all")
		public int getLevelTimeLimitTicks() {
			return this.levelTimeLimitTicks;
		}

		@java.lang.SuppressWarnings("all")
		public int getBarWidth() {
			return this.barWidth;
		}

		@java.lang.SuppressWarnings("all")
		public int getBaseZoneWidth() {
			return this.baseZoneWidth;
		}

		@java.lang.SuppressWarnings("all")
		public int getZoneWidthDecreasePerLevel() {
			return this.zoneWidthDecreasePerLevel;
		}

		@java.lang.SuppressWarnings("all")
		public int getMinZoneWidth() {
			return this.minZoneWidth;
		}

		@java.lang.SuppressWarnings("all")
		public double getBaseZoneSpeed() {
			return this.baseZoneSpeed;
		}

		@java.lang.SuppressWarnings("all")
		public double getZoneSpeedPerLevel() {
			return this.zoneSpeedPerLevel;
		}

		@java.lang.SuppressWarnings("all")
		public double getMarkerSpeed() {
			return this.markerSpeed;
		}

		@java.lang.SuppressWarnings("all")
		public double getBaseProgressLossPerTick() {
			return this.baseProgressLossPerTick;
		}

		@java.lang.SuppressWarnings("all")
		public double getProgressLossPerLevel() {
			return this.progressLossPerLevel;
		}

		@java.lang.SuppressWarnings("all")
		public ControlConfig() {
		}
	}


	public static class MemoryConfig extends MinigameSettings {
		{
			masterName = "gohan";
		}

		private int baseSequenceLength = 3;
		private int sequenceLengthPerLevel = 1;
		private int baseShowTicks = 42;
		private int showTicksDecreasePerLevel = 4;
		private int minShowTicks = 16;

		@java.lang.SuppressWarnings("all")
		public int getBaseSequenceLength() {
			return this.baseSequenceLength;
		}

		@java.lang.SuppressWarnings("all")
		public int getSequenceLengthPerLevel() {
			return this.sequenceLengthPerLevel;
		}

		@java.lang.SuppressWarnings("all")
		public int getBaseShowTicks() {
			return this.baseShowTicks;
		}

		@java.lang.SuppressWarnings("all")
		public int getShowTicksDecreasePerLevel() {
			return this.showTicksDecreasePerLevel;
		}

		@java.lang.SuppressWarnings("all")
		public int getMinShowTicks() {
			return this.minShowTicks;
		}

		@java.lang.SuppressWarnings("all")
		public MemoryConfig() {
		}
	}


	public static class PrecisionConfig extends MinigameSettings {
		{
			masterName = "trunks";
		}

		private int outerRingRadius = 40;
		private int targetRadius = 14;
		private double baseRingSpeed = 0.7;
		private double ringSpeedPerLevel = 0.18;
		private int spawnIntervalTicks = 12;
		private int maxCircles = 3;
		private int perfectWindow = 4;
		private int goodWindow = 11;
		private int perfectPoints = 2;
		private int goodPoints = 1;
		private int missPenalty = 2;
		private int fadeOutTicks = 20;
		private int startingScore = 6;
		private double burstChance = 0.5;
		private int levelUpScoreBase = 10;
		private int levelUpScorePerLevel = 8;
		private int loseMissThreshold = 5;
		private int loseMissWindow = 10;

		@java.lang.SuppressWarnings("all")
		public int getOuterRingRadius() {
			return this.outerRingRadius;
		}

		@java.lang.SuppressWarnings("all")
		public int getTargetRadius() {
			return this.targetRadius;
		}

		@java.lang.SuppressWarnings("all")
		public double getBaseRingSpeed() {
			return this.baseRingSpeed;
		}

		@java.lang.SuppressWarnings("all")
		public double getRingSpeedPerLevel() {
			return this.ringSpeedPerLevel;
		}

		@java.lang.SuppressWarnings("all")
		public int getSpawnIntervalTicks() {
			return this.spawnIntervalTicks;
		}

		@java.lang.SuppressWarnings("all")
		public int getMaxCircles() {
			return this.maxCircles;
		}

		@java.lang.SuppressWarnings("all")
		public int getPerfectWindow() {
			return this.perfectWindow;
		}

		@java.lang.SuppressWarnings("all")
		public int getGoodWindow() {
			return this.goodWindow;
		}

		@java.lang.SuppressWarnings("all")
		public int getPerfectPoints() {
			return this.perfectPoints;
		}

		@java.lang.SuppressWarnings("all")
		public int getGoodPoints() {
			return this.goodPoints;
		}

		@java.lang.SuppressWarnings("all")
		public int getMissPenalty() {
			return this.missPenalty;
		}

		@java.lang.SuppressWarnings("all")
		public int getFadeOutTicks() {
			return this.fadeOutTicks;
		}

		@java.lang.SuppressWarnings("all")
		public int getStartingScore() {
			return this.startingScore;
		}

		@java.lang.SuppressWarnings("all")
		public double getBurstChance() {
			return this.burstChance;
		}

		@java.lang.SuppressWarnings("all")
		public int getLevelUpScoreBase() {
			return this.levelUpScoreBase;
		}

		@java.lang.SuppressWarnings("all")
		public int getLevelUpScorePerLevel() {
			return this.levelUpScorePerLevel;
		}

		@java.lang.SuppressWarnings("all")
		public int getLoseMissThreshold() {
			return this.loseMissThreshold;
		}

		@java.lang.SuppressWarnings("all")
		public int getLoseMissWindow() {
			return this.loseMissWindow;
		}

		@java.lang.SuppressWarnings("all")
		public PrecisionConfig() {
		}
	}


	public static class GravityConfig extends MinigameSettings {
		{
			masterName = "vegeta";
		}

		private int holdDurationTicks = 200;
		private int barHeight = 180;
		private double controlLineFraction = 0.45;
		private double baseGravity = 1.1;
		private double gravityPerLevel = 0.13;
		private double risePerTap = 9.0;
		private double progressLossPerTick = 2.5;
		private double wrongPressDescentMultiplier = 3.0;

		@java.lang.SuppressWarnings("all")
		public int getHoldDurationTicks() {
			return this.holdDurationTicks;
		}

		@java.lang.SuppressWarnings("all")
		public int getBarHeight() {
			return this.barHeight;
		}

		@java.lang.SuppressWarnings("all")
		public double getControlLineFraction() {
			return this.controlLineFraction;
		}

		@java.lang.SuppressWarnings("all")
		public double getBaseGravity() {
			return this.baseGravity;
		}

		@java.lang.SuppressWarnings("all")
		public double getGravityPerLevel() {
			return this.gravityPerLevel;
		}

		@java.lang.SuppressWarnings("all")
		public double getRisePerTap() {
			return this.risePerTap;
		}

		@java.lang.SuppressWarnings("all")
		public double getProgressLossPerTick() {
			return this.progressLossPerTick;
		}

		@java.lang.SuppressWarnings("all")
		public double getWrongPressDescentMultiplier() {
			return this.wrongPressDescentMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public GravityConfig() {
		}
	}

	@java.lang.SuppressWarnings("all")
	public String getConfigVersion() {
		return this.configVersion;
	}

	@java.lang.SuppressWarnings("all")
	public double getRewardBaseCoefficient() {
		return this.rewardBaseCoefficient;
	}

	@java.lang.SuppressWarnings("all")
	public double getRewardCostExponent() {
		return this.rewardCostExponent;
	}

	@java.lang.SuppressWarnings("all")
	public RhythmConfig getRhythm() {
		return this.rhythm;
	}

	@java.lang.SuppressWarnings("all")
	public ControlConfig getControl() {
		return this.control;
	}

	@java.lang.SuppressWarnings("all")
	public MemoryConfig getMemory() {
		return this.memory;
	}

	@java.lang.SuppressWarnings("all")
	public PrecisionConfig getPrecision() {
		return this.precision;
	}

	@java.lang.SuppressWarnings("all")
	public GravityConfig getGravity() {
		return this.gravity;
	}

	@java.lang.SuppressWarnings("all")
	public TrainingConfig() {
	}

	@java.lang.SuppressWarnings("all")
	public void setConfigVersion(final String configVersion) {
		this.configVersion = configVersion;
	}
}
