// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.client.gui.utilitymenu;

import net.minecraft.network.chat.Component;

public class ButtonInfo {
	protected Component line1 = Component.empty();
	protected Component line2 = Component.empty();
	protected int color = 16777215;
	protected boolean isSelected = false;

	public ButtonInfo() {
		// Default empty constructor
	}

	public ButtonInfo(Component line1, Component line2) {
		this.line1 = line1;
		this.line2 = line2;
	}

	public ButtonInfo(Component line1, Component line2, boolean isSelected) {
		this.line1 = line1;
		this.line2 = line2;
		this.isSelected = isSelected;
	}

	public boolean hasContent() {
		return !line1.getString().isEmpty() || !line2.getString().isEmpty();
	}

	@java.lang.SuppressWarnings("all")
	public Component getLine1() {
		return this.line1;
	}

	@java.lang.SuppressWarnings("all")
	public Component getLine2() {
		return this.line2;
	}

	@java.lang.SuppressWarnings("all")
	public int getColor() {
		return this.color;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isSelected() {
		return this.isSelected;
	}

	@java.lang.SuppressWarnings("all")
	public void setColor(final int color) {
		this.color = color;
	}
}
