// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.init.armor;

import com.dragonminez.Reference;
import com.dragonminez.client.util.ArmorTextureResolver;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.core.Holder;
import net.minecraft.world.item.ArmorItem;
import net.minecraft.world.item.ArmorMaterial;
import net.minecraft.world.item.ItemStack;
import org.jetbrains.annotations.Nullable;
import software.bernie.geckolib.animatable.GeoItem;
import software.bernie.geckolib.animatable.instance.AnimatableInstanceCache;
import software.bernie.geckolib.animation.AnimatableManager;
import software.bernie.geckolib.animation.AnimationController;
import software.bernie.geckolib.animation.RawAnimation;
import software.bernie.geckolib.util.GeckoLibUtil;

public class DbzArmorCapeItem extends ArmorItem implements GeoItem, DbzArmorTextured {
    private final AnimatableInstanceCache cache = GeckoLibUtil.createInstanceCache(this);
    private final String modId;
    private final String itemId;

    public DbzArmorCapeItem(Holder<ArmorMaterial> pMaterial, Type pType, Properties pProperties, String itemId) {
        this(pMaterial, pType, pProperties, Reference.MOD_ID, itemId);
    }

    public DbzArmorCapeItem(Holder<ArmorMaterial> pMaterial, Type pType, Properties pProperties, String modId, String itemId) {
        super(pMaterial, pType, pProperties);
        this.modId = modId;
        this.itemId = itemId;
    }

    @Nullable
    @Override
    public ResourceLocation getArmorTexture(ItemStack stack, Entity entity, EquipmentSlot slot, ArmorMaterial.Layer layer, boolean innerModel) {
        return ArmorTextureResolver.resolve(modId, itemId, slot, stack);
    }

    @Override
    public void registerControllers(AnimatableManager.ControllerRegistrar controllers) {
        controllers.add(new AnimationController<>(this, "controller", 5, event -> {
            if (event.isMoving()) {
                return event.setAndContinue(RawAnimation.begin().thenLoop("walk"));
            } else {
                return event.setAndContinue(RawAnimation.begin().thenLoop("idle"));
            }
        }));
    }

    @Override
    public AnimatableInstanceCache getAnimatableInstanceCache() {
        return cache;
    }

    @java.lang.SuppressWarnings("all")
    public String getModId() {
        return this.modId;
    }

    @java.lang.SuppressWarnings("all")
    public String getItemId() {
        return this.itemId;
    }
}
