// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.init.armor;

import com.dragonminez.Reference;
import com.dragonminez.client.util.ArmorTextureResolver;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.core.Holder;
import net.minecraft.world.item.ArmorItem;
import net.minecraft.world.item.ArmorMaterial;
import net.minecraft.world.item.ItemStack;
import org.jetbrains.annotations.Nullable;

/**
 * Custom DBZ armor piece. Texture paths are resolved per-item via
 * {@link #getArmorTexture} so armor stands (Goku's house displays, etc.) and
 * vanilla {@code HumanoidArmorLayer} pick up the correct layer PNGs.
 * Client model registration is handled by {@code DMZClientItemExtensions}.
 */
public class DbzArmorItem extends ArmorItem implements DbzArmorTextured {
    private final String modId;
    private final String itemId;

    public DbzArmorItem(Holder<ArmorMaterial> pMaterial, Type pType, Properties pProperties, String itemId) {
        this(pMaterial, pType, pProperties, Reference.MOD_ID, itemId);
    }

    public DbzArmorItem(Holder<ArmorMaterial> pMaterial, Type pType, Properties pProperties, String modId, String itemId) {
        super(pMaterial, pType, pProperties);
        this.modId = modId;
        this.itemId = itemId;
    }

    /**
     * NeoForge 1.21 armor texture hook used by ClientHooks / HumanoidArmorLayer
     * (armor stands, non-player entities, item frames, etc.).
     */
    @Nullable
    @Override
    public ResourceLocation getArmorTexture(ItemStack stack, Entity entity, EquipmentSlot slot, ArmorMaterial.Layer layer, boolean innerModel) {
        return ArmorTextureResolver.resolve(modId, itemId, slot, stack);
    }

    @java.lang.SuppressWarnings("all")
    public String getModId() {
        return this.modId;
    }

    @java.lang.SuppressWarnings("all")
    public String getItemId() {
        return this.itemId;
    }
}
