// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.stats.character;

import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.FriendlyByteBuf;

public class Effect {
    private final String name;
    private double power;
    private int duration;

    public Effect(String name, double power, int duration) {
        this.name = name;
        this.power = power;
        this.duration = duration;
    }

    public boolean isPermanent() {
        return duration == -1;
    }

    public void tick() {
        if (duration > 0) {
            duration--;
        }
    }

    public boolean isExpired() {
        return duration == 0;
    }

    public CompoundTag save() {
        CompoundTag nbt = new CompoundTag();
        nbt.putString("Name", name);
        nbt.putDouble("Power", power);
        nbt.putInt("Duration", duration);
        return nbt;
    }

    public static Effect load(CompoundTag nbt) {
        String name = nbt.getString("Name");
        double power = nbt.getDouble("Power");
        int duration = nbt.getInt("Duration");
        return new Effect(name, power, duration);
    }

    public void toBytes(FriendlyByteBuf buf) {
        buf.writeUtf(name);
        buf.writeDouble(power);
        buf.writeInt(duration);
    }

    public static Effect fromBytes(FriendlyByteBuf buf) {
        String name = buf.readUtf();
        double power = buf.readDouble();
        int duration = buf.readInt();
        return new Effect(name, power, duration);
    }

    public Effect copy() {
        return new Effect(this.name, this.power, this.duration);
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public double getPower() {
        return this.power;
    }

    @java.lang.SuppressWarnings("all")
    public int getDuration() {
        return this.duration;
    }

    @java.lang.SuppressWarnings("all")
    public void setPower(final double power) {
        this.power = power;
    }

    @java.lang.SuppressWarnings("all")
    public void setDuration(final int duration) {
        this.duration = duration;
    }
}
