// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.stats.character;

import com.dragonminez.common.config.ConfigManager;
import com.dragonminez.common.stats.extras.ActionMode;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.nbt.StringTag;
import net.minecraft.nbt.Tag;
import net.minecraft.resources.ResourceLocation;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.UUID;

public class Status {
	public static final int FLIGHT_SEARCH = 0;
	public static final int FLIGHT_COMBAT = 1;
	private boolean isAlive;
	private boolean forceHalo;
	private boolean isHasCreatedCharacter;
	private boolean isAuraActive;
	private boolean isActionCharging;
	private boolean isTailVisible;
	private boolean isDescending;
	private boolean isInKaioPlanet;
	private boolean isChargingKi;
	private boolean isBlocking;
	private long lastBlockTime;
	private long lastHurtTime;
	private boolean friendlyFistEnabled;
	private boolean stunEffect;
	private boolean isKnockedDown;
	private ActionMode selectedAction;
	private String kiWeaponType;
	private int drainingTargetId;
	private boolean isFused;
	private boolean isFusionLeader;
	private UUID fusionPartnerUUID;
	private int fusionTimer;
	private String fusionType;
	private String fusionName;
	private boolean fusionPartyManaged;
	private UUID fusionPrevPartyId;
	private boolean fusionPrevPartyLeader;
	private int potaraPoseTimer;
	private UUID potaraPartnerUUID;
	private boolean potaraLeader;
	private CompoundTag originalAppearance;
	private boolean androidUpgraded;
	private boolean renderKatana;
	private String backWeapon;
	private String scouterItem;
	private String pothalaColor;
	private boolean isPermanentAura;
	private boolean isStrikeLocked;
	private int flightMode;
	private final Set<String> visitedDimensions;
	private UUID activeShadowDummyUUID;
	private int shadowDummyPercent;
	private int shadowDummyKillCount;

	public Status() {
		this.isAlive = true;
		this.forceHalo = false;
		this.isHasCreatedCharacter = false;
		this.isAuraActive = false;
		this.isActionCharging = false;
		this.isTailVisible = true;
		this.isDescending = false;
		this.isInKaioPlanet = false;
		this.isChargingKi = false;
		this.isBlocking = false;
		this.lastBlockTime = 0;
		this.lastHurtTime = 0;
		this.friendlyFistEnabled = false;
		this.stunEffect = false;
		this.isKnockedDown = false;
		this.selectedAction = ActionMode.FORM;
		this.kiWeaponType = "blade";
		this.drainingTargetId = -1;
		this.isFused = false;
		this.isFusionLeader = false;
		this.fusionPartnerUUID = null;
		this.fusionTimer = 0;
		this.fusionType = "";
		this.fusionName = "";
		this.fusionPartyManaged = false;
		this.fusionPrevPartyId = null;
		this.fusionPrevPartyLeader = false;
		this.potaraPoseTimer = 0;
		this.potaraPartnerUUID = null;
		this.potaraLeader = false;
		this.originalAppearance = new CompoundTag();
		this.androidUpgraded = false;
		this.renderKatana = false;
		this.backWeapon = "";
		this.scouterItem = "";
		this.pothalaColor = "";
		this.isPermanentAura = false;
		this.isStrikeLocked = false;
		this.flightMode = FLIGHT_SEARCH;
		this.visitedDimensions = new LinkedHashSet<>();
		this.activeShadowDummyUUID = null;
		this.shadowDummyPercent = 0;
		this.shadowDummyKillCount = 0;
	}

	public void reset() {
		this.isAlive = true;
		this.forceHalo = false;
		this.isHasCreatedCharacter = false;
		this.isAuraActive = false;
		this.isActionCharging = false;
		this.isTailVisible = true;
		this.isDescending = false;
		this.isInKaioPlanet = false;
		this.isChargingKi = false;
		this.isBlocking = false;
		this.lastBlockTime = 0;
		this.lastHurtTime = 0;
		this.friendlyFistEnabled = false;
		this.stunEffect = false;
		this.isKnockedDown = false;
		this.selectedAction = ActionMode.FORM;
		this.kiWeaponType = "blade";
		this.drainingTargetId = -1;
		this.isFused = false;
		this.isFusionLeader = false;
		this.fusionPartnerUUID = null;
		this.fusionTimer = 0;
		this.fusionType = "";
		this.fusionName = "";
		this.fusionPartyManaged = false;
		this.fusionPrevPartyId = null;
		this.fusionPrevPartyLeader = false;
		this.potaraPoseTimer = 0;
		this.potaraPartnerUUID = null;
		this.potaraLeader = false;
		this.originalAppearance = new CompoundTag();
		this.androidUpgraded = false;
		this.renderKatana = false;
		this.backWeapon = "";
		this.scouterItem = "";
		this.pothalaColor = "";
		this.isPermanentAura = false;
		this.isStrikeLocked = false;
		this.flightMode = FLIGHT_SEARCH;
		this.visitedDimensions.clear();
		this.activeShadowDummyUUID = null;
		this.shadowDummyPercent = 0;
		this.shadowDummyKillCount = 0;
	}

	public boolean isStunned() {
		return stunEffect || isKnockedDown || isStrikeLocked;
	}

	public void validateKiWeaponType() {
		var types = ConfigManager.getCombatConfig().getKiWeaponTypes();
		if (types.isEmpty()) return;
		if (kiWeaponType == null || !types.contains(kiWeaponType.toLowerCase())) kiWeaponType = types.get(0);
	}

	public boolean hasActiveShadowDummy() {
		return activeShadowDummyUUID != null;
	}

	public void markVisitedDimension(String dimensionId) {
		if (dimensionId == null || dimensionId.isBlank() || ResourceLocation.tryParse(dimensionId) == null) return;
		this.visitedDimensions.add(dimensionId);
	}

	public boolean hasVisitedDimension(String dimensionId) {
		return dimensionId != null && this.visitedDimensions.contains(dimensionId);
	}

	public CompoundTag save() {
		CompoundTag tag = new CompoundTag();
		tag.putBoolean("IsAlive", isAlive);
		tag.putBoolean("ForceHalo", forceHalo);
		tag.putBoolean("HasCreatedChar", isHasCreatedCharacter);
		tag.putBoolean("AuraActive", isAuraActive);
		tag.putBoolean("Transforming", isActionCharging);
		tag.putBoolean("TailVisible", isTailVisible);
		tag.putBoolean("Descending", isDescending);
		tag.putBoolean("InKaioPlanet", isInKaioPlanet);
		tag.putBoolean("IsChargingKi", isChargingKi);
		tag.putBoolean("IsBlocking", isBlocking);
		tag.putLong("LastBlockTime", lastBlockTime);
		tag.putLong("LastHurtTime", lastHurtTime);
		tag.putBoolean("FriendlyFistEnabled", friendlyFistEnabled);
		tag.putBoolean("IsStunned", stunEffect);
		tag.putBoolean("IsKnockedDown", isKnockedDown);
		tag.putInt("SelectedAction", selectedAction.ordinal());
		tag.putString("KiWeaponType", kiWeaponType);
		tag.putInt("DrainingTargetId", drainingTargetId);
		tag.putBoolean("IsFused", isFused);
		tag.putBoolean("IsFusionLeader", isFusionLeader);
		if (fusionPartnerUUID != null) tag.putUUID("FusionPartnerUUID", fusionPartnerUUID);
		tag.putInt("FusionTimer", fusionTimer);
		tag.putString("FusionType", fusionType);
		tag.putString("FusionName", fusionName);
		tag.putBoolean("FusionPartyManaged", fusionPartyManaged);
		if (fusionPrevPartyId != null) tag.putUUID("FusionPrevPartyId", fusionPrevPartyId);
		tag.putBoolean("FusionPrevPartyLeader", fusionPrevPartyLeader);
		tag.putInt("PotaraPoseTimer", potaraPoseTimer);
		if (potaraPartnerUUID != null) tag.putUUID("PotaraPartnerUUID", potaraPartnerUUID);
		tag.putBoolean("PotaraLeader", potaraLeader);
		tag.put("OriginalAppearance", originalAppearance);
		tag.putBoolean("AndroidUpgraded", androidUpgraded);
		tag.putBoolean("RenderKatana", renderKatana);
		tag.putString("BackWeapon", backWeapon);
		tag.putString("ScouterItem", scouterItem);
		tag.putString("PothalaColor", pothalaColor);
		tag.putBoolean("IsPermanentAura", isPermanentAura);
		tag.putBoolean("IsStrikeLocked", isStrikeLocked);
		tag.putInt("FlightMode", flightMode);
		ListTag visitedDimensionsTag = new ListTag();
		for (String dimensionId : visitedDimensions) visitedDimensionsTag.add(StringTag.valueOf(dimensionId));
		tag.put("VisitedDimensions", visitedDimensionsTag);
		if (activeShadowDummyUUID != null) tag.putUUID("ActiveShadowDummyUUID", activeShadowDummyUUID);
		tag.putInt("ShadowDummyPercent", shadowDummyPercent);
		tag.putInt("ShadowDummyKillCount", shadowDummyKillCount);
		return tag;
	}

	public void load(CompoundTag tag) {
		this.isAlive = tag.getBoolean("IsAlive");
		this.forceHalo = tag.getBoolean("ForceHalo");
		this.isHasCreatedCharacter = tag.getBoolean("HasCreatedChar");
		this.isAuraActive = tag.getBoolean("AuraActive");
		this.isActionCharging = tag.getBoolean("Transforming");
		this.isTailVisible = tag.getBoolean("TailVisible");
		this.isDescending = tag.getBoolean("Descending");
		this.isInKaioPlanet = tag.getBoolean("InKaioPlanet");
		this.isChargingKi = tag.getBoolean("IsChargingKi");
		this.isBlocking = tag.getBoolean("IsBlocking");
		this.lastBlockTime = tag.getLong("LastBlockTime");
		this.lastHurtTime = tag.getLong("LastHurtTime");
		this.friendlyFistEnabled = tag.getBoolean("FriendlyFistEnabled");
		this.stunEffect = tag.getBoolean("IsStunned");
		this.isKnockedDown = tag.getBoolean("IsKnockedDown");
		if (tag.contains("SelectedAction")) this.selectedAction = ActionMode.values()[tag.getInt("SelectedAction")];
		 else this.selectedAction = ActionMode.FORM;
		this.kiWeaponType = tag.getString("KiWeaponType");
		this.drainingTargetId = tag.getInt("DrainingTargetId");
		this.isFused = tag.getBoolean("IsFused");
		this.isFusionLeader = tag.getBoolean("IsFusionLeader");
		if (tag.hasUUID("FusionPartnerUUID")) this.fusionPartnerUUID = tag.getUUID("FusionPartnerUUID");
		 else this.fusionPartnerUUID = null;
		this.fusionTimer = tag.getInt("FusionTimer");
		this.fusionType = tag.getString("FusionType");
		this.fusionName = tag.getString("FusionName");
		this.fusionPartyManaged = tag.getBoolean("FusionPartyManaged");
		this.fusionPrevPartyId = tag.hasUUID("FusionPrevPartyId") ? tag.getUUID("FusionPrevPartyId") : null;
		this.fusionPrevPartyLeader = tag.getBoolean("FusionPrevPartyLeader");
		this.potaraPoseTimer = tag.getInt("PotaraPoseTimer");
		this.potaraPartnerUUID = tag.hasUUID("PotaraPartnerUUID") ? tag.getUUID("PotaraPartnerUUID") : null;
		this.potaraLeader = tag.getBoolean("PotaraLeader");
		if (tag.contains("OriginalAppearance")) this.originalAppearance = tag.getCompound("OriginalAppearance");
		 else this.originalAppearance = new CompoundTag();
		this.androidUpgraded = tag.getBoolean("AndroidUpgraded");
		this.renderKatana = tag.getBoolean("RenderKatana");
		this.backWeapon = tag.getString("BackWeapon");
		this.scouterItem = tag.getString("ScouterItem");
		this.pothalaColor = tag.getString("PothalaColor");
		this.isPermanentAura = tag.getBoolean("IsPermanentAura");
		this.isStrikeLocked = tag.getBoolean("IsStrikeLocked");
		this.flightMode = tag.getInt("FlightMode");
		this.visitedDimensions.clear();
		if (tag.contains("VisitedDimensions", Tag.TAG_LIST)) {
			ListTag visitedDimensionsTag = tag.getList("VisitedDimensions", Tag.TAG_STRING);
			for (Tag dimensionTag : visitedDimensionsTag) this.markVisitedDimension(dimensionTag.getAsString());
		}
		this.activeShadowDummyUUID = tag.hasUUID("ActiveShadowDummyUUID") ? tag.getUUID("ActiveShadowDummyUUID") : null;
		this.shadowDummyPercent = tag.getInt("ShadowDummyPercent");
		this.shadowDummyKillCount = tag.contains("ShadowDummyKillCount") ? tag.getInt("ShadowDummyKillCount") : 0;
	}

	public void copyFrom(Status other) {
		this.isAlive = other.isAlive;
		this.forceHalo = other.forceHalo;
		this.isHasCreatedCharacter = other.isHasCreatedCharacter;
		this.isAuraActive = other.isAuraActive;
		this.isActionCharging = other.isActionCharging;
		this.isTailVisible = other.isTailVisible;
		this.isDescending = other.isDescending;
		this.isInKaioPlanet = other.isInKaioPlanet;
		this.isChargingKi = other.isChargingKi;
		this.isBlocking = other.isBlocking;
		this.lastBlockTime = other.lastBlockTime;
		this.lastHurtTime = other.lastHurtTime;
		this.friendlyFistEnabled = other.friendlyFistEnabled;
		this.stunEffect = other.stunEffect;
		this.isKnockedDown = other.isKnockedDown;
		this.selectedAction = other.selectedAction;
		this.kiWeaponType = other.kiWeaponType;
		this.drainingTargetId = other.drainingTargetId;
		this.isFused = other.isFused;
		this.isFusionLeader = other.isFusionLeader;
		this.fusionPartnerUUID = other.fusionPartnerUUID;
		this.fusionTimer = other.fusionTimer;
		this.fusionType = other.fusionType;
		this.fusionName = other.fusionName;
		this.fusionPartyManaged = other.fusionPartyManaged;
		this.fusionPrevPartyId = other.fusionPrevPartyId;
		this.fusionPrevPartyLeader = other.fusionPrevPartyLeader;
		this.potaraPoseTimer = other.potaraPoseTimer;
		this.potaraPartnerUUID = other.potaraPartnerUUID;
		this.potaraLeader = other.potaraLeader;
		this.originalAppearance = other.originalAppearance.copy();
		this.androidUpgraded = other.androidUpgraded;
		this.renderKatana = other.renderKatana;
		this.backWeapon = other.backWeapon;
		this.pothalaColor = other.pothalaColor;
		this.scouterItem = other.scouterItem;
		this.isPermanentAura = other.isPermanentAura;
		this.isStrikeLocked = other.isStrikeLocked;
		this.flightMode = other.flightMode;
		this.visitedDimensions.clear();
		this.visitedDimensions.addAll(other.visitedDimensions);
		this.activeShadowDummyUUID = other.activeShadowDummyUUID;
		this.shadowDummyPercent = other.shadowDummyPercent;
		this.shadowDummyKillCount = other.shadowDummyKillCount;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isAlive() {
		return this.isAlive;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isForceHalo() {
		return this.forceHalo;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isHasCreatedCharacter() {
		return this.isHasCreatedCharacter;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isAuraActive() {
		return this.isAuraActive;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isActionCharging() {
		return this.isActionCharging;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isTailVisible() {
		return this.isTailVisible;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isDescending() {
		return this.isDescending;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isInKaioPlanet() {
		return this.isInKaioPlanet;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isChargingKi() {
		return this.isChargingKi;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isBlocking() {
		return this.isBlocking;
	}

	@java.lang.SuppressWarnings("all")
	public long getLastBlockTime() {
		return this.lastBlockTime;
	}

	@java.lang.SuppressWarnings("all")
	public long getLastHurtTime() {
		return this.lastHurtTime;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isFriendlyFistEnabled() {
		return this.friendlyFistEnabled;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isStunEffect() {
		return this.stunEffect;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isKnockedDown() {
		return this.isKnockedDown;
	}

	@java.lang.SuppressWarnings("all")
	public ActionMode getSelectedAction() {
		return this.selectedAction;
	}

	@java.lang.SuppressWarnings("all")
	public String getKiWeaponType() {
		return this.kiWeaponType;
	}

	@java.lang.SuppressWarnings("all")
	public int getDrainingTargetId() {
		return this.drainingTargetId;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isFused() {
		return this.isFused;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isFusionLeader() {
		return this.isFusionLeader;
	}

	@java.lang.SuppressWarnings("all")
	public UUID getFusionPartnerUUID() {
		return this.fusionPartnerUUID;
	}

	@java.lang.SuppressWarnings("all")
	public int getFusionTimer() {
		return this.fusionTimer;
	}

	@java.lang.SuppressWarnings("all")
	public String getFusionType() {
		return this.fusionType;
	}

	@java.lang.SuppressWarnings("all")
	public String getFusionName() {
		return this.fusionName;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isFusionPartyManaged() {
		return this.fusionPartyManaged;
	}

	@java.lang.SuppressWarnings("all")
	public UUID getFusionPrevPartyId() {
		return this.fusionPrevPartyId;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isFusionPrevPartyLeader() {
		return this.fusionPrevPartyLeader;
	}

	@java.lang.SuppressWarnings("all")
	public int getPotaraPoseTimer() {
		return this.potaraPoseTimer;
	}

	@java.lang.SuppressWarnings("all")
	public UUID getPotaraPartnerUUID() {
		return this.potaraPartnerUUID;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isPotaraLeader() {
		return this.potaraLeader;
	}

	@java.lang.SuppressWarnings("all")
	public CompoundTag getOriginalAppearance() {
		return this.originalAppearance;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isAndroidUpgraded() {
		return this.androidUpgraded;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isRenderKatana() {
		return this.renderKatana;
	}

	@java.lang.SuppressWarnings("all")
	public String getBackWeapon() {
		return this.backWeapon;
	}

	@java.lang.SuppressWarnings("all")
	public String getScouterItem() {
		return this.scouterItem;
	}

	@java.lang.SuppressWarnings("all")
	public String getPothalaColor() {
		return this.pothalaColor;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isPermanentAura() {
		return this.isPermanentAura;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isStrikeLocked() {
		return this.isStrikeLocked;
	}

	@java.lang.SuppressWarnings("all")
	public int getFlightMode() {
		return this.flightMode;
	}

	@java.lang.SuppressWarnings("all")
	public Set<String> getVisitedDimensions() {
		return this.visitedDimensions;
	}

	@java.lang.SuppressWarnings("all")
	public UUID getActiveShadowDummyUUID() {
		return this.activeShadowDummyUUID;
	}

	@java.lang.SuppressWarnings("all")
	public int getShadowDummyPercent() {
		return this.shadowDummyPercent;
	}

	@java.lang.SuppressWarnings("all")
	public int getShadowDummyKillCount() {
		return this.shadowDummyKillCount;
	}

	@java.lang.SuppressWarnings("all")
	public void setAlive(final boolean isAlive) {
		this.isAlive = isAlive;
	}

	@java.lang.SuppressWarnings("all")
	public void setForceHalo(final boolean forceHalo) {
		this.forceHalo = forceHalo;
	}

	@java.lang.SuppressWarnings("all")
	public void setHasCreatedCharacter(final boolean isHasCreatedCharacter) {
		this.isHasCreatedCharacter = isHasCreatedCharacter;
	}

	@java.lang.SuppressWarnings("all")
	public void setAuraActive(final boolean isAuraActive) {
		this.isAuraActive = isAuraActive;
	}

	@java.lang.SuppressWarnings("all")
	public void setActionCharging(final boolean isActionCharging) {
		this.isActionCharging = isActionCharging;
	}

	@java.lang.SuppressWarnings("all")
	public void setTailVisible(final boolean isTailVisible) {
		this.isTailVisible = isTailVisible;
	}

	@java.lang.SuppressWarnings("all")
	public void setDescending(final boolean isDescending) {
		this.isDescending = isDescending;
	}

	@java.lang.SuppressWarnings("all")
	public void setInKaioPlanet(final boolean isInKaioPlanet) {
		this.isInKaioPlanet = isInKaioPlanet;
	}

	@java.lang.SuppressWarnings("all")
	public void setChargingKi(final boolean isChargingKi) {
		this.isChargingKi = isChargingKi;
	}

	@java.lang.SuppressWarnings("all")
	public void setBlocking(final boolean isBlocking) {
		this.isBlocking = isBlocking;
	}

	@java.lang.SuppressWarnings("all")
	public void setLastBlockTime(final long lastBlockTime) {
		this.lastBlockTime = lastBlockTime;
	}

	@java.lang.SuppressWarnings("all")
	public void setLastHurtTime(final long lastHurtTime) {
		this.lastHurtTime = lastHurtTime;
	}

	@java.lang.SuppressWarnings("all")
	public void setFriendlyFistEnabled(final boolean friendlyFistEnabled) {
		this.friendlyFistEnabled = friendlyFistEnabled;
	}

	@java.lang.SuppressWarnings("all")
	public void setStunEffect(final boolean stunEffect) {
		this.stunEffect = stunEffect;
	}

	@java.lang.SuppressWarnings("all")
	public void setKnockedDown(final boolean isKnockedDown) {
		this.isKnockedDown = isKnockedDown;
	}

	@java.lang.SuppressWarnings("all")
	public void setSelectedAction(final ActionMode selectedAction) {
		this.selectedAction = selectedAction;
	}

	@java.lang.SuppressWarnings("all")
	public void setKiWeaponType(final String kiWeaponType) {
		this.kiWeaponType = kiWeaponType;
	}

	@java.lang.SuppressWarnings("all")
	public void setDrainingTargetId(final int drainingTargetId) {
		this.drainingTargetId = drainingTargetId;
	}

	@java.lang.SuppressWarnings("all")
	public void setFused(final boolean isFused) {
		this.isFused = isFused;
	}

	@java.lang.SuppressWarnings("all")
	public void setFusionLeader(final boolean isFusionLeader) {
		this.isFusionLeader = isFusionLeader;
	}

	@java.lang.SuppressWarnings("all")
	public void setFusionPartnerUUID(final UUID fusionPartnerUUID) {
		this.fusionPartnerUUID = fusionPartnerUUID;
	}

	@java.lang.SuppressWarnings("all")
	public void setFusionTimer(final int fusionTimer) {
		this.fusionTimer = fusionTimer;
	}

	@java.lang.SuppressWarnings("all")
	public void setFusionType(final String fusionType) {
		this.fusionType = fusionType;
	}

	@java.lang.SuppressWarnings("all")
	public void setFusionName(final String fusionName) {
		this.fusionName = fusionName;
	}

	@java.lang.SuppressWarnings("all")
	public void setFusionPartyManaged(final boolean fusionPartyManaged) {
		this.fusionPartyManaged = fusionPartyManaged;
	}

	@java.lang.SuppressWarnings("all")
	public void setFusionPrevPartyId(final UUID fusionPrevPartyId) {
		this.fusionPrevPartyId = fusionPrevPartyId;
	}

	@java.lang.SuppressWarnings("all")
	public void setFusionPrevPartyLeader(final boolean fusionPrevPartyLeader) {
		this.fusionPrevPartyLeader = fusionPrevPartyLeader;
	}

	@java.lang.SuppressWarnings("all")
	public void setPotaraPoseTimer(final int potaraPoseTimer) {
		this.potaraPoseTimer = potaraPoseTimer;
	}

	@java.lang.SuppressWarnings("all")
	public void setPotaraPartnerUUID(final UUID potaraPartnerUUID) {
		this.potaraPartnerUUID = potaraPartnerUUID;
	}

	@java.lang.SuppressWarnings("all")
	public void setPotaraLeader(final boolean potaraLeader) {
		this.potaraLeader = potaraLeader;
	}

	@java.lang.SuppressWarnings("all")
	public void setOriginalAppearance(final CompoundTag originalAppearance) {
		this.originalAppearance = originalAppearance;
	}

	@java.lang.SuppressWarnings("all")
	public void setAndroidUpgraded(final boolean androidUpgraded) {
		this.androidUpgraded = androidUpgraded;
	}

	@java.lang.SuppressWarnings("all")
	public void setRenderKatana(final boolean renderKatana) {
		this.renderKatana = renderKatana;
	}

	@java.lang.SuppressWarnings("all")
	public void setBackWeapon(final String backWeapon) {
		this.backWeapon = backWeapon;
	}

	@java.lang.SuppressWarnings("all")
	public void setScouterItem(final String scouterItem) {
		this.scouterItem = scouterItem;
	}

	@java.lang.SuppressWarnings("all")
	public void setPothalaColor(final String pothalaColor) {
		this.pothalaColor = pothalaColor;
	}

	@java.lang.SuppressWarnings("all")
	public void setPermanentAura(final boolean isPermanentAura) {
		this.isPermanentAura = isPermanentAura;
	}

	@java.lang.SuppressWarnings("all")
	public void setStrikeLocked(final boolean isStrikeLocked) {
		this.isStrikeLocked = isStrikeLocked;
	}

	@java.lang.SuppressWarnings("all")
	public void setFlightMode(final int flightMode) {
		this.flightMode = flightMode;
	}

	@java.lang.SuppressWarnings("all")
	public void setActiveShadowDummyUUID(final UUID activeShadowDummyUUID) {
		this.activeShadowDummyUUID = activeShadowDummyUUID;
	}

	@java.lang.SuppressWarnings("all")
	public void setShadowDummyPercent(final int shadowDummyPercent) {
		this.shadowDummyPercent = shadowDummyPercent;
	}

	@java.lang.SuppressWarnings("all")
	public void setShadowDummyKillCount(final int shadowDummyKillCount) {
		this.shadowDummyKillCount = shadowDummyKillCount;
	}
}
