// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.events;

import com.dragonminez.common.dragonball.DragonBallSetDefinition;
import com.dragonminez.common.dragonball.DragonDefinition;
import com.dragonminez.common.quest.Difficulty;
import com.dragonminez.common.quest.Quest;
import com.dragonminez.common.quest.Saga;
import com.dragonminez.common.stats.StatsData;
import com.dragonminez.common.stats.techniques.KiAttackData;
import com.dragonminez.common.stats.techniques.StrikeAttackData;
import net.minecraft.core.BlockPos;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.player.Player;
import net.neoforged.bus.api.ICancellableEvent;
import net.neoforged.bus.api.Event;
import java.util.List;

public abstract class DMZEvent extends Event {
	private static String buildQuestKey(Saga saga, Quest quest) {
		if (quest == null) {
			return "";
		}
		if (saga == null) {
			return quest.getStringId() != null ? quest.getStringId() : String.valueOf(quest.getId());
		}
		return saga.getId() + ":" + quest.getId();
	}

	// @Cancelable -> implement ICancellableEvent on event type if needed
	/**
	 * Event fired when a player's stat is about to change, doesn't matter from what source.
	 * This includes increases and decreases to stats, fired through commands, items, interfaces, etc.
	 * This event is cancelable; if canceled, the stat change will not occur.
	 */
	public static class StatChangeEvent extends Event implements ICancellableEvent {
		private final Player player;
		private final StatType stat;
		private final int oldValue;
		private final int newValue;

		public StatChangeEvent(Player player, StatType stat, int oldValue, int newValue) {
			this.player = player;
			this.stat = stat;
			this.oldValue = oldValue;
			this.newValue = newValue;
		}


		public enum StatType {
			STRENGTH, STRIKE_POWER, RESISTANCE, VITALITY, KI_POWER, ENERGY;
		}

		@java.lang.SuppressWarnings("all")
		public Player getPlayer() {
			return this.player;
		}

		@java.lang.SuppressWarnings("all")
		public StatType getStat() {
			return this.stat;
		}

		@java.lang.SuppressWarnings("all")
		public int getOldValue() {
			return this.oldValue;
		}

		@java.lang.SuppressWarnings("all")
		public int getNewValue() {
			return this.newValue;
		}
	}

	// @Cancelable -> implement ICancellableEvent on event type if needed
	/**
	 * Event fired when a player is about to charge ki energy.
	 * This event is cancelable; if canceled, the ki charge will not occur.
	 */
	public static class KiChargeEvent extends Event implements ICancellableEvent {
		private final Player player;
		private final float currentEnergy;
		private final float maxEnergy;

		public KiChargeEvent(Player player, float currentEnergy, float maxEnergy) {
			this.player = player;
			this.currentEnergy = currentEnergy;
			this.maxEnergy = maxEnergy;
		}

		public boolean isEnergyFull() {
			return currentEnergy >= maxEnergy;
		}

		@java.lang.SuppressWarnings("all")
		public Player getPlayer() {
			return this.player;
		}

		@java.lang.SuppressWarnings("all")
		public float getCurrentEnergy() {
			return this.currentEnergy;
		}

		@java.lang.SuppressWarnings("all")
		public float getMaxEnergy() {
			return this.maxEnergy;
		}
	}

	// @Cancelable -> implement ICancellableEvent on event type if needed
	/**
	 * Event fired when a player is about to gain training points.
	 * This event is cancelable; if canceled, the TP gain will not occur.
	 */
	public static class TPGainEvent extends Event implements ICancellableEvent {
		private final Player player;
		private final int oldValue;
		private boolean shareWithParty;
		private int tpGain;

		public TPGainEvent(Player player, int oldValue, int tpGain, boolean shareWithParty) {
			this.player = player;
			this.oldValue = oldValue;
			this.tpGain = tpGain;
			this.shareWithParty = shareWithParty;
		}

		public int getNewTpsValue() {
			return oldValue + tpGain;
		}

		public boolean getShareWithParty() {
			return shareWithParty;
		}

		@java.lang.SuppressWarnings("all")
		public Player getPlayer() {
			return this.player;
		}

		@java.lang.SuppressWarnings("all")
		public int getOldValue() {
			return this.oldValue;
		}

		@java.lang.SuppressWarnings("all")
		public int getTpGain() {
			return this.tpGain;
		}

		@java.lang.SuppressWarnings("all")
		public void setShareWithParty(final boolean shareWithParty) {
			this.shareWithParty = shareWithParty;
		}

		@java.lang.SuppressWarnings("all")
		public void setTpGain(final int tpGain) {
			this.tpGain = tpGain;
		}
	}

	// @Cancelable -> implement ICancellableEvent on event type if needed
	/**
	 * Event fired when a player successfully blocks an attack.
	 * This event is cancelable; if canceled, the block will not occur, so the player will take full damage.
	 */
	public static class PlayerBlockEvent extends Event implements ICancellableEvent {
		private final ServerPlayer victim;
		private final LivingEntity attacker;
		private final float originalDamage;
		private float finalDamage;
		private boolean isParry;
		private float poiseDamage;

		public PlayerBlockEvent(ServerPlayer victim, LivingEntity attacker, float originalDamage, float finalDamage, boolean isParry, float poiseDamage) {
			this.victim = victim;
			this.attacker = attacker;
			this.originalDamage = originalDamage;
			this.finalDamage = finalDamage;
			this.isParry = isParry;
			this.poiseDamage = poiseDamage;
		}

		@java.lang.SuppressWarnings("all")
		public ServerPlayer getVictim() {
			return this.victim;
		}

		@java.lang.SuppressWarnings("all")
		public LivingEntity getAttacker() {
			return this.attacker;
		}

		@java.lang.SuppressWarnings("all")
		public float getOriginalDamage() {
			return this.originalDamage;
		}

		@java.lang.SuppressWarnings("all")
		public float getFinalDamage() {
			return this.finalDamage;
		}

		@java.lang.SuppressWarnings("all")
		public boolean isParry() {
			return this.isParry;
		}

		@java.lang.SuppressWarnings("all")
		public float getPoiseDamage() {
			return this.poiseDamage;
		}

		@java.lang.SuppressWarnings("all")
		public void setFinalDamage(final float finalDamage) {
			this.finalDamage = finalDamage;
		}

		@java.lang.SuppressWarnings("all")
		public void setParry(final boolean isParry) {
			this.isParry = isParry;
		}

		@java.lang.SuppressWarnings("all")
		public void setPoiseDamage(final float poiseDamage) {
			this.poiseDamage = poiseDamage;
		}
	}

	// @Cancelable -> implement ICancellableEvent on event type if needed
	/**
	 * Event fired when a player performs a dash.
	 * This event is cancelable; if canceled, the dash will not occur.
	 */
	public static class PlayerDashEvent extends Event implements ICancellableEvent {
		private final ServerPlayer player;
		private final DashType dashType;
		private double distance;
		private int kiCost;

		public PlayerDashEvent(ServerPlayer player, DashType dashType, double distance, int kiCost) {
			this.player = player;
			this.dashType = dashType;
			this.distance = distance;
			this.kiCost = kiCost;
		}


		public enum DashType {
			NORMAL, DOUBLE;
		}

		@java.lang.SuppressWarnings("all")
		public ServerPlayer getPlayer() {
			return this.player;
		}

		@java.lang.SuppressWarnings("all")
		public DashType getDashType() {
			return this.dashType;
		}

		@java.lang.SuppressWarnings("all")
		public double getDistance() {
			return this.distance;
		}

		@java.lang.SuppressWarnings("all")
		public int getKiCost() {
			return this.kiCost;
		}

		@java.lang.SuppressWarnings("all")
		public void setDistance(final double distance) {
			this.distance = distance;
		}

		@java.lang.SuppressWarnings("all")
		public void setKiCost(final int kiCost) {
			this.kiCost = kiCost;
		}
	}

	// @Cancelable -> implement ICancellableEvent on event type if needed
	/**
	 * Event fired when a player successfully evades an attack.
	 * This event is cancelable; if canceled, the evasion will not occur.
	 */
	public static class PlayerEvasionEvent extends Event implements ICancellableEvent {
		private final ServerPlayer player;
		private final LivingEntity attacker;
		private final float originalDamage;
		private int kiCost;

		public PlayerEvasionEvent(ServerPlayer player, LivingEntity attacker, float originalDamage, int kiCost) {
			this.player = player;
			this.attacker = attacker;
			this.originalDamage = originalDamage;
			this.kiCost = kiCost;
		}

		@java.lang.SuppressWarnings("all")
		public ServerPlayer getPlayer() {
			return this.player;
		}

		@java.lang.SuppressWarnings("all")
		public LivingEntity getAttacker() {
			return this.attacker;
		}

		@java.lang.SuppressWarnings("all")
		public float getOriginalDamage() {
			return this.originalDamage;
		}

		@java.lang.SuppressWarnings("all")
		public int getKiCost() {
			return this.kiCost;
		}

		@java.lang.SuppressWarnings("all")
		public void setKiCost(final int kiCost) {
			this.kiCost = kiCost;
		}
	}

	// @Cancelable -> implement ICancellableEvent on event type if needed
	/**
	 * Event fired when two entities are about to fuse.
	 * This event is cancelable; if canceled, the fusion will not occur.
	 */
	public static class FusionEvent extends Event implements ICancellableEvent {
		private final ServerPlayer initiator;
		private final LivingEntity target;
		private final FusionType type;

		public FusionEvent(ServerPlayer initiator, LivingEntity target, FusionType type) {
			this.initiator = initiator;
			this.target = target;
			this.type = type;
		}


		public enum FusionType {
			METAMORU, POTHALA, ABSORPTION, ASSIMILATION;
		}

		@java.lang.SuppressWarnings("all")
		public ServerPlayer getInitiator() {
			return this.initiator;
		}

		@java.lang.SuppressWarnings("all")
		public LivingEntity getTarget() {
			return this.target;
		}

		@java.lang.SuppressWarnings("all")
		public FusionType getType() {
			return this.type;
		}
	}


	/**
	 * Event fired after a dragon has been successfully summoned from a complete Dragon Ball set.
	 */
	public static class DragonSummonedEvent extends Event {
		private final Player player;
		private final ServerLevel level;
		private final BlockPos position;
		private final DragonDefinition dragonDefinition;
		private final DragonBallSetDefinition ballSetDefinition;
		private final List<BlockPos> consumedPositions;

		public DragonSummonedEvent(Player player, ServerLevel level, BlockPos position, DragonDefinition dragonDefinition, DragonBallSetDefinition ballSetDefinition, List<BlockPos> consumedPositions) {
			this.player = player;
			this.level = level;
			this.position = position != null ? position.immutable() : BlockPos.ZERO;
			this.dragonDefinition = dragonDefinition;
			this.ballSetDefinition = ballSetDefinition;
			this.consumedPositions = consumedPositions == null ? List.of() : consumedPositions.stream().map(BlockPos::immutable).toList();
		}

		public String getDragonId() {
			return dragonDefinition != null ? dragonDefinition.getId() : "";
		}

		public String getBallSetId() {
			return ballSetDefinition != null ? ballSetDefinition.getId() : "";
		}

		@java.lang.SuppressWarnings("all")
		public Player getPlayer() {
			return this.player;
		}

		@java.lang.SuppressWarnings("all")
		public ServerLevel getLevel() {
			return this.level;
		}

		@java.lang.SuppressWarnings("all")
		public BlockPos getPosition() {
			return this.position;
		}

		@java.lang.SuppressWarnings("all")
		public DragonDefinition getDragonDefinition() {
			return this.dragonDefinition;
		}

		@java.lang.SuppressWarnings("all")
		public DragonBallSetDefinition getBallSetDefinition() {
			return this.ballSetDefinition;
		}

		@java.lang.SuppressWarnings("all")
		public List<BlockPos> getConsumedPositions() {
			return this.consumedPositions;
		}
	}


	/**
	 * Base event for quest lifecycle hooks (start/progress/fail/turn-in/reward/complete).
	 */
	public static abstract class QuestLifecycleEvent extends Event implements ICancellableEvent {
		private final ServerPlayer player;
		private final String questKey;
		private final Saga saga;
		private final Quest quest;
		private final List<ServerPlayer> partyMembers;

		public QuestLifecycleEvent(ServerPlayer player, String questKey, Saga saga, Quest quest, List<ServerPlayer> partyMembers) {
			this.player = player;
			this.questKey = questKey == null ? "" : questKey;
			this.saga = saga;
			this.quest = quest;
			this.partyMembers = partyMembers == null ? List.of() : List.copyOf(partyMembers);
		}

		@java.lang.SuppressWarnings("all")
		public ServerPlayer getPlayer() {
			return this.player;
		}

		@java.lang.SuppressWarnings("all")
		public String getQuestKey() {
			return this.questKey;
		}

		@java.lang.SuppressWarnings("all")
		public Saga getSaga() {
			return this.saga;
		}

		@java.lang.SuppressWarnings("all")
		public Quest getQuest() {
			return this.quest;
		}

		@java.lang.SuppressWarnings("all")
		public List<ServerPlayer> getPartyMembers() {
			return this.partyMembers;
		}
	}

	// @Cancelable -> implement ICancellableEvent on event type if needed
	/**
	 * Event fired before a quest is accepted.
	 */
	public static class QuestStartEvent extends QuestLifecycleEvent {
		private Difficulty difficulty;

		public QuestStartEvent(ServerPlayer player, String questKey, Saga saga, Quest quest, List<ServerPlayer> partyMembers, Difficulty difficulty) {
			super(player, questKey, saga, quest, partyMembers);
			this.difficulty = difficulty;
		}

		@java.lang.SuppressWarnings("all")
		public void setDifficulty(final Difficulty difficulty) {
			this.difficulty = difficulty;
		}

		@java.lang.SuppressWarnings("all")
		public Difficulty getDifficulty() {
			return this.difficulty;
		}
	}

	// @Cancelable -> implement ICancellableEvent on event type if needed
	/**
	 * Event fired before objective progress is stored.
	 */
	public static class QuestObjectiveProgressEvent extends QuestLifecycleEvent {
		private final int objectiveIndex;
		private final int oldProgress;
		private int newProgress;
		private final int objectiveRequired;

		public QuestObjectiveProgressEvent(ServerPlayer player, String questKey, Saga saga, Quest quest, List<ServerPlayer> partyMembers, int objectiveIndex, int oldProgress, int newProgress, int objectiveRequired) {
			super(player, questKey, saga, quest, partyMembers);
			this.objectiveIndex = objectiveIndex;
			this.oldProgress = oldProgress;
			this.newProgress = newProgress;
			this.objectiveRequired = objectiveRequired;
		}

		@java.lang.SuppressWarnings("all")
		public int getObjectiveIndex() {
			return this.objectiveIndex;
		}

		@java.lang.SuppressWarnings("all")
		public int getOldProgress() {
			return this.oldProgress;
		}

		@java.lang.SuppressWarnings("all")
		public int getNewProgress() {
			return this.newProgress;
		}

		@java.lang.SuppressWarnings("all")
		public int getObjectiveRequired() {
			return this.objectiveRequired;
		}

		@java.lang.SuppressWarnings("all")
		public void setNewProgress(final int newProgress) {
			this.newProgress = newProgress;
		}
	}

	// @Cancelable -> implement ICancellableEvent on event type if needed
	/**
	 * Event fired before a quest is marked as failed.
	 */
	public static class QuestFailEvent extends QuestLifecycleEvent {
		private final FailureReason reason;

		public QuestFailEvent(ServerPlayer player, String questKey, Saga saga, Quest quest, List<ServerPlayer> partyMembers, FailureReason reason) {
			super(player, questKey, saga, quest, partyMembers);
			this.reason = reason;
		}


		public enum FailureReason {
			PLAYER_DEATH, FORCED_RESET, SCRIPT;
		}

		@java.lang.SuppressWarnings("all")
		public FailureReason getReason() {
			return this.reason;
		}
	}

	// @Cancelable -> implement ICancellableEvent on event type if needed
	/**
	 * Event fired before a quest turn-in action is applied.
	 */
	public static class QuestTurnInEvent extends QuestLifecycleEvent {
		private final String npcId;

		public QuestTurnInEvent(ServerPlayer player, String questKey, Saga saga, Quest quest, List<ServerPlayer> partyMembers, String npcId) {
			super(player, questKey, saga, quest, partyMembers);
			this.npcId = npcId == null ? "" : npcId;
		}

		@java.lang.SuppressWarnings("all")
		public String getNpcId() {
			return this.npcId;
		}
	}

	// @Cancelable -> implement ICancellableEvent on event type if needed
	/**
	 * Event fired before an individual reward is claimed.
	 */
	public static class QuestRewardClaimEvent extends QuestLifecycleEvent {
		private final int rewardIndex;

		public QuestRewardClaimEvent(ServerPlayer player, String questKey, Saga saga, Quest quest, List<ServerPlayer> partyMembers, int rewardIndex) {
			super(player, questKey, saga, quest, partyMembers);
			this.rewardIndex = rewardIndex;
		}

		@java.lang.SuppressWarnings("all")
		public int getRewardIndex() {
			return this.rewardIndex;
		}
	}


	/**
	 * Fires when quest is completed
	 */
	public static class QuestCompletedEvent extends QuestLifecycleEvent {
		public QuestCompletedEvent(ServerPlayer player, Saga saga, Quest quest, List<ServerPlayer> partyMembers) {
			super(player, buildQuestKey(saga, quest), saga, quest, partyMembers);
		}

		public QuestCompletedEvent(ServerPlayer player, String questKey, Saga saga, Quest quest, List<ServerPlayer> partyMembers) {
			super(player, questKey, saga, quest, partyMembers);
		}
	}


	/**
	 * Event fired when a player's data is being saved.
	 */
	public static class PlayerDataSaveEvent extends Event implements ICancellableEvent {
		private final ServerPlayer player;
		private final CompoundTag data;

		public PlayerDataSaveEvent(ServerPlayer player, CompoundTag data) {
			this.player = player;
			this.data = data;
		}

		@java.lang.SuppressWarnings("all")
		public ServerPlayer getPlayer() {
			return this.player;
		}

		@java.lang.SuppressWarnings("all")
		public CompoundTag getData() {
			return this.data;
		}
	}


	/**
	 * Event fired when a player's data is being loaded.
	 */
	public static class PlayerDataLoadEvent extends Event {
		private final ServerPlayer player;
		private final CompoundTag data;

		public PlayerDataLoadEvent(ServerPlayer player, CompoundTag data) {
			this.player = player;
			this.data = data;
		}

		@java.lang.SuppressWarnings("all")
		public ServerPlayer getPlayer() {
			return this.player;
		}

		@java.lang.SuppressWarnings("all")
		public CompoundTag getData() {
			return this.data;
		}
	}

	// @Cancelable -> implement ICancellableEvent on event type if needed
	/**
	 * Base for the per-second resource regeneration events. Modify {@link #amount} or cancel to suppress.
	 */
	public static abstract class ResourceRegenEvent extends Event implements ICancellableEvent {
		private final Player player;
		private final StatsData statsData;
		private double amount;

		protected ResourceRegenEvent(Player player, StatsData statsData, double amount) {
			this.player = player;
			this.statsData = statsData;
			this.amount = amount;
		}

		@java.lang.SuppressWarnings("all")
		public Player getPlayer() {
			return this.player;
		}

		@java.lang.SuppressWarnings("all")
		public StatsData getStatsData() {
			return this.statsData;
		}

		@java.lang.SuppressWarnings("all")
		public double getAmount() {
			return this.amount;
		}

		@java.lang.SuppressWarnings("all")
		public void setAmount(final double amount) {
			this.amount = amount;
		}
	}


	/**
	 * Fired before the per-second health (HP5) regen is applied.
	 */
	public static class HealthRegenEvent extends ResourceRegenEvent {
		public HealthRegenEvent(Player player, StatsData statsData, double amount) {
			super(player, statsData, amount);
		}
	}


	/**
	 * Fired before the per-second energy (Ki) regen is applied.
	 */
	public static class EnergyRegenEvent extends ResourceRegenEvent {
		public EnergyRegenEvent(Player player, StatsData statsData, double amount) {
			super(player, statsData, amount);
		}
	}


	/**
	 * Fired before the per-second stamina (STM) regen is applied.
	 */
	public static class StaminaRegenEvent extends ResourceRegenEvent {
		public StaminaRegenEvent(Player player, StatsData statsData, double amount) {
			super(player, statsData, amount);
		}
	}


	public enum DamageSourceType {
		MELEE, KI, STRIKE;
	}

	// @Cancelable -> implement ICancellableEvent on event type if needed
	/**
	 * Phase 1: fired pre-mitigation for an outgoing hit. Modify {@link #amount}/{@link #defensePenetration} or cancel.
	 */
	public static class DamageModifyEvent extends Event implements ICancellableEvent {
		private final Player attacker;
		private final LivingEntity victim;
		private double amount;
		private double defensePenetration;
		private final DamageSourceType sourceType;

		public DamageModifyEvent(Player attacker, LivingEntity victim, double amount, double defensePenetration, DamageSourceType sourceType) {
			this.attacker = attacker;
			this.victim = victim;
			this.amount = amount;
			this.defensePenetration = defensePenetration;
			this.sourceType = sourceType;
		}

		@java.lang.SuppressWarnings("all")
		public Player getAttacker() {
			return this.attacker;
		}

		@java.lang.SuppressWarnings("all")
		public LivingEntity getVictim() {
			return this.victim;
		}

		@java.lang.SuppressWarnings("all")
		public double getAmount() {
			return this.amount;
		}

		@java.lang.SuppressWarnings("all")
		public double getDefensePenetration() {
			return this.defensePenetration;
		}

		@java.lang.SuppressWarnings("all")
		public DamageSourceType getSourceType() {
			return this.sourceType;
		}

		@java.lang.SuppressWarnings("all")
		public void setAmount(final double amount) {
			this.amount = amount;
		}

		@java.lang.SuppressWarnings("all")
		public void setDefensePenetration(final double defensePenetration) {
			this.defensePenetration = defensePenetration;
		}
	}


	/**
	 * Phase 2: notification fired after blocking is resolved for a DMZ hit (pre-mitigation amount).
	 */
	public static class DamageDealtEvent extends Event {
		private final Player attacker;
		private final LivingEntity victim;
		private final double amount;
		private final boolean blocked;
		private final boolean parried;
		private final DamageSourceType sourceType;

		public DamageDealtEvent(Player attacker, LivingEntity victim, double amount, boolean blocked, boolean parried, DamageSourceType sourceType) {
			this.attacker = attacker;
			this.victim = victim;
			this.amount = amount;
			this.blocked = blocked;
			this.parried = parried;
			this.sourceType = sourceType;
		}

		@java.lang.SuppressWarnings("all")
		public Player getAttacker() {
			return this.attacker;
		}

		@java.lang.SuppressWarnings("all")
		public LivingEntity getVictim() {
			return this.victim;
		}

		@java.lang.SuppressWarnings("all")
		public double getAmount() {
			return this.amount;
		}

		@java.lang.SuppressWarnings("all")
		public boolean isBlocked() {
			return this.blocked;
		}

		@java.lang.SuppressWarnings("all")
		public boolean isParried() {
			return this.parried;
		}

		@java.lang.SuppressWarnings("all")
		public DamageSourceType getSourceType() {
			return this.sourceType;
		}
	}


	/**
	 * Fired when resolving a player's crit chance. Listeners may modify {@link #chance} (0..1).
	 */
	public static class CritChanceEvent extends Event {
		private final Player player;
		private double chance;

		public CritChanceEvent(Player player, double chance) {
			this.player = player;
			this.chance = chance;
		}

		@java.lang.SuppressWarnings("all")
		public Player getPlayer() {
			return this.player;
		}

		@java.lang.SuppressWarnings("all")
		public double getChance() {
			return this.chance;
		}

		@java.lang.SuppressWarnings("all")
		public void setChance(final double chance) {
			this.chance = chance;
		}
	}


	/**
	 * Notification fired when a player begins charging (casts) a Ki attack.
	 */
	public static class KiAttackCastEvent extends Event {
		private final Player player;
		private final StatsData statsData;
		private final KiAttackData kiAttack;

		public KiAttackCastEvent(Player player, StatsData statsData, KiAttackData kiAttack) {
			this.player = player;
			this.statsData = statsData;
			this.kiAttack = kiAttack;
		}

		@java.lang.SuppressWarnings("all")
		public Player getPlayer() {
			return this.player;
		}

		@java.lang.SuppressWarnings("all")
		public StatsData getStatsData() {
			return this.statsData;
		}

		@java.lang.SuppressWarnings("all")
		public KiAttackData getKiAttack() {
			return this.kiAttack;
		}
	}


	/**
	 * Fired when a Ki attack is released (fired). Listeners may modify {@link #cooldownTicks}.
	 */
	public static class KiAttackFireEvent extends Event {
		private final Player player;
		private final StatsData statsData;
		private final KiAttackData kiAttack;
		private final float chargeMultiplier;
		private int cooldownTicks;

		public KiAttackFireEvent(Player player, StatsData statsData, KiAttackData kiAttack, float chargeMultiplier, int cooldownTicks) {
			this.player = player;
			this.statsData = statsData;
			this.kiAttack = kiAttack;
			this.chargeMultiplier = chargeMultiplier;
			this.cooldownTicks = cooldownTicks;
		}

		@java.lang.SuppressWarnings("all")
		public Player getPlayer() {
			return this.player;
		}

		@java.lang.SuppressWarnings("all")
		public StatsData getStatsData() {
			return this.statsData;
		}

		@java.lang.SuppressWarnings("all")
		public KiAttackData getKiAttack() {
			return this.kiAttack;
		}

		@java.lang.SuppressWarnings("all")
		public float getChargeMultiplier() {
			return this.chargeMultiplier;
		}

		@java.lang.SuppressWarnings("all")
		public int getCooldownTicks() {
			return this.cooldownTicks;
		}

		@java.lang.SuppressWarnings("all")
		public void setCooldownTicks(final int cooldownTicks) {
			this.cooldownTicks = cooldownTicks;
		}
	}


	/**
	 * Notification fired when a player initiates (casts) a strike attack.
	 */
	public static class StrikeAttackCastEvent extends Event {
		private final ServerPlayer player;
		private final StatsData statsData;
		private final StrikeAttackData strike;

		public StrikeAttackCastEvent(ServerPlayer player, StatsData statsData, StrikeAttackData strike) {
			this.player = player;
			this.statsData = statsData;
			this.strike = strike;
		}

		@java.lang.SuppressWarnings("all")
		public ServerPlayer getPlayer() {
			return this.player;
		}

		@java.lang.SuppressWarnings("all")
		public StatsData getStatsData() {
			return this.statsData;
		}

		@java.lang.SuppressWarnings("all")
		public StrikeAttackData getStrike() {
			return this.strike;
		}
	}


	/**
	 * Notification fired when a strike attack connects and begins (fires) on a target.
	 */
	public static class StrikeAttackFireEvent extends Event {
		private final ServerPlayer player;
		private final StatsData statsData;
		private final StrikeAttackData strike;
		private final LivingEntity target;

		public StrikeAttackFireEvent(ServerPlayer player, StatsData statsData, StrikeAttackData strike, LivingEntity target) {
			this.player = player;
			this.statsData = statsData;
			this.strike = strike;
			this.target = target;
		}

		@java.lang.SuppressWarnings("all")
		public ServerPlayer getPlayer() {
			return this.player;
		}

		@java.lang.SuppressWarnings("all")
		public StatsData getStatsData() {
			return this.statsData;
		}

		@java.lang.SuppressWarnings("all")
		public StrikeAttackData getStrike() {
			return this.strike;
		}

		@java.lang.SuppressWarnings("all")
		public LivingEntity getTarget() {
			return this.target;
		}
	}


	/**
	 * Notification fired when a player's base form changes (transform or untransform).
	 */
	public static class FormChangeEvent extends Event {
		private final ServerPlayer player;
		private final String oldGroup;
		private final String oldForm;
		private final String newGroup;
		private final String newForm;

		public FormChangeEvent(ServerPlayer player, String oldGroup, String oldForm, String newGroup, String newForm) {
			this.player = player;
			this.oldGroup = oldGroup == null ? "" : oldGroup;
			this.oldForm = oldForm == null ? "" : oldForm;
			this.newGroup = newGroup == null ? "" : newGroup;
			this.newForm = newForm == null ? "" : newForm;
		}

		public boolean isTransform() {
			return oldForm.isEmpty() && !newForm.isEmpty();
		}

		public boolean isUntransform() {
			return !oldForm.isEmpty() && newForm.isEmpty();
		}

		@java.lang.SuppressWarnings("all")
		public ServerPlayer getPlayer() {
			return this.player;
		}

		@java.lang.SuppressWarnings("all")
		public String getOldGroup() {
			return this.oldGroup;
		}

		@java.lang.SuppressWarnings("all")
		public String getOldForm() {
			return this.oldForm;
		}

		@java.lang.SuppressWarnings("all")
		public String getNewGroup() {
			return this.newGroup;
		}

		@java.lang.SuppressWarnings("all")
		public String getNewForm() {
			return this.newForm;
		}
	}


	/**
	 * Notification fired when a player's stack form changes.
	 */
	public static class StackFormChangeEvent extends Event {
		private final ServerPlayer player;
		private final String oldGroup;
		private final String oldForm;
		private final String newGroup;
		private final String newForm;

		public StackFormChangeEvent(ServerPlayer player, String oldGroup, String oldForm, String newGroup, String newForm) {
			this.player = player;
			this.oldGroup = oldGroup == null ? "" : oldGroup;
			this.oldForm = oldForm == null ? "" : oldForm;
			this.newGroup = newGroup == null ? "" : newGroup;
			this.newForm = newForm == null ? "" : newForm;
		}

		public boolean isTransform() {
			return oldForm.isEmpty() && !newForm.isEmpty();
		}

		public boolean isUntransform() {
			return !oldForm.isEmpty() && newForm.isEmpty();
		}

		@java.lang.SuppressWarnings("all")
		public ServerPlayer getPlayer() {
			return this.player;
		}

		@java.lang.SuppressWarnings("all")
		public String getOldGroup() {
			return this.oldGroup;
		}

		@java.lang.SuppressWarnings("all")
		public String getOldForm() {
			return this.oldForm;
		}

		@java.lang.SuppressWarnings("all")
		public String getNewGroup() {
			return this.newGroup;
		}

		@java.lang.SuppressWarnings("all")
		public String getNewForm() {
			return this.newForm;
		}
	}
}
