// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.quest.objectives;

import com.dragonminez.common.quest.QuestObjective;
import net.minecraft.core.BlockPos;
import net.minecraft.world.level.biome.Biome;

public class BiomeObjective extends QuestObjective {
	private final String biomeId;

	public BiomeObjective(String biomeId) {
		super(ObjectiveType.BIOME, 1);
		this.biomeId = biomeId;
	}

	@Override
	public boolean checkProgress(Object... params) {
		if (params.length > 0 && params[0] instanceof Biome biome) {
			String currentBiome = biome.toString();
			if (currentBiome.contains(biomeId)) {
				setProgress(1);
				return true;
			}
		}
		return false;
	}

	@java.lang.SuppressWarnings("all")
	public String getBiomeId() {
		return this.biomeId;
	}
}
