// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.quest.objectives;

import com.dragonminez.common.quest.QuestObjective;
import net.minecraft.core.BlockPos;

public class CoordsObjective extends QuestObjective {
	private final BlockPos targetPos;
	private final int radius;

	public CoordsObjective(BlockPos targetPos, int radius) {
		super(ObjectiveType.COORDS, 1);
		this.targetPos = targetPos;
		this.radius = radius;
	}

	@Override
	public boolean checkProgress(Object... params) {
		if (params.length > 0 && params[0] instanceof BlockPos playerPos) {
			double distance = Math.sqrt(playerPos.distSqr(targetPos));
			if (distance <= radius) {
				setProgress(1);
				return true;
			}
		}
		return false;
	}

	@java.lang.SuppressWarnings("all")
	public BlockPos getTargetPos() {
		return this.targetPos;
	}

	@java.lang.SuppressWarnings("all")
	public int getRadius() {
		return this.radius;
	}
}
