// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.quest.objectives;

import com.dragonminez.common.quest.QuestObjective;
import net.minecraft.world.level.Level;

public class DimensionObjective extends QuestObjective {
    private final String dimensionId;

    public DimensionObjective(String dimensionId) {
        super(ObjectiveType.DIMENSION, 1);
        this.dimensionId = dimensionId;
    }

    @Override
    public boolean checkProgress(Object... params) {
        if (params.length > 0 && params[0] instanceof Level level) {
            if (level.dimension().location().toString().equals(dimensionId)) {
                setProgress(1);
                return true;
            }
        }
        return false;
    }

    @java.lang.SuppressWarnings("all")
    public String getDimensionId() {
        return this.dimensionId;
    }
}
