// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.quest.objectives;

import com.dragonminez.common.quest.QuestObjective;
import net.minecraft.core.BlockPos;
import net.minecraft.world.level.Level;

public class StructureObjective extends QuestObjective {
	private final String structureId;

	public StructureObjective(String structureId) {
		super(ObjectiveType.STRUCTURE, 1);
		this.structureId = structureId;
	}

	@Override
	public boolean checkProgress(Object... params) {
		if (params.length >= 2 && params[0] instanceof Level level && params[1] instanceof BlockPos pos) {
			setProgress(1);
			return true;
		}
		return false;
	}

	@java.lang.SuppressWarnings("all")
	public String getStructureId() {
		return this.structureId;
	}
}
