// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.util.types.items;

import com.google.gson.GsonBuilder;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import java.util.HashMap;
import java.util.Map;

public class EnchantedBookDTO extends EnchantedItemDTO {
    protected String itemType;
    protected Map<String, Integer> enchantments = new HashMap<>();

    public EnchantedBookDTO(Map<String, Integer> enchantments) {
        super("enchanted_book", "minecraft:enchanted_book", 1, enchantments);
        this.enchantments = enchantments;
    }

    @Override
    public ItemStack getItemStack() {
        // Enchantment holders require registry access at apply time; return book base item.
        return new ItemStack(Items.ENCHANTED_BOOK);
    }

    @Override
    public String toJson() {
        return new GsonBuilder().setPrettyPrinting().create().toJson(this, EnchantedBookDTO.class);
    }

    @java.lang.SuppressWarnings("all")
    public String getItemType() {
        return this.itemType;
    }

    @java.lang.SuppressWarnings("all")
    public Map<String, Integer> getEnchantments() {
        return this.enchantments;
    }

    @java.lang.SuppressWarnings("all")
    public void setItemType(final String itemType) {
        this.itemType = itemType;
    }

    @java.lang.SuppressWarnings("all")
    public void setEnchantments(final Map<String, Integer> enchantments) {
        this.enchantments = enchantments;
    }

    @java.lang.SuppressWarnings("all")
    public EnchantedBookDTO() {
    }
}
