// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.util.types.items;

import com.google.gson.GsonBuilder;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;
import net.minecraft.core.registries.BuiltInRegistries;

public class GenericItemDTO {
    protected String itemType;
    protected String itemId;
    protected int count = 1;

    public GenericItemDTO(String itemId, int count) {
        this.itemType = "generic_item";
        this.itemId = itemId;
        this.count = count;
    }

    public GenericItemDTO(String itemType, String itemId, int count) {
        this.itemType = itemType;
        this.itemId = itemId;
        this.count = count;
    }

    public ItemStack getItemStack() {
        var item = BuiltInRegistries.ITEM.get(ResourceLocation.parse(this.getItemId()));
        if (item != null) {
            return new ItemStack(item, this.count);
        }
        return ItemStack.EMPTY;
    }

    public String toJson() {
        return new GsonBuilder().setPrettyPrinting().create().toJson(this, GenericItemDTO.class);
    }

    @java.lang.SuppressWarnings("all")
    public String getItemType() {
        return this.itemType;
    }

    @java.lang.SuppressWarnings("all")
    public String getItemId() {
        return this.itemId;
    }

    @java.lang.SuppressWarnings("all")
    public int getCount() {
        return this.count;
    }

    @java.lang.SuppressWarnings("all")
    public void setItemType(final String itemType) {
        this.itemType = itemType;
    }

    @java.lang.SuppressWarnings("all")
    public void setItemId(final String itemId) {
        this.itemId = itemId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCount(final int count) {
        this.count = count;
    }

    @java.lang.SuppressWarnings("all")
    public GenericItemDTO() {
    }
}
