// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.util.types.items;

import com.google.gson.GsonBuilder;
import java.util.Map;

public class LingeringPotionDTO extends PotionDTO {
    public LingeringPotionDTO(String potion, Map<String, Integer> mobEffects) {
        super("lingering_potion", "minecraft:lingering_potion", 1, potion, mobEffects);
    }

    @Override
    public String toJson() {
        return new GsonBuilder().setPrettyPrinting().create().toJson(this, LingeringPotionDTO.class);
    }

    @java.lang.SuppressWarnings("all")
    public LingeringPotionDTO() {
    }
}
