// Generated by delombok at Tue Aug 04 23:08:17 IDT 2026
package com.dragonminez.common.wish;

import net.minecraft.server.level.ServerPlayer;

public abstract class Wish {
    private final String name;
    private final String description;
    private final String type;

    public abstract void grant(ServerPlayer player);

    public abstract String toJson();

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public String getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    public Wish(final String name, final String description, final String type) {
        this.name = name;
        this.description = description;
        this.type = type;
    }
}
